#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)0xA5FC;

#include "../../../generic/capt_seq.c"

void __attribute__((naked,noinline)) sub_FFD15B58_my(){ 
 asm volatile(
                "STMFD   SP!, {R0-R10,LR}\n"
                "MOV     R6, #0\n"
                "MOV     R4, R0\n"
                "BL      sub_FFD166AC\n"
                "MVN     R1, #0\n"
                "BL      sub_FFC19408\n"
                "MOV     R2, #4\n"
                "ADD     R1, SP, #8\n"
                "MOV     R0, #0x8A\n"
                "BL      sub_FFC5BCC0\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x20A\n"
                "LDRNE   R0, =0xFFD15D60\n"
                "BLNE    sub_FFC0C090\n"
                "LDR     R8, =0x1993C\n"
                "LDR     R5, =0x19890\n"
                "LDRSH   R1, [R8,#0xE]\n"
                "LDR     R0, [R5,#0x74]\n"
                "BL      sub_FFCDAF78\n"
                "BL      sub_FFC3A2E0\n"
                "LDR     R2, =0xA600\n"
                "ADD     R3, R4, #0x8C\n"
                "STRH    R0, [R4,#0x88]\n"
            //  "STRD    R2, [SP]\n"
                ".long	 0xE1CD20F0\n"
                "MOV     R1, R0\n"
                "LDRH    R0, [R5,#0x4C]\n"
                "LDRSH   R2, [R8,#0xC]\n"
                "LDR     R3, =0xA5FC\n"
                "BL      sub_FFD16B98\n"
                "BL      capt_seq_hook_set_nr\n"
                "B	 sub_FFD15BCC\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC4DE48_my(){ 
 asm volatile(
                "STMFD   SP!, {R3-R7,LR}\n"
                "LDR     R4, [R0,#0xC]\n"
                "LDR     R5, =0x19890\n"
                "LDR     R0, [R4,#8]\n"
                "LDR     R6, =0x820A\n"
                "ORR     R0, R0, #1\n"
                "STR     R0, [R4,#8]\n"
                "LDRH    R0, [R5]\n"
                "CMP     R0, R6\n"
                "BEQ     loc_FFC4DEE4\n"
                "LDRH    R0, [R5,#0x7E]\n"
                "CMP     R0, #3\n"
                "BEQ     loc_FFC4DF48\n"
                "LDR     R0, [R4,#0xC]\n"
                "CMP     R0, #1\n"
                "BLS     loc_FFC4DEF0\n"
                "LDRH    R0, [R5,#0x7C]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC4DF48\n"
                "LDRH    R0, [R5,#0x78]\n"
                "CMP     R0, #2\n"
                "BNE     loc_FFC4DEFC\n"
                "BL      sub_FFD1456C\n"
                "LDRH    R0, [R5]\n"
                "CMP     R0, R6\n"
                "BEQ     loc_FFC4DEE4\n"
                "LDRH    R0, [R5,#0x7E]\n"
                "CMP     R0, #3\n"
                "BEQ     loc_FFC4DF48\n"
                "LDR     R0, [R4,#0xC]\n"
                "CMP     R0, #1\n"
                "BLS     loc_FFC4DEF0\n"
                "LDRH    R0, [R5,#0x7C]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC4DF48\n"
                "LDRH    R0, [R5,#0x78]\n"
                "CMP     R0, #2\n"
                "BEQ     loc_FFC4DF28\n"
                "B       loc_FFC4DEFC\n"
"loc_FFC4DEE4:\n"
                "LDRH    R0, [R5,#0x7E]\n"
                "CMP     R0, #3\n"
                "BEQ     loc_FFC4DF48\n"
"loc_FFC4DEF0:\n"
                "LDRH    R0, [R5,#0x7C]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC4DF48\n"
"loc_FFC4DEFC:\n"
                "LDRH    R0, [R5,#0x78]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC4DF48\n"
                "LDRH    R0, [R5]\n"
                "CMP     R0, R6\n"
                "LDRNE   R0, [R4,#0xC]\n"
                "CMPNE   R0, #1\n"
                "BLS     loc_FFC4DF48\n"
                "LDR     R0, [R4,#0x10]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC4DF48\n"
"loc_FFC4DF28:\n"
                "LDR     R3, =0x20D\n"
                "LDR     R0, =0x5698\n"
                "STR     R3, [SP]\n"
                "LDR     R0, [R0,#0xC]\n"
                "LDR     R2, =0xEA60\n"
                "LDR     R3, =0xFFC4DDC8\n"
                "MOV     R1, #0x40000000\n"
                "BL      sub_FFC51928\n"
"loc_FFC4DF48:\n"
                "BL      sub_FFC4DD2C\n"
                "MOV     R0, #2\n"
                "BL      sub_FFC49530\n"
                "BL      sub_FFD14188\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD147F0\n"
                "TST     R0, #1\n"
                "MOVNE   R2, R4\n"
                "LDMNEFD SP!, {R3-R7,LR}\n"
                "MOVNE   R1, #1\n"
                "BNE     sub_FFC4C774\n"
                "BL      sub_FFD27B40\n"
                "BL      sub_FFC5BE50\n"
                "STR     R0, [R4,#0x14]\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD15A70\n"
                "BL      sub_FFD16540\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD15B58_my\n"         //----------->
                "BL      capt_seq_hook_raw_here\n"  //+
                "MOV     R2, R4\n"
                "MOV     R1, #1\n"
                "BL      sub_FFC4C774\n"
                "BL      sub_FFD15F94\n"
                "CMP     R0, #0\n"
                "LDRNE   R0, [R4,#8]\n"
                "ORRNE   R0, R0, #0x2000\n"
                "STRNE   R0, [R4,#8]\n"
                "LDRH    R0, [R5,#0x7E]\n"
                "CMP     R0, #3\n"
                "BEQ     loc_FFC4DFDC\n"
                "LDRH    R0, [R5,#0x7C]\n"
                "CMP     R0, #0\n"
                "LDREQH  R0, [R5,#0x78]\n"
                "CMPEQ   R0, #2\n"
                "MOVEQ   R0, R4\n"
                "LDMEQFD SP!, {R3-R7,LR}\n"
                "BEQ     sub_FFD145C0\n"
"loc_FFC4DFDC:\n"
                "LDMFD   SP!, {R3-R7,PC}\n"
 );
}


void __attribute__((naked,noinline)) CaptSeqTask() //#fs
{
	asm volatile (
                "STMFD   SP!, {R3-R7,LR}\n"
                "LDR     R6, =0x5698\n"
"loc_FFC4E2E8:\n"
                "LDR     R0, [R6,#0x10]\n"
                "MOV     R2, #0\n"
                "MOV     R1, SP\n"
                "BL      sub_FFC19658\n"
                "TST     R0, #1\n"
                "BEQ     loc_FFC4E314\n"
                "LDR     R1, =0x43F\n"
                "LDR     R0, =0xFFC4DDC8\n"
                "BL      sub_FFC0C090\n"
                "BL      sub_FFC0BE48\n"
                "LDMFD   SP!, {R3-R7,PC}\n"
"loc_FFC4E314:\n"
                "LDR     R0, [SP]\n"
                "LDR     R1, [R0]\n"
                "CMP     R1, #0x1A\n"
                "ADDLS   PC, PC, R1,LSL#2\n"
                "B       loc_FFC4E4BC\n"
"loc_FFC4E328:\n"
                "B       loc_FFC4E394\n"
"loc_FFC4E32C:\n"
                "B       loc_FFC4E39C\n"
"loc_FFC4E330:\n"
                "B       loc_FFC4E3A4\n"
"loc_FFC4E334:\n"
                "B       loc_FFC4E3B8\n"
"loc_FFC4E338:\n"
                "B       loc_FFC4E3B0\n"
"loc_FFC4E33C:\n"
                "B       loc_FFC4E3C0\n"
"loc_FFC4E340:\n"
                "B       loc_FFC4E3C8\n"
"loc_FFC4E344:\n"
                "B       loc_FFC4E3D4\n"
"loc_FFC4E348:\n"
                "B       loc_FFC4E42C\n"
"loc_FFC4E34C:\n"
                "B       loc_FFC4E3B8\n"
"loc_FFC4E350:\n"
                "B       loc_FFC4E434\n"
"loc_FFC4E354:\n"
                "B       loc_FFC4E43C\n"
"loc_FFC4E358:\n"
                "B       loc_FFC4E444\n"
"loc_FFC4E35C:\n"
                "B       loc_FFC4E44C\n"
"loc_FFC4E360:\n"
                "B       loc_FFC4E454\n"
"loc_FFC4E364:\n"
                "B       loc_FFC4E45C\n"
"loc_FFC4E368:\n"
                "B       loc_FFC4E464\n"
"loc_FFC4E36C:\n"
                "B       loc_FFC4E46C\n"
"loc_FFC4E370:\n"
                "B       loc_FFC4E474\n"
"loc_FFC4E374:\n"
                "B       loc_FFC4E47C\n"
"loc_FFC4E378:\n"
                "B       loc_FFC4E484\n"
"loc_FFC4E37C:\n"
                "B       loc_FFC4E490\n"
"loc_FFC4E380:\n"
                "B       loc_FFC4E49C\n"
"loc_FFC4E384:\n"
                "B       loc_FFC4E4A4\n"
"loc_FFC4E388:\n"
                "B       loc_FFC4E4AC\n"
"loc_FFC4E38C:\n"
                "B       loc_FFC4E4B4\n"
"loc_FFC4E390:\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E394:\n"
                "BL      sub_FFD141D0\n"
                "BL      shooting_expo_param_override\n"  // +
                "B       loc_FFC4E3CC\n"
"loc_FFC4E39C:\n"
                "BL      sub_FFC4DE48_my\n"     //---------------->
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3A4:\n"
                "MOV     R0, #1\n"
                "BL      sub_FFD14360\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3B0:\n"
                "BL      sub_FFD13E64\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3B8:\n"
                "BL      sub_FFD14178\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3C0:\n"
                "BL      sub_FFD14180\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3C8:\n"
                "BL      sub_FFD14280\n"
"loc_FFC4E3CC:\n"
                "BL      sub_FFC4C3DC\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E3D4:\n"
                "LDR     R4, [R0,#0xC]\n"
                "BL      sub_FFD14188\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD14BE0\n"
                "TST     R0, #1\n"
                "MOV     R5, R0\n"
                "BNE     loc_FFC4E414\n"
                "BL      sub_FFC5BE50\n"
                "STR     R0, [R4,#0x14]\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD15A70\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD15FF4\n"
                "MOV     R5, R0\n"
                "LDR     R0, [R4,#0x14]\n"
                "BL      sub_FFC5C064\n"
"loc_FFC4E414:\n"
                "BL      sub_FFD14178\n"
                "MOV     R2, R4\n"
                "MOV     R1, #8\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC4C774\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E42C:\n"
                "BL      sub_FFD142DC\n"
                "B       loc_FFC4E3CC\n"
"loc_FFC4E434:\n"
                "BL      sub_FFD14E4C\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E43C:\n"
                "BL      sub_FFD15004\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E444:\n"
                "BL      sub_FFD15094\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E44C:\n"
                "BL      sub_FFD15148\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E454:\n"
                "BL      sub_FFD153D4\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E45C:\n"
                "BL      sub_FFD15424\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E464:\n"
                "MOV     R0, #0\n"
                "B       loc_FFC4E488\n"
"loc_FFC4E46C:\n"
                "BL      sub_FFD155E8\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E474:\n"
                "BL      sub_FFD1567C\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E47C:\n"
                "BL      sub_FFD1573C\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E484:\n"
                "MOV     R0, #1\n"
"loc_FFC4E488:\n"
                "BL      sub_FFD154A8\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E490:\n"
                "BL      sub_FFD144AC\n"
                "BL      sub_FFC4E5E4\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E49C:\n"
                "BL      sub_FFD15264\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E4A4:\n"
                "BL      sub_FFD1533C\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E4AC:\n"
                "BL      sub_FFC4DD2C\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E4B4:\n"
                "BL      sub_FFC15C28\n"
                "B       loc_FFC4E4C8\n"
"loc_FFC4E4BC:\n"
                "LDR     R1, =0x523\n"
                "LDR     R0, =0xFFC4DDC8\n"
                "BL      sub_FFC0C090\n"
"loc_FFC4E4C8:\n"
                "LDR     R0, [SP]\n"
                "LDR     R1, [R0,#4]\n"
                "LDR     R0, [R6,#0xC]\n"
                "BL      sub_FFC193D4\n"
                "LDR     R4, [SP]\n"
                "LDR     R0, [R4,#8]\n"
                "CMP     R0, #0\n"
                "LDREQ   R0, =0xFFC4DDC8\n"
                "MOVEQ   R1, #0xFC\n"
                "BLEQ    sub_FFC0C090\n"
                "MOV     R0, #0\n"
                "STR     R0, [R4,#8]\n"
                "B       loc_FFC4E2E8\n"
    );
} //#fe


void __attribute__((naked,noinline)) exp_drv_task(){
 asm volatile(
"                STMFD   SP!, {R4-R8,LR}\n"
"                SUB     SP, SP, #0x20\n"
"                LDR     R8, =0xBB8\n"
"                LDR     R7, =0x6D70\n"
"                LDR     R5, =0x41350\n"
"                MOV     R0, #0\n"
"                ADD     R6, SP, #0x38-0x28\n"
"                STR     R0, [SP,#0x38-0x2C]\n"
"loc_FFC98F38:\n"
"                LDR     R0, [R7,#0x20]\n"
"                MOV     R2, #0\n"
"                ADD     R1, SP, #0x38-0x1C\n"
"                BL      sub_FFC19658\n"
"                LDR     R0, [SP,#0x38-0x2C]\n"
"                CMP     R0, #1\n"
"                BNE     loc_FFC98F80\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R0, [R0]\n"
"                CMP     R0, #0x13\n"
"                CMPNE   R0, #0x14\n"
"                CMPNE   R0, #0x15\n"
"                BEQ     loc_FFC99100\n"
"                CMP     R0, #0x26\n"
"                BEQ     loc_FFC9906C\n"
"                ADD     R1, SP, #0x38-0x2C\n"
"                MOV     R0, #0\n"
"                BL      sub_FFC98EC8\n"
"loc_FFC98F80:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R1, [R0]\n"
"                CMP     R1, #0x2B\n"
"                BNE     loc_FFC98FB0\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                BL      sub_FFC9A1F8\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R1, #1\n"
"                BL      sub_FFC193D4\n"
"                BL      sub_FFC0BE48\n"
"                ADD     SP, SP, #0x20\n"
"                LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC98FB0:\n"
"                CMP     R1, #0x2A\n"
"                BNE     loc_FFC98FCC\n"
"                LDR     R2, [R0,#0x88]!\n"
"                LDR     R1, [R0,#4]\n"
"                MOV     R0, R1\n"
"                BLX     R2\n"
"                B       loc_FFC99564\n"
"loc_FFC98FCC:\n"
"                CMP     R1, #0x24\n"
"                BNE     loc_FFC9901C\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R1, #0x80\n"
"                BL      sub_FFC19408\n"
"                LDR     R0, =0xFFC959B4\n"
"                MOV     R1, #0x80\n"
"                BL      sub_FFD0A51C\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R2, R8\n"
"                MOV     R1, #0x80\n"
"                BL      sub_FFC1930C\n"
"                TST     R0, #1\n"
"                LDRNE   R1, =0xD07\n"
"                BNE     loc_FFC990DC\n"
"loc_FFC99008:\n"
"                LDR     R1, [SP,#0x38-0x1C]\n"
"                LDR     R0, [R1,#0x8C]\n"
"                LDR     R1, [R1,#0x88]\n"
"                BLX     R1\n"
"                B       loc_FFC99564\n"
"loc_FFC9901C:\n"
"                CMP     R1, #0x25\n"
"                BNE     loc_FFC99064\n"
"                ADD     R1, SP, #0x38-0x2C\n"
"                BL      sub_FFC98EC8\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R1, #0x100\n"
"                BL      sub_FFC19408\n"
"                MOV     R1, #0x100\n"
"                LDR     R0, =0xFFC959C4\n" //
"                BL      sub_FFD0ACDC\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R2, R8\n"
"                MOV     R1, #0x100\n"
"                BL      sub_FFC1930C\n"
"                TST     R0, #1\n"
"                BEQ     loc_FFC99008\n"
"                LDR     R1, =0xD11\n"
"                B       loc_FFC990DC\n"
"loc_FFC99064:\n"
"                CMP     R1, #0x26\n"
"                BNE     loc_FFC9907C\n"
"loc_FFC9906C:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                ADD     R1, SP, #0x38-0x2C\n"
"                BL      sub_FFC98EC8\n"
"                B       loc_FFC99008\n"
"loc_FFC9907C:\n"
"                CMP     R1, #0x27\n"
"                CMPNE   R1, #0x28\n"
"                BNE     loc_FFC990E8\n"
"                ADD     R1, SP, #0x38-0x2C\n"
"                BL      sub_FFC98EC8\n"
"                LDR     R4, [SP,#0x38-0x1C]\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R1, #0x40\n"
"                BL      sub_FFC19408\n"
"                LDR     R0, [R4]\n"
"                MOV     R1, #0x40\n"
"                CMP     R0, #0x27\n"
"                LDR     R0, =0xFFC95A28\n"
"                BNE     loc_FFC990BC\n"
"                BL      sub_FFD0A5BC\n"
"                B       loc_FFC990C0\n"
"loc_FFC990BC:\n"
"                BL      sub_FFD0A648\n"
"loc_FFC990C0:\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R2, R8\n"
"                MOV     R1, #0x40\n"
"                BL      sub_FFC1930C\n"
"                TST     R0, #1\n"
"                BEQ     loc_FFC99008\n"
"                LDR     R1, =0xD1F\n"
"loc_FFC990DC:\n"
"                LDR     R0, =0xFFC960C4\n"
"                BL      sub_FFC0C090\n"
"                B       loc_FFC99008\n"
"loc_FFC990E8:\n"
"                CMP     R1, #0x29\n"
"                BNE     loc_FFC99100\n"
"                BL      sub_FFC77FEC\n"
"                BL      sub_FFC78D6C\n"
"                BL      sub_FFC7882C\n"
"                B       loc_FFC99008\n"
"loc_FFC99100:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                MOV     R4, #1\n"
"                LDR     R1, [R0]\n"
"                CMP     R1, #0x11\n"
"                CMPNE   R1, #0x12\n"
"                BNE     loc_FFC99170\n"
"                LDR     R1, [R0,#0x7C]\n"
"                ADD     R1, R1, R1,LSL#1\n"
"                ADD     R1, R0, R1,LSL#2\n"
"                SUB     R1, R1, #8\n"
"                LDMIA   R1, {R2-R4}\n"
"                STMIA   R6, {R2-R4}\n"
"                BL      sub_FFC97A44\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R1, [R0,#0x7C]\n"
"                LDR     R3, [R0,#0x88]\n"
"                LDR     R2, [R0,#0x8C]\n"
"                ADD     R0, R0, #4\n"
"                BLX     R3\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                BL      sub_FFC9A5CC\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R1, [R0,#0x7C]\n"
"                LDR     R3, [R0,#0x90]\n"
"                LDR     R2, [R0,#0x94]\n"
"                ADD     R0, R0, #4\n"
"                BLX     R3\n"
"                B       loc_FFC994A4\n"
"loc_FFC99170:\n"
"                CMP     R1, #0x13\n"
"                CMPNE   R1, #0x14\n"
"                CMPNE   R1, #0x15\n"
"                BNE     loc_FFC99224\n"
"                ADD     R3, SP, #0x38-0x2C\n"
"                MOV     R2, SP\n"
"                ADD     R1, SP, #0x38-0x28\n"
"                BL      sub_FFC97C8C\n"
"                CMP     R0, #1\n"
"                MOV     R4, R0\n"
"                CMPNE   R4, #5\n"
"                BNE     loc_FFC991C0\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                MOV     R2, R4\n"
"                LDR     R1, [R0,#0x7C]!\n"
"                LDR     R12, [R0,#0xC]!\n"
"                LDR     R3, [R0,#4]\n"
"                MOV     R0, SP\n"
"                BLX     R12\n"
"                B       loc_FFC991F8\n"
"loc_FFC991C0:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                CMP     R4, #2\n"
"                LDR     R3, [R0,#0x8C]\n"
"                CMPNE   R4, #6\n"
"                BNE     loc_FFC9920C\n"
"                LDR     R12, [R0,#0x88]\n"
"                MOV     R0, SP\n"
"                MOV     R2, R4\n"
"                MOV     R1, #1\n"
"                BLX     R12\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                MOV     R2, SP\n"
"                ADD     R1, SP, #0x38-0x28\n"
"                BL      sub_FFC98C14\n"
"loc_FFC991F8:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R2, [SP,#0x38-0x2C]\n"
"                MOV     R1, R4\n"
"                BL      sub_FFC98E68\n"
"                B       loc_FFC994A4\n"
"loc_FFC9920C:\n"
"                LDR     R1, [R0,#0x7C]\n"
"                LDR     R12, [R0,#0x88]\n"
"                ADD     R0, R0, #4\n"
"                MOV     R2, R4\n"
"                BLX     R12\n"
"                B       loc_FFC994A4\n"
"loc_FFC99224:\n"
"                CMP     R1, #0x20\n"
"                CMPNE   R1, #0x21\n"
"                BNE     loc_FFC99270\n"
"                LDR     R1, [R0,#0x7C]\n"
"                ADD     R1, R1, R1,LSL#1\n"
"                ADD     R1, R0, R1,LSL#2\n"
"                SUB     R1, R1, #8\n"
"                LDMIA   R1, {R2-R4}\n"
"                STMIA   R6, {R2-R4}\n"
"                BL      sub_FFC96FC8\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R1, [R0,#0x7C]\n"
"                LDR     R3, [R0,#0x88]\n"
"                LDR     R2, [R0,#0x8C]\n"
"                ADD     R0, R0, #4\n"
"                BLX     R3\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                BL      sub_FFC972C4\n"
"                B       loc_FFC994A4\n"
"loc_FFC99270:\n"
"                ADD     R1, R0, #4\n"
"                LDMIA   R1, {R2,R3,R12}\n"
"                STMIA   R6, {R2,R3,R12}\n"
"                LDR     R1, [R0]\n"
"                CMP     R1, #0x23\n"
"                ADDLS   PC, PC, R1,LSL#2\n"
"                B       loc_FFC99484\n"
"loc_FFC9928C:\n"
"                B       loc_FFC9931C\n"
"loc_FFC99290:\n"
"                B       loc_FFC9931C\n"
"loc_FFC99294:\n"
"                B       loc_FFC9936C\n"
"loc_FFC99298:\n"
"                B       loc_FFC99374\n"
"loc_FFC9929C:\n"
"                B       loc_FFC99374\n"
"loc_FFC992A0:\n"
"                B       loc_FFC99374\n"
"loc_FFC992A4:\n"
"                B       loc_FFC9931C\n"
"loc_FFC992A8:\n"
"                B       loc_FFC9936C\n"
"loc_FFC992AC:\n"
"                B       loc_FFC99374\n"
"loc_FFC992B0:\n"
"                B       loc_FFC99374\n"
"loc_FFC992B4:\n"
"                B       loc_FFC9938C\n"
"loc_FFC992B8:\n"
"                B       loc_FFC9938C\n"
"loc_FFC992BC:\n"
"                B       loc_FFC99478\n"
"loc_FFC992C0:\n"
"                B       loc_FFC99480\n"
"loc_FFC992C4:\n"
"                B       loc_FFC99480\n"
"loc_FFC992C8:\n"
"                B       loc_FFC99480\n"
"loc_FFC992CC:\n"
"                B       loc_FFC99480\n"
"loc_FFC992D0:\n"
"                B       loc_FFC99484\n"
"loc_FFC992D4:\n"
"                B       loc_FFC99484\n"
"loc_FFC992D8:\n"
"                B       loc_FFC99484\n"
"loc_FFC992DC:\n"
"                B       loc_FFC99484\n"
"loc_FFC992E0:\n"
"                B       loc_FFC99484\n"
"loc_FFC992E4:\n"
"                B       loc_FFC9937C\n"
"loc_FFC992E8:\n"
"                B       loc_FFC99384\n"
"loc_FFC992EC:\n"
"                B       loc_FFC99384\n"
"loc_FFC992F0:\n"
"                B       loc_FFC99398\n"
"loc_FFC992F4:\n"
"                B       loc_FFC993A0\n"
"loc_FFC992F8:\n"
"                B       loc_FFC993D0\n"
"loc_FFC992FC:\n"
"                B       loc_FFC99400\n"
"loc_FFC99300:\n"
"                B       loc_FFC99430\n"
"loc_FFC99304:\n"
"                B       loc_FFC99460\n"
"loc_FFC99308:\n"
"                B       loc_FFC99460\n"
"loc_FFC9930C:\n"
"                B       loc_FFC99484\n"
"loc_FFC99310:\n"
"                B       loc_FFC99484\n"
"loc_FFC99314:\n"
"                B       loc_FFC99468\n"
"loc_FFC99318:\n"
"                B       loc_FFC99470\n"
"loc_FFC9931C:\n"
"                BL      sub_FFC95EAC\n"
"                B       loc_FFC99484\n"
"loc_FFC9936C:\n"
"                BL      sub_FFC96134\n"
"                B       loc_FFC99484\n"
"loc_FFC99374:\n"
"                BL      sub_FFC96338\n"
"                B       loc_FFC99484\n"
"loc_FFC9937C:\n"
"                BL      sub_FFC965A0\n"
"                B       loc_FFC99484\n"
"loc_FFC99384:\n"
"                BL      sub_FFC96794\n"
"                B       loc_FFC99484\n"
"loc_FFC9938C:\n"
"                BL      sub_FFC969F8_my\n" //->
"                MOV     R4, #0\n"
"                B       loc_FFC99484\n"
"loc_FFC99398:\n"
"                BL      sub_FFC96B34\n"
"                B       loc_FFC99484\n"
"loc_FFC993A0:\n"
"                LDRH    R1, [R0,#4]\n"
"                STRH    R1, [SP,#0x38-0x28]\n"
"                LDRH    R1, [R5,#2]\n"
"                STRH    R1, [SP,#0x38-0x26]\n"
"                LDRH    R1, [R5,#4]\n"
"                STRH    R1, [SP,#0x38-0x24]\n"
"                LDRH    R1, [R5,#6]\n"
"                STRH    R1, [SP,#0x38-0x22]\n"
"                LDRH    R1, [R0,#0xC]\n"
"                STRH    R1, [SP,#0x38-0x20]\n"
"                BL      sub_FFC9A26C\n"
"                B       loc_FFC99484\n"
"loc_FFC993D0:\n"
"                LDRH    R1, [R0,#4]\n"
"                STRH    R1, [SP,#0x38-0x28]\n"
"                LDRH    R1, [R5,#2]\n"
"                STRH    R1, [SP,#0x38-0x26]\n"
"                LDRH    R1, [R5,#4]\n"
"                STRH    R1, [SP,#0x38-0x24]\n"
"                LDRH    R1, [R5,#6]\n"
"                STRH    R1, [SP,#0x38-0x22]\n"
"                LDRH    R1, [R5,#8]\n"
"                STRH    R1, [SP,#0x38-0x20]\n"
"                BL      sub_FFC9A3E8\n"
"                B       loc_FFC99484\n"
"loc_FFC99400:\n"
"                LDRH    R1, [R5]\n"
"                STRH    R1, [SP,#0x38-0x28]\n"
"                LDRH    R1, [R0,#6]\n"
"                STRH    R1, [SP,#0x38-0x26]\n"
"                LDRH    R1, [R5,#4]\n"
"                STRH    R1, [SP,#0x38-0x24]\n"
"                LDRH    R1, [R5,#6]\n"
"                STRH    R1, [SP,#0x38-0x22]\n"
"                LDRH    R1, [R5,#8]\n"
"                STRH    R1, [SP,#0x38-0x20]\n"
"                BL      sub_FFC9A494\n"
"                B       loc_FFC99484\n"
"loc_FFC99430:\n"
"                LDRH    R1, [R5]\n"
"                STRH    R1, [SP,#0x38-0x28]\n"
"                LDRH    R1, [R5,#2]\n"
"                STRH    R1, [SP,#0x38-0x26]\n"
"                LDRH    R1, [R5,#4]\n"
"                STRH    R1, [SP,#0x38-0x24]\n"
"                LDRH    R1, [R5,#6]\n"
"                STRH    R1, [SP,#0x38-0x22]\n"
"                LDRH    R1, [R0,#0xC]\n"
"                STRH    R1, [SP,#0x38-0x20]\n"
"                BL      sub_FFC9A534\n"
"                B       loc_FFC99484\n"
"loc_FFC99460:\n"
"                BL      sub_FFC96D8C\n"
"                B       loc_FFC99484\n"
"loc_FFC99468:\n"
"                BL      sub_FFC973C8\n"
"                B       loc_FFC99484\n"
"loc_FFC99470:\n"
"                BL      sub_FFC975FC\n"
"                B       loc_FFC99484\n"
"loc_FFC99478:\n"
"                BL      sub_FFC97774\n"
"                B       loc_FFC99484\n"
"loc_FFC99480:\n"
"                BL      sub_FFC9790C\n"
"loc_FFC99484:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R1, [R0,#0x7C]\n"
"                LDR     R3, [R0,#0x88]\n"
"                LDR     R2, [R0,#0x8C]\n"
"                ADD     R0, R0, #4\n"
"                BLX     R3\n"
"                CMP     R4, #1\n"
"                BNE     loc_FFC994EC\n"
"loc_FFC994A4:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                MOV     R2, #0xC\n"
"                LDR     R1, [R0,#0x7C]\n"
"                ADD     R1, R1, R1,LSL#1\n"
"                ADD     R0, R0, R1,LSL#2\n"
"                SUB     R4, R0, #8\n"
"                LDR     R0, =0x41350\n"
"                ADD     R1, SP, #0x38-0x28\n"
"                BL      sub_FFE56B0C\n"
"                LDR     R0, =0x4135C\n"
"                MOV     R2, #0xC\n"
"                ADD     R1, SP, #0x38-0x28\n"
"                BL      sub_FFE56B0C\n"
"                LDR     R0, =0x41368\n"
"                MOV     R2, #0xC\n"
"                MOV     R1, R4\n"
"                BL      sub_FFE56B0C\n"
"                B       loc_FFC99564\n"
"loc_FFC994EC:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                LDR     R0, [R0]\n"
"                CMP     R0, #0xB\n"
"                BNE     loc_FFC99534\n"
"                MOV     R3, #0\n"
"                STR     R3, [SP,#0x38-0x38]\n"
"                MOV     R3, #1\n"
"                MOV     R2, #1\n"
"                MOV     R1, #1\n"
"                MOV     R0, #0\n"
"                BL      sub_FFC95CB4\n"
"                MOV     R3, #0\n"
"                STR     R3, [SP,#0x38-0x38]\n"
"                MOV     R3, #1\n"
"                MOV     R2, #1\n"
"                MOV     R1, #1\n"
"                MOV     R0, #0\n"
"                B       loc_FFC99560\n"
"loc_FFC99534:\n"
"                MOV     R3, #1\n"
"                MOV     R2, #1\n"
"                MOV     R1, #1\n"
"                MOV     R0, #1\n"
"                STR     R3, [SP,#0x38-0x38]\n"
"                BL      sub_FFC95CB4\n"
"                MOV     R3, #1\n"
"                MOV     R2, #1\n"
"                MOV     R1, #1\n"
"                MOV     R0, #1\n"
"                STR     R3, [SP,#0x38-0x38]\n"
"loc_FFC99560:\n"
"                BL      sub_FFC95DF4\n"
"loc_FFC99564:\n"
"                LDR     R0, [SP,#0x38-0x1C]\n"
"                BL      sub_FFC9A1F8\n"
"                B       loc_FFC98F38\n"
 );
}



void __attribute__((naked,noinline)) sub_FFC969F8_my(){
 asm volatile(
"                STMFD   SP!, {R4-R8,LR}\n"
"                LDR     R7, =0x6D70\n"
"                MOV     R4, R0\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R1, #0x3E\n"
"                BL      sub_FFC19408\n"
"                LDRSH   R0, [R4,#4]\n"
"                MOV     R2, #0\n"
"                MOV     R1, #0\n"
"                BL      sub_FFC95A48\n"
"                MOV     R6, R0\n"
"                LDRSH   R0, [R4,#6]\n"
"                BL      sub_FFC95B54\n"
"                LDRSH   R0, [R4,#8]\n"
"                BL      sub_FFC95BAC\n"
"                LDRSH   R0, [R4,#0xA]\n"
"                BL      sub_FFC95C04\n"
"                LDRSH   R0, [R4,#0xC]\n"
"                BL      sub_FFC95C5C\n"
"                MOV     R5, R0\n"
"                LDR     R0, [R4]\n"
"                LDR     R8, =0x41368\n"
"                CMP     R0, #0xB\n"
"                MOVEQ   R6, #0\n"
"                MOVEQ   R5, #0\n"
"                BEQ     loc_FFC96A88\n"
"                CMP     R6, #1\n"
"                BNE     loc_FFC96A88\n"
"                LDRSH   R0, [R4,#4]\n"
"                LDR     R1, =0xFFC959A4\n"
"                MOV     R2, #2\n"
"                BL      sub_FFD0A790\n"
"                STRH    R0, [R4,#4]\n"
"                MOV     R0, #0\n"
"                STR     R0, [R7,#0x28]\n"
"                B       loc_FFC96A90\n"
"loc_FFC96A88:\n"
"                LDRH    R0, [R8]\n"
"                STRH    R0, [R4,#4]\n"
"loc_FFC96A90:\n"
"                CMP     R5, #1\n"
"                LDRNEH  R0, [R8,#8]\n" //ldrhne
"                BNE     loc_FFC96AAC\n"
"                LDRSH   R0, [R4,#0xC]\n"
"                LDR     R1, =0xFFC95A38\n"
"                MOV     R2, #0x20\n"
"                BL      sub_FFC9A228\n"
"loc_FFC96AAC:\n"
"                STRH    R0, [R4,#0xC]\n"
"                LDRSH   R0, [R4,#6]\n"
"                BL      sub_FFC77D90_my\n" //->
"                LDRSH   R0, [R4,#8]\n"
"                MOV     R1, #1\n"
"                BL      sub_FFC78524\n"
"                MOV     R1, #0\n"
"                ADD     R0, R4, #8\n"
"                BL      sub_FFC785AC\n"
"                LDRSH   R0, [R4,#0xE]\n"
"                BL      sub_FFC8CDC8\n"
"                LDR     R4, =0xBB8\n"
"                CMP     R6, #1\n"
"                BNE     loc_FFC96B04\n"
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R2, R4\n"
"                MOV     R1, #2\n"
"                BL      sub_FFC1930C\n"
"                TST     R0, #1\n"
"                LDRNE   R1, =0x527\n"
"                LDRNE   R0, =0xFFC960C4\n"
"                BLNE    sub_FFC0C090\n"
"loc_FFC96B04:\n"
"                CMP     R5, #1\n"
"                LDMNEFD SP!, {R4-R8,PC}\n" //ldmfdne
"                LDR     R0, [R7,#0x1C]\n"
"                MOV     R2, R4\n"
"                MOV     R1, #0x20\n"
"                BL      sub_FFC1930C\n"
"                TST     R0, #1\n"
"                LDRNE   R1, =0x52C\n"
"                LDRNE   R0, =0xFFC960C4\n"
"                LDMNEFD SP!, {R4-R8,LR}\n" //ldmfdne
"                BNE     sub_FFC0C090\n"
"                LDMFD   SP!, {R4-R8,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFC77D90_my(){
 asm volatile(
"                STMFD   SP!, {R4-R6,LR}\n"
"                LDR     R5, =0x66FC\n"
"                MOV     R4, R0\n"
"                LDR     R0, [R5,#4]\n"
"                CMP     R0, #1\n"
"                MOVNE   R1, #0x16C\n"
"                LDRNE   R0, =0xFFC77B28\n"
"                BLNE    sub_FFC0C090\n"
"                CMN     R4, #0xC00\n"
"                LDREQSH R4, [R5,#2]\n" //ldrsheq
"                CMN     R4, #0xC00\n"
"                LDREQ   R1, =0x172\n"
"                LDREQ   R0, =0xFFC77B28\n"
"                STRH    R4, [R5,#2]\n"
"                BLEQ    sub_FFC0C090\n"
"                MOV     R0, R4\n"
//"                BL      sub_FFD7B48C\n" //-
"                BL      apex2us\n" //+
"                MOV     R4, R0\n"
//"                BL      nullsub\n"
//"                MOV     R0, R4\n"
"                BL      sub_FFCAC3C8\n"
"                TST     R0, #1\n"
"                LDRNE   R1, =0x177\n"
"                LDMNEFD SP!, {R4-R6,LR}\n" //ldmfdne
"                LDRNE   R0, =0xFFC77B28\n"
"                BNE     sub_FFC0C090\n"
"                LDMFD   SP!, {R4-R6,PC}\n"
 );
}
