
NSTUB(eventproc_export_memShow, 0xff810dc8)

NSTUB(eventproc_export_strlen, 0xff814100)

NSTUB(eventproc_export_CreateTask, 0xff81e8a0)

NSTUB(eventproc_export_ExitTask, 0xff81eb30)

NSTUB(eventproc_export_RotateConsoleZOder, 0xff81f280)

NSTUB(eventproc_export_CPrintf, 0xff81f490)
NSTUB(eventproc_export_CPutChar, 0xff81f4ec)
NSTUB(eventproc_export_GetCh, 0xff81f518)
NSTUB(eventproc_export_GetStringWithPrompt, 0xff81f568)
NSTUB(eventproc_export_OpenConsole, 0xff81f5c8)
NSTUB(eventproc_export_CloseConsole, 0xff81f734)

NSTUB(eventproc_export_StartRedirectUART, 0xff81fe30)
NSTUB(eventproc_export_StopRedirectUART, 0xff81ff48)

NSTUB(eventproc_export_sprintf, 0xff8205f4)

NSTUB(eventproc_export_strcpy, 0xff820674)
NSTUB(eventproc_export_strcmp, 0xff82068c)
NSTUB(eventproc_export_memcmp, 0xff8206d0)

NSTUB(eventproc_export_Fopen_Fut, 0xff836b90)
NSTUB(eventproc_export_Fclose_Fut, 0xff836bd0)
NSTUB(eventproc_export_Fread_Fut, 0xff836c7c)
NSTUB(eventproc_export_Fwrite_Fut, 0xff836cd0)

NSTUB(eventproc_export_Fseek_Fut, 0xff836d70)

NSTUB(eventproc_export_Open, 0xff837070)
NSTUB(eventproc_export_Close, 0xff8370dc)

NSTUB(eventproc_export_Read, 0xff837168)
NSTUB(eventproc_export_Write, 0xff83716c)

NSTUB(eventproc_export_Lseek, 0xff8371f8)
NSTUB(eventproc_export_OpenForScrip, 0xff837218)

NSTUB(eventproc_export_StartCameraLog, 0xff8375cc)
NSTUB(eventproc_export_ShowCameraLog, 0xff8375d0)
NSTUB(eventproc_export_ShowCameraLogInfo, 0xff8375d4)
NSTUB(eventproc_export_StopCameraLog, 0xff8375d8)
NSTUB(eventproc_export_PutsCameraLogEvent, 0xff8375dc)

NSTUB(eventproc_export_NewTaskShell, 0xff837644)

NSTUB(eventproc_export_ExMem, 0xff83765c)

NSTUB(eventproc_export_CreateCountingSemaphore, 0xff83a7e0)
NSTUB(eventproc_export_DeleteSemaphore, 0xff83a838)

NSTUB(eventproc_export_TakeSemaphore, 0xff83a8e4)
NSTUB(eventproc_export_GiveSemaphore, 0xff83a9b4)

NSTUB(eventproc_export_SleepTask, 0xff83ac1c)

NSTUB(eventproc_export_TurnOffE1, 0xff83c534)

NSTUB(eventproc_export_memcpy, 0xff840750)

NSTUB(eventproc_export_ChangePowerState, 0xff863aa0)

NSTUB(eventproc_export_HdmiSimulateModeStop, 0xff863fec)
NSTUB(eventproc_export_HdmiSimulateModeStart, 0xff864014)

NSTUB(eventproc_export_HdmiHpd5VOutput, 0xff8640e0)
NSTUB(eventproc_export_LockHdmiState, 0xff8640e4)
NSTUB(eventproc_export_EdidDump, 0xff86412c)
NSTUB(eventproc_export_HdmiRegDump, 0xff8641f4)

NSTUB(eventproc_export_WriteToRom, 0xff892a80)
NSTUB(eventproc_export_EraseSectorOfRom, 0xff892b10)

NSTUB(eventproc_export_UnLoadScript, 0xff892cd8)

NSTUB(eventproc_export_LoadScript, 0xff892dd0)

NSTUB(eventproc_export_GetTimeOfSystem, 0xff893c3c)

NSTUB(eventproc_export_OpLog_Stop, 0xff8972d8)

NSTUB(eventproc_export_OpLog_WriteToROM, 0xff897334)

NSTUB(eventproc_export_OpLog_ReadFromROM, 0xff897344)
NSTUB(eventproc_export_OpLog_ReadFromSD, 0xff897390)
NSTUB(eventproc_export_OpLog_WriteToSD, 0xff8977d0)
NSTUB(eventproc_export_OpLog_Get, 0xff897c24)
NSTUB(eventproc_export_OpLog_Play, 0xff897c44)

NSTUB(eventproc_export_OpLog_Start, 0xff897d74)

NSTUB(eventproc_export_StartWDT, 0xff898630)
NSTUB(eventproc_export_StopWDT, 0xff898694)

NSTUB(eventproc_export_GetBuildDate, 0xff898784)
NSTUB(eventproc_export_GetBuildTime, 0xff89878c)
NSTUB(eventproc_export_GetFirmwareVersion, 0xff898794)

NSTUB(eventproc_export_CheckSumAll, 0xff8988a0)
NSTUB(eventproc_export_RomCheckSum, 0xff898a90)

NSTUB(eventproc_export_CreateController, 0xff89d7d4)
NSTUB(eventproc_export_DeleteController, 0xff89d890)

NSTUB(eventproc_export_MoveControllerToTopOfZOrder, 0xff89da10)

NSTUB(eventproc_export_GetSelfControllerHandle, 0xff89db50)

NSTUB(eventproc_export_PostLogicalEventForNotPowerType, 0xff89e02c)
NSTUB(eventproc_export_PostLogicalEventToUI, 0xff89e078)
NSTUB(eventproc_export_PostEventShootSeqToUI, 0xff89e0f0)
NSTUB(eventproc_export_ShowLogicalEventName, 0xff89e14c)

NSTUB(eventproc_export_IsControlEventActive, 0xff89ff60)
NSTUB(eventproc_export_UiEvnt_SetLogicalEventActive, 0xff89ffd0)
NSTUB(eventproc_export_SetScriptMode, 0xff8a0020)

NSTUB(eventproc_export_UiEvnt_StartDisguiseCradleStatus, 0xff8a0090)
NSTUB(eventproc_export_UiEvnt_StopDisguiseCradleStatus, 0xff8a00a0)

NSTUB(eventproc_export_UnlockMainPower, 0xff8a01e8)
NSTUB(eventproc_export_LockMainPower, 0xff8a0294)
NSTUB(eventproc_export_SetAutoShutdownTime, 0xff8a0308)

NSTUB(eventproc_export_HardwareDefectWithRestart, 0xff8a04e8)
NSTUB(eventproc_export_HardwareDefect, 0xff8a0538)

NSTUB(eventproc_export_PTM_AllResetToFactorySetting, 0xff8a0758)
NSTUB(eventproc_export_PTM_AllReset, 0xff8a0768)

NSTUB(eventproc_export_PTM_SetCurrentCaptureMode, 0xff8a0a58)

NSTUB(eventproc_export_PTM_GetWorkingCaptureMode, 0xff8a0b1c)

NSTUB(eventproc_export_PTM_SetCurrentItem, 0xff8a0b24)

NSTUB(eventproc_export_PTM_GetCurrentItem, 0xff8a0b30)

NSTUB(eventproc_export_PTM_NextItem, 0xff8a0b9c)
NSTUB(eventproc_export_PTM_PrevItem, 0xff8a0ba0)

NSTUB(eventproc_export_PTM_IsEnableItem, 0xff8a0bb0)
NSTUB(eventproc_export_PTM_SetProprietyEnable, 0xff8a0bb4)

NSTUB(eventproc_export_PTM_BackupUIProperty, 0xff8a0bcc)

NSTUB(eventproc_export_PTM_RestoreUIProperty, 0xff8a0bd4)

NSTUB(eventproc_export_SetCurrentCaptureModeType, 0xff8a922c)
NSTUB(eventproc_export_GetCurrentCaptureModeType, 0xff8a9268)

NSTUB(eventproc_export_GUISrv_StartGUISystem, 0xff8b790c)

NSTUB(eventproc_export_atol, 0xff8b9a14)

NSTUB(eventproc_export_GetLatestHVPosition, 0xff934634)

NSTUB(eventproc_export_SetSDPwrPort, 0xff98ee74)
NSTUB(eventproc_export_GetAdVBattBottom, 0xff98eea0)
NSTUB(eventproc_export_GetAdChValue, 0xff98eea4)
NSTUB(eventproc_export_BeepDrive, 0xff98eea8)
NSTUB(eventproc_export_BeepDriveComp, 0xff98eeac)
NSTUB(eventproc_export_VbattGet, 0xff98eeb0)
NSTUB(eventproc_export_LEDDrive, 0xff98eeb4)
NSTUB(eventproc_export_ShowPhySwStatus, 0xff98eeb8)
NSTUB(eventproc_export_SetRawSWCheckMode, 0xff98eec8)
NSTUB(eventproc_export_OnPrintPhySw, 0xff98eed8)
NSTUB(eventproc_export_OffPrintPhySw, 0xff98eee8)
NSTUB(eventproc_export_GetSwitchStatus, 0xff98eef8)
NSTUB(eventproc_export_ShowSDStatus, 0xff98eefc)
NSTUB(eventproc_export_GetSDDetect, 0xff98ef0c)
NSTUB(eventproc_export_GetSDProtect, 0xff98ef10)
NSTUB(eventproc_export_SetIgnoreAVJACK, 0xff98ef14)
NSTUB(eventproc_export_GetDialEventId, 0xff98ef24)
NSTUB(eventproc_export_GetLcdPosition, 0xff98ef28)
NSTUB(eventproc_export_GetBatteryCoverClose, 0xff98ef2c)
NSTUB(eventproc_export_IsHvSensorExist, 0xff98ef30)

NSTUB(eventproc_export_GetDateAndTime, 0xff98f1e4)

NSTUB(eventproc_export_MonSelEvent, 0xff98f28c)
NSTUB(eventproc_export_MemoryChecker, 0xff98f290)
NSTUB(eventproc_export_VerifyByte, 0xff98f294)
NSTUB(eventproc_export_EraseSignature, 0xff98f298)
NSTUB(eventproc_export_SDump, 0xff98f2a8)

NSTUB(eventproc_export_Dump32, 0xff98f2bc)
NSTUB(eventproc_export_Poke32, 0xff98f2d0)
NSTUB(eventproc_export_Poke16, 0xff98f2e0)
NSTUB(eventproc_export_Poke8, 0xff98f2f0)
NSTUB(eventproc_export_Peek32, 0xff98f300)
NSTUB(eventproc_export_Peek16, 0xff98f304)
NSTUB(eventproc_export_Peek8, 0xff98f308)
NSTUB(eventproc_export_Wait, 0xff98f30c)

NSTUB(eventproc_export_ShowAllTaskInfo, 0xff98f320)

NSTUB(eventproc_export_UIFS_IsAvailableMovieRecOptZoom, 0xff98fc60)
NSTUB(eventproc_export_UIFS_IsAvailableMovieRecDigZoom, 0xff98fc68)
NSTUB(eventproc_export_UIFS_IsAvailableServoAF, 0xff98fc70)
NSTUB(eventproc_export_UIFS_IsAvailableRecMenuAFMode, 0xff98fc78)
NSTUB(eventproc_export_UIFS_IsAutoPopupDownStrobe, 0xff98fc80)
NSTUB(eventproc_export_UIFS_IsAvailableAvTvMode, 0xff98fc88)

NSTUB(eventproc_export_UIFS_SetDialStillRec, 0xff98fe0c)
NSTUB(eventproc_export_UIFS_SetCaptureModeToP, 0xff98fe2c)
NSTUB(eventproc_export_UIFS_SetDialMovieRec, 0xff98fe6c)
NSTUB(eventproc_export_UIFS_SetDialPlay, 0xff98feac)
NSTUB(eventproc_export_UIFS_OpenPopupStrobe, 0xff98fecc)
NSTUB(eventproc_export_UIFS_ClosePopupStrobe, 0xff98fefc)
NSTUB(eventproc_export_UIFS_MountExtFlash, 0xff98ff2c)
NSTUB(eventproc_export_UIFS_UnmountExtFlash, 0xff98ff5c)
NSTUB(eventproc_export_UIFS_ConnectVideo, 0xff98ff8c)
NSTUB(eventproc_export_UIFS_DisconnectVideo, 0xff98ffbc)
NSTUB(eventproc_export_UIFS_MoveZoomTo, 0xff98ffec)
NSTUB(eventproc_export_UIFS_StopPostingUIEvent, 0xff98fff0)
NSTUB(eventproc_export_UIFS_RestartPostingUIEvent, 0xff98fff4)
NSTUB(eventproc_export_UIFS_PostModeDial, 0xff98fff8)
NSTUB(eventproc_export_UIFS_Capture, 0xff990020)
NSTUB(eventproc_export_UIFS_CaptureNoneStop, 0xff990024)
NSTUB(eventproc_export_UIFS_StartMovieRecord, 0xff990028)
NSTUB(eventproc_export_UIFS_StopMovieRecord, 0xff99002c)
NSTUB(eventproc_export_UIFS_StartClockMode, 0xff990030)
NSTUB(eventproc_export_UIFS_EndClockMode, 0xff990040)
NSTUB(eventproc_export_UIFS_SetCradleSetting, 0xff990050)
NSTUB(eventproc_export_UIFS_WriteFirmInfoToFile, 0xff990054)
NSTUB(eventproc_export_UIFS_GetMovieRecoadableNumber, 0xff990058)
NSTUB(eventproc_export_UIFS_GetStillShotableNumber, 0xff9900a0)
NSTUB(eventproc_export_UIFS_ChangeShootState, 0xff9900e8)

NSTUB(eventproc_export_UIFS_ShootSeqToUI, 0xff99010c)

NSTUB(eventproc_export_UIFS_GetLastPath, 0xff990130)
NSTUB(eventproc_export_UIFS_GetAvItemCount, 0xff990168)

NSTUB(eventproc_export_UIFS_GetAvItem, 0xff990218)
NSTUB(eventproc_export_UIFS_GetTvItem, 0xff990334)
NSTUB(eventproc_export_UIFS_GetCurrentAvString, 0xff990370)
NSTUB(eventproc_export_UIFS_GetCurrentTvString, 0xff9903f0)
NSTUB(eventproc_export_UIFS_IsAvailableShots, 0xff990474)
NSTUB(eventproc_export_UIFS_GetNumberOfDisplayedImage, 0xff990478)
NSTUB(eventproc_export_UIFS_PlayTrimExecuteAllImageSize, 0xff99047c)

NSTUB(eventproc_export_UI_ShowStateOfRecMode, 0xff990f00)

NSTUB(eventproc_export_EraseLogSector, 0xff9976dc)

NSTUB(eventproc_export_FmtMenu_ExecuteQuickFormat, 0xff9b2a3c)

NSTUB(eventproc_export_ExecuteResetFactoryWithRomWrite, 0xff9c2b6c)
NSTUB(eventproc_export_ExecuteResetFactory, 0xff9c2b84)
NSTUB(eventproc_export_ExecuteShutDownPropertyService, 0xff9c2b9c)

NSTUB(eventproc_export_memset, 0xffa4da70)

NSTUB(eventproc_export_sscanf, 0xffa4dbe0)

