#include "conf.h"

void change_video_tables(int a, int b){
}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

//** movie_record_task  @ 0xFF862C0C 

void __attribute__((naked,noinline)) movie_record_task(  ) { 
asm volatile (
"	STMFD	SP!, {R2-R8,LR} \n"                
"	LDR	R7, =0x2710 \n"                      
"	LDR	R4, =0x53E0 \n"                      
"	MOV	R6, #0 \n"                           
"	MOV	R5, #1 \n"                           
"loc_FF862C20:\n"
"	LDR	R0, [R4, #0x18] \n"                  
"	MOV	R2, #0 \n"                           
"	ADD	R1, SP, #4 \n"                       
"	BL	sub_FF827D30 \n"                      
"	LDR	R0, [R4, #0x20] \n"                  
"	CMP	R0, #0 \n"                           
"	BNE	loc_FF862CF0 \n"                     
"	LDR	R0, [SP, #4] \n"                     
"	LDR	R1, [R0] \n"                         
"	SUB	R1, R1, #2 \n"                       
"	CMP	R1, #9 \n"                           
"	ADDLS	PC, PC, R1, LSL #2 \n"             
"	B	loc_FF862CF0 \n"                       
"	B	loc_FF862CA4 \n"                       
"	B	loc_FF862CC4 \n"                       
"	B	loc_FF862CD4 \n"                       
"	B	loc_FF862CDC \n"                       
"	B	loc_FF862CAC \n"                       
"	B	loc_FF862CE4 \n"                       
"	B	loc_FF862CB4 \n"                       
"	B	loc_FF862CF0 \n"                       
"	B	loc_FF862CEC \n"                       
"	B	loc_FF862C7C \n"                       
"loc_FF862C7C:\n"
"	LDR	R0, =0xFF862924 \n"                  
"	STR	R6, [R4, #0x34] \n"                  
"	STR	R0, [R4, #0x9C] \n"                  
"	LDR	R0, =0xFF861FF4 \n"                  
"	LDR	R2, =0xFF861F10 \n"                  
"	LDR	R1, =0x1B800 \n"                     
"	STR	R6, [R4, #0x24] \n"                  
"	BL	sub_FF83C7A8 \n"                      
"	STR	R5, [R4, #0x38] \n"                  
"	B	loc_FF862CF0 \n"                       
"loc_FF862CA4:\n"
"	BL      unlock_optical_zoom\n" //+-----> inserted to unlock the zoom
"	BL	sub_FF862A1C \n"                      
"	B	loc_FF862CF0 \n"                       
"loc_FF862CAC:\n"
//"	BL	sub_FF8625C8 \n"
"	BL	sub_FF8625C8_my \n" // +-------------->              
"	B	loc_FF862CF0 \n"                       
"loc_FF862CB4:\n"
"	LDR	R1, [R0, #0x10] \n"                  
"	LDR	R0, [R0, #4] \n"                     
"	BL	sub_FF942C0C \n"                      
"	B	loc_FF862CF0 \n"                       
"loc_FF862CC4:\n"
"	LDR	R0, [R4, #0x38] \n"                  
"	CMP	R0, #5 \n"                           
"	STRNE	R5, [R4, #0x28] \n"                
"	B	loc_FF862CF0 \n"                       
"loc_FF862CD4:\n"
"	BL	sub_FF8622E8 \n"                      
"	B	loc_FF862CF0 \n"                       
"loc_FF862CDC:\n"
"	BL	sub_FF862040 \n"                      
"	B	loc_FF862CF0 \n"                       
"loc_FF862CE4:\n"
"	BL	sub_FF861E9C \n"                      
"	B	loc_FF862CF0 \n"                       
"loc_FF862CEC:\n"
"	BL	sub_FF862E5C \n"                      
"loc_FF862CF0:\n"
"	LDR	R1, [SP, #4] \n"                     
"	MOV	R3, #0x430 \n"                       
"	STR	R6, [R1] \n"                         
"	STR	R3, [SP] \n"                         
"	LDR	R0, [R4, #0x1C] \n"                  
"	LDR	R3, =0xFF861D00 \n"                  
"	MOV	R2, R7 \n"                           
"	BL	sub_FF828684 \n"                      
"	B	loc_FF862C20 \n"                       
	);
}


//** sub_FF8625C8_my  @ 0xFF8625C8 

void __attribute__((naked,noinline)) sub_FF8625C8_my(  ) { 
asm volatile (
"	STMFD	SP!, {R4-R9,LR} \n"                
"	SUB	SP, SP, #0x44 \n"                    
"	MOV	R7, #0 \n"                           
"	LDR	R6, =0x53E0 \n"                      
"	MOV	R4, R0 \n"                           
"	STR	R7, [SP, #0x34] \n"                  
"	STR	R7, [SP, #0x2C] \n"                  
"	LDR	R0, [R6, #0x38] \n"                  
"	MOV	R8, #4 \n"                           
"	CMP	R0, #3 \n"                           
"	STREQ	R8, [R6, #0x38] \n"                
"	LDR	R0, [R6, #0x9C] \n"                  
"	BLX	R0 \n"                               
"	LDR	R0, [R6, #0x38] \n"                  
"	CMP	R0, #4 \n"                           
"	BNE	loc_FF862718 \n"                     
"	ADD	R3, SP, #0x2C \n"                    
"	ADD	R2, SP, #0x30 \n"                    
"	ADD	R1, SP, #0x34 \n"                    
"	ADD	R0, SP, #0x38 \n"                    
"	BL	sub_FF942CA8 \n"                      
"	CMP	R0, #0 \n"                           
"	MOV	R5, #1 \n"                           
"	BNE	loc_FF862644 \n"                     
"	LDR	R1, [R6, #0x28] \n"                  
"	CMP	R1, #1 \n"                           
"	BNE	loc_FF86272C \n"                     
"	LDR	R1, [R6, #0x4C] \n"                  
"	LDR	R2, [R6, #0x3C] \n"                  
"	CMP	R1, R2 \n"                           
"	BCC	loc_FF86272C \n"                     
"loc_FF862644:\n"
"	CMP	R0, #0x80000001 \n"                  
"	STREQ	R8, [R6, #0x50] \n"                
"	BEQ	loc_FF86267C \n"                     
"	CMP	R0, #0x80000003 \n"                  
"	STREQ	R5, [R6, #0x50] \n"                
"	BEQ	loc_FF86267C \n"                     
"	CMP	R0, #0x80000005 \n"                  
"	MOVEQ	R0, #2 \n"                         
"	BEQ	loc_FF862678 \n"                     
"	CMP	R0, #0x80000007 \n"                  
"	STRNE	R7, [R6, #0x50] \n"                
"	BNE	loc_FF86267C \n"                     
"	MOV	R0, #3 \n"                           
"loc_FF862678:\n"
"	STR	R0, [R6, #0x50] \n"                  
"loc_FF86267C:\n"
"	LDR	R0, =0x1B834 \n"                     
"	LDR	R0, [R0, #8] \n"                     
"	CMP	R0, #0 \n"                           
"	BEQ	loc_FF862694 \n"                     
"	BL	sub_FF84CAA8 \n"                      
"	B	loc_FF862698 \n"                       
"loc_FF862694:\n"
"	BL	sub_FF861E9C \n"                      
"loc_FF862698:\n"
"	LDR	R0, [R4, #0x14] \n"                  
"	LDR	R1, [R4, #0x18] \n"                  
"	ADD	R3, SP, #0x3C \n"                    
"	MVN	R2, #1 \n"                           
"	ADD	R7, SP, #0x18 \n"                    
"	STMIA	R7, {R0-R3} \n"                    
"	LDR	R2, [R6, #0x64] \n"                  
"	LDR	R3, [R6, #0x68] \n"                  
"	MOV	R0, #0 \n"                           
"	ADD	R1, SP, #0x40 \n"                    
"	ADD	R7, SP, #8 \n"                       
"	STMIA	R7, {R0-R3} \n"                    
"	MOV	R3, #0 \n"                           
"	MOV	R2, #0x40 \n"                        
"	STRD	R2, [SP] \n"                        
"	LDMIB	R4, {R0,R1} \n"                    
"	LDR	R3, =0x1B84C \n"                     
"	MOV	R2, R9 \n"                           
"	BL	sub_FF8FE9D4 \n"                      
"	LDR	R0, [R6, #0x10] \n"                  
"	MOV	R1, #0x3E8 \n"                       
"	BL	sub_FF82814C \n"                      
"	CMP	R0, #9 \n"                           
"	BEQ	loc_FF8627B0 \n"                     
"	LDR	R0, [SP, #0x3C] \n"                  
"	CMP	R0, #0 \n"                           
"	BNE	loc_FF8627CC \n"                     
"	MOV	R0, #1 \n"                           
"	BL	sub_FF8FEA7C \n"                      
"	BL	sub_FF8FEAB8 \n"                      
"	MOV	R0, #5 \n"                           
"	STR	R0, [R6, #0x38] \n"                  
"loc_FF862718:\n"
"	ADD	SP, SP, #0x44 \n"                    
"	LDMFD	SP!, {R4-R9,PC} \n"                
"loc_FF862720:\n"
"	BL	sub_FF87F1C4 \n"                      
"	MOV	R0, #1 \n"                           
"	B	loc_FF86286C \n"                       
"loc_FF86272C:\n"
"	LDR	R12, [SP, #0x34] \n"                 
"	CMP	R12, #0 \n"                          
"	BEQ	loc_FF8628CC \n"                     
"	STR	R5, [R6, #0x2C] \n"                  
"	LDR	R0, [R6, #0x4C] \n"                  
"	LDR	R8, [R4, #0xC] \n"                   
"	CMP	R0, #0 \n"                           
"	LDRNE	LR, [SP, #0x38] \n"                
"	BNE	loc_FF8627F8 \n"                     
"	LDR	R0, [R4, #0x14] \n"                  
"	LDR	R1, [R4, #0x18] \n"                  
"	ADD	R3, SP, #0x3C \n"                    
"	MVN	R2, #0 \n"                           
"	ADD	R9, SP, #0x18 \n"                    
"	STMIA	R9, {R0-R3} \n"                    
"	LDR	R0, [SP, #0x2C] \n"                  
"	LDR	R2, [R6, #0x64] \n"                  
"	LDR	R3, [R6, #0x68] \n"                  
"	ADD	R1, SP, #0x40 \n"                    
"	ADD	R9, SP, #8 \n"                       
"	STMIA	R9, {R0-R3} \n"                    
"	LDR	R3, [SP, #0x30] \n"                  
"	STR	R12, [SP] \n"                        
"	STR	R3, [SP, #4] \n"                     
"	LDMIB	R4, {R0,R1} \n"                    
"	LDR	R3, [SP, #0x38] \n"                  
"	MOV	R2, R8 \n"                           
"	BL	sub_FF8FE9D4 \n"                      
"	LDR	R0, [R6, #0x10] \n"                  
"	MOV	R1, #0x3E8 \n"                       
"	BL	sub_FF82814C \n"                      
"	CMP	R0, #9 \n"                           
"	BNE	loc_FF8627C0 \n"                     
"loc_FF8627B0:\n"
"	BL	sub_FF943174 \n"                      
"	MOV	R0, #0x90000 \n"                     
"	STR	R5, [R6, #0x38] \n"                  
"	B	loc_FF862720 \n"                       
"loc_FF8627C0:\n"
"	LDR	R0, [SP, #0x3C] \n"                  
"	CMP	R0, #0 \n"                           
"	BEQ	loc_FF8627DC \n"                     
"loc_FF8627CC:\n"
"	BL	sub_FF943174 \n"                      
"	MOV	R0, #0xA0000 \n"                     
"	STR	R5, [R6, #0x38] \n"                  
"	B	loc_FF862720 \n"                       
"loc_FF8627DC:\n"
"	MOV	R0, #1 \n"                           
"	BL	sub_FF8FEA7C \n"                      
"	LDR	R0, [SP, #0x40] \n"                  
"	LDR	R1, [SP, #0x38] \n"                  
"	ADD	LR, R1, R0 \n"                       
"	LDR	R1, [SP, #0x34] \n"                  
"	SUB	R12, R1, R0 \n"                      
"loc_FF8627F8:\n"
"	LDR	R0, [R4, #0x14] \n"                  
"	LDR	R2, [R6, #0x48] \n"                  
"	LDR	R1, [R4, #0x18] \n"                  
"	ADD	R3, SP, #0x3C \n"                    
"	ADD	R9, SP, #0x18 \n"                    
"	STMIA	R9, {R0-R3} \n"                    
"	LDR	R0, [SP, #0x2C] \n"                  
"	LDR	R2, [R6, #0x64] \n"                  
"	LDR	R3, [R6, #0x68] \n"                  
"	ADD	R1, SP, #0x40 \n"                    
"	ADD	R9, SP, #8 \n"                       
"	STMIA	R9, {R0-R3} \n"                    
"	LDR	R3, [SP, #0x30] \n"                  
"	STR	R12, [SP] \n"                        
"	STR	R3, [SP, #4] \n"                     
"	LDMIB	R4, {R0,R1} \n"                    
"	MOV	R3, LR \n"                           
"	MOV	R2, R8 \n"                           
"	BL	sub_FF8FE9D4 \n"                      
"	LDR	R0, [R6, #0x10] \n"                  
"	MOV	R1, #0x3E8 \n"                       
"	BL	sub_FF82814C \n"                      
"	CMP	R0, #9 \n"                           
"	BNE	loc_FF862874 \n"                     
"	BL	sub_FF943174 \n"                      
"	MOV	R0, #0x90000 \n"                     
"	STR	R5, [R6, #0x38] \n"                  
"	BL	sub_FF87F1C4 \n"                      
"	MOV	R0, #0 \n"                           
"loc_FF86286C:\n"
"	BL	sub_FF8FEA7C \n"                      
"	B	loc_FF862718 \n"                       
"loc_FF862874:\n"
"	LDR	R0, [SP, #0x3C] \n"                  
"	CMP	R0, #0 \n"                           
"	BEQ	loc_FF862894 \n"                     
"	BL	sub_FF943174 \n"                      
"	MOV	R0, #0xA0000 \n"                     
"	STR	R5, [R6, #0x38] \n"                  
"	BL	sub_FF87F1C4 \n"                      
"	B	loc_FF862718 \n"                       
"loc_FF862894:\n"
"	MOV	R0, #0 \n"                           
"	BL	sub_FF8FEA7C \n"                      
"	LDR	R0, [SP, #0x38] \n"                  
"	LDR	R1, [SP, #0x40] \n"                  
"	BL	sub_FF942ED0 \n"                      
"	LDR	R0, [R6, #0x48] \n"                  
"	LDR	R3, =0x5448 \n"			// ---> -  	                    
"	ADD	R1, R0, #1 \n"			// ---> -              
"	STR	R1, [R6, #0x48] \n" 	// ---> -         
"	STR	R3, [SP] \n"			//       |                         
"	LDR	R0, [SP, #0x40] \n"		//       |                  
"	SUB	R3, R3, #4 \n"			// ---> -                       
"	MOV	R2, #0xF \n"			//       |                         
"	BL	sub_FF9411CC \n"		//       |                      
								//       |
"	LDR     R0, =0x5448-4\n"    // -<----     // +
"	BL      set_quality\n"                    // +	
"loc_FF8628CC:\n"
"	LDR	R0, [R6, #0x4C] \n"                  
"	ADD	R0, R0, #1 \n"                       
"	STR	R0, [R6, #0x4C] \n"                  
"	LDR	R1, [R6, #0x74] \n"                  
"	MUL	R0, R1, R0 \n"                       
"	LDR	R1, [R6, #0x70] \n"                  
"	BL	sub_FFB07534 \n"   	//*                   
"	MOV	R4, R0 \n"                           
"	BL	sub_FF9431AC \n"                      
"	LDR	R1, [R6, #0x6C] \n"                  
"	CMP	R1, R4 \n"                           
"	BNE	loc_FF862908 \n"                     
"	LDR	R0, [R6, #0x30] \n"                  
"	CMP	R0, #1 \n"                           
"	BNE	loc_FF86291C \n"                     
"loc_FF862908:\n"
"	LDR	R1, [R6, #0x80] \n"                  
"	MOV	R0, R4 \n"                           
"	BLX	R1 \n"                               
"	STR	R4, [R6, #0x6C] \n"                  
"	STR	R7, [R6, #0x30] \n"                  
"loc_FF86291C:\n"
"	STR	R7, [R6, #0x2C] \n"                                    
"	B	loc_FF862718 \n"  
	);
}

