#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)0x8450; // 0xFFD0F430

#include "../../../generic/capt_seq.c"

void __attribute__((naked,noinline)) sub_FFD0F3B8_my(){
 asm volatile(
                "STMFD   SP!, {R0-R10,LR}\n"
                "MOV     R6, #0\n"
                "MOV     R4, R0\n"
                "BL      sub_FFD0FEB8\n"
                "MVN     R1, #0\n"		// "MOVL     R1, 0xFFFFFFFF"
                "BL      sub_FFC173FC\n"
                "MOV     R2, #4\n"
                "ADD     R1, SP, #8\n"
                "MOV     R0, #0x8A\n"
                "BL      sub_FFC5819C\n"
                "TST     R0, #1\n"
                "MOVNE   R1, #0x218\n"
                "LDRNE   R0, =0xFFD0F5CC\n"
                "BLNE    sub_FFC0BDB8\n"
                "LDR     R8, =0x18440\n"
                "LDR     R5, =0x18394\n"
                "LDRSH   R1, [R8,#0xE]\n"
                "LDR     R0, [R5,#0x74]\n"
                "BL      sub_FFCCD36C\n"
                "BL      sub_FFC339C8\n"
                "LDR     R2, =0x8454\n"
                "ADD     R3, R4, #0x8C\n"
                "STRH    R0, [R4,#0x88]\n"
                "STR     R2, [SP]\n"		// Corrected! from STRD    R2, [SP]
                "STR     R3, [SP,#4]\n"		// Added! (als in a720)
                "MOV     R1, R0\n"
                "LDRH    R0, [R5,#0x4C]\n"
                "LDRSH   R2, [R8,#0xC]\n"
                "LDR     R3, =0x8450\n"
                "BL	 sub_FFD103A4\n"
                "BL      wait_until_remote_button_is_released\n"
                "BL      capt_seq_hook_set_nr\n"
                "B       sub_FFD0F42C\n"
 );
}


void __attribute__((naked,noinline)) task_CaptSeqTask_my() //#fs
{
	asm volatile (
                "STMFD   SP!, {R3-R7,LR}\n"
                "LDR     R6, =0x52A8\n"

"loc_FFC49B40:\n"
                "LDR     R0, [R6,#8]\n"
                "MOV     R2, #0\n"
                "MOV     R1, SP\n"
                "BL      sub_FFC1764C\n"
                "TST     R0, #1\n"
                "BEQ     loc_FFC49B6C\n"
                "LDR     R1, =0x48E\n"
                "LDR     R0, =0xFFC49860\n"		// aSsshoottask_c
                "BL      sub_FFC0BDB8\n"		// DebugAssert
                "BL      sub_FFC0BB70\n"		// ExitTask
                "LDMFD   SP!, {R3-R7,PC}\n"

"loc_FFC49B6C:\n"
                "LDR     R0, [SP]\n"
                "LDR     R1, [R0]\n"

                //"LDR     R2, =0x1850\n"         // What? DEBUG: Save jumptable-target ...
                //"STR     R1, [R2]\n"            // What? ...to some unused space. Read and displayed in GUI in core/gui.c

                "CMP     R1, #0x19\n"
                "ADDLS   PC, PC, R1,LSL#2\n"
                "B       loc_FFC49D80\n"

                "B       loc_FFC49BE8\n"
                "B       loc_FFC49BF0\n"
                "B       loc_FFC49C70\n"
                "B       loc_FFC49C84\n"
                "B       loc_FFC49C7C\n"
                "B       loc_FFC49C8C\n"
                "B       loc_FFC49C94\n"
                "B       loc_FFC49CA0\n"
                "B       loc_FFC49CF8\n"
                "B       loc_FFC49C84\n"
                "B       loc_FFC49D00\n"
                "B       loc_FFC49D08\n"
                "B       loc_FFC49D10\n"
                "B       loc_FFC49D18\n"
                "B       loc_FFC49D20\n"
                "B       loc_FFC49D2C\n"
                "B       loc_FFC49D34\n"
                "B       loc_FFC49D3C\n"
                "B       loc_FFC49D44\n"
                "B       loc_FFC49D50\n"
                "B       loc_FFC49D58\n"
                "B       loc_FFC49D60\n"
                "B       loc_FFC49D68\n"
                "B       loc_FFC49D70\n"
                "B       loc_FFC49D78\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49BE8:\n"
                "BL      sub_FFD0DF20\n"
                "BL      shooting_expo_param_override\n"
                "B       loc_FFC49C98\n"
"loc_FFC49BF0:\n"
                "LDR     R4, [R0,#0xC]\n"
                "LDR     R0, [R4,#8]\n"
                "ORR     R0, R0, #1\n"
                "STR     R0, [R4,#8]\n"
                "BL      sub_FFD0DF10\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0E2F8\n"
                "TST     R0, #1\n"
                "MOVNE   R2, R4\n"
                "MOVNE   R1, #1\n"
                "BNE     loc_FFC49CF0\n"
                "BL      sub_FFD2D318\n"
                "BL      sub_FFC5832C\n"
                "STR     R0, [R4,#0x14]\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0F2F0\n"
                "BL      sub_FFD0FD54\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0F3B8_my\n"		//-------------->
                "BL      capt_seq_hook_raw_here\n"		//-------------->
                "MOV     R5, R0\n"
                "BL      sub_FFD10D34\n"
                "BL      sub_FFD10D70\n"
                "MOV     R2, R4\n"
                "MOV     R1, #1\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC4831C\n"
                "BL      sub_FFD0F768\n"
                "CMP     R0, #0\n"
                "LDRNE   R0, [R4,#8]\n"
                "ORRNE   R0, R0, #0x2000\n"
                "STRNE   R0, [R4,#8]\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49C70:\n"
                "MOV     R0, #1\n"
                "BL      sub_FFD0E0B4\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49C7C:\n"
                "BL      sub_FFD0DB80\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49C84:\n"
                "BL      sub_FFD0DF00\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49C8C:\n"
                "BL      sub_FFD0DF08\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49C94:\n"
                "BL      sub_FFD0DFD4\n"
"loc_FFC49C98:\n"
                "BL      sub_FFC47F9C\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49CA0:\n"
                "LDR     R4, [R0,#0xC]\n"
                "BL      sub_FFD0DF10\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0E678\n"
                "TST     R0, #1\n"
                "MOV     R5, R0\n"
                "BNE     loc_FFC49CE0\n"
                "BL      sub_FFC5832C\n"
                "STR     R0, [R4,#0x14]\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0F2F0\n"
                "MOV     R0, R4\n"
                "BL      sub_FFD0F7C8\n"
                "MOV     R5, R0\n"
                "LDR     R0, [R4,#0x14]\n"
                "BL      sub_FFC58538\n"
"loc_FFC49CE0:\n"
                "BL      sub_FFD0DF00\n"
                "MOV     R2, R4\n"
                "MOV     R1, #9\n"
                "MOV     R0, R5\n"
"loc_FFC49CF0:\n"
                "BL      sub_FFC4831C\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49CF8:\n"
                "BL      sub_FFD0E034\n"
                "B       loc_FFC49C98\n"
"loc_FFC49D00:\n"
                "BL      sub_FFD0E8F4\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D08:\n"
                "BL      sub_FFD0EADC\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D10:\n"
                "BL      sub_FFD0EB6C\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D18:\n"
                "BL      sub_FFD0EC20\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D20:\n"
                "MOV     R0, #0\n"
                "BL      sub_FFD0EDC4\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D2C:\n"
                "BL      sub_FFD0EF14\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D34:\n"
                "BL      sub_FFD0EFA8\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D3C:\n"
                "BL      sub_FFD0F070\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D44:\n"
                "BL      sub_FFD0E1D0\n"
                "BL      sub_FFC149BC\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D50:\n"
                "BL      sub_FFD0ECDC\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D58:\n"
                "BL      sub_FFD0ED20\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D60:\n"
                "BL      sub_FFD10D18\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D68:\n"
                "BL      sub_FFD10D34\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D70:\n"
                "BL      sub_FFD10D44\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D78:\n"
                "BL      sub_FFD10D70\n"
                "B       loc_FFC49D8C\n"
"loc_FFC49D80:\n"
                "LDR     R1, =0x58E\n"
                "LDR     R0, =0xFFC49860\n"
                "BL      sub_FFC0BDB8\n"		// DebugAssert
"loc_FFC49D8C:\n"
                "LDR     R0, [SP]\n"
                "LDR     R1, [R0,#4]\n"
                "LDR     R0, [R6,#4]\n"
                "BL      sub_FFC173C8\n"
                "LDR     R4, [SP]\n"
                "LDR     R0, [R4,#8]\n"
                "CMP     R0, #0\n"
                "LDREQ   R1, =0x10D\n"
                "LDREQ   R0, =0xFFC49860\n"
                "BLEQ    sub_FFC0BDB8\n"		// DebugAssert
                "MOV     R0, #0\n"
                "STR     R0, [R4,#8]\n"
                "B       loc_FFC49B40\n"
    );
} //#fe

void __attribute__((naked,noinline)) exp_drv_task(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "SUB     SP, SP, #0x20\n"
                "LDR     R8, =0xBB8\n"
                "LDR     R7, =0x649C\n"
                "LDR     R5, =0x3C0F0\n"
                "MOV     R0, #0\n"
                "ADD     R6, SP, #0x10\n"
                "STR     R0, [SP,#0xC]\n"
"loc_FFC911B4:\n"
                "LDR     R0, [R7,#0x20]\n"
                "MOV     R2, #0\n"
                "ADD     R1, SP, #0x1C\n"
                "BL      sub_FFC1764C\n"
                "LDR     R0, [SP,#0xC]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC911FC\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R0, [R0]\n"
                "CMP     R0, #0x13\n"
                "CMPNE   R0, #0x14\n"
                "CMPNE   R0, #0x15\n"
                "BEQ     loc_FFC91318\n"
                "CMP     R0, #0x27\n"
                "BEQ     loc_FFC912F0\n"
                "ADD     R1, SP, #0xC\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC91144\n"
"loc_FFC911FC:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R1, [R0]\n"
                "CMP     R1, #0x2C\n"
                "BNE     loc_FFC9122C\n"
                "LDR     R0, [SP,#0x1C]\n"
                "BL      sub_FFC923F8\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R1, #1\n"
                "BL      sub_FFC173C8\n"
                "BL      sub_FFC0BB70\n"		// ExitTask
                "ADD     SP, SP, #0x20\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC9122C:\n"
                "CMP     R1, #0x2B\n"
                "BNE     loc_FFC91248\n"
                "LDR     R2, [R0,#0x88]!\n"
                "LDR     R1, [R0,#4]\n"
                "MOV     R0, R1\n"
                "BLX     R2\n"
                "B       loc_FFC9177C\n"
"loc_FFC91248:\n"
                "CMP     R1, #0x25\n"
                "BNE     loc_FFC91298\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R1, #0x80\n"
                "BL      sub_FFC173FC\n"
                "LDR     R0, =0xFFC8DC38\n"
                "MOV     R1, #0x80\n"
                "BL      sub_FFD05880\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R2, R8\n"
                "MOV     R1, #0x80\n"
                "BL      sub_FFC17300\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0xD1B\n"
                "BNE     loc_FFC912DC\n"
"loc_FFC91284:\n"
                "LDR     R1, [SP,#0x1C]\n"
                "LDR     R0, [R1,#0x8C]\n"
                "LDR     R1, [R1,#0x88]\n"
                "BLX     R1\n"
                "B       loc_FFC9177C\n"
"loc_FFC91298:\n"
                "CMP     R1, #0x26\n"
                "BNE     loc_FFC912E8\n"
                "ADD     R1, SP, #0xC\n"
                "BL      sub_FFC91144\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R1, #0x100\n"
                "BL      sub_FFC173FC\n"
                "LDR     R0, =0xFFC8DC48\n"
                "MOV     R1, #0x100\n"
                "BL      sub_FFD05B08\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R2, R8\n"
                "MOV     R1, #0x100\n"
                "BL      sub_FFC17300\n"
                "TST     R0, #1\n"
                "BEQ     loc_FFC91284\n"
                "LDR     R1, =0xD25\n"
"loc_FFC912DC:\n"
                "LDR     R0, =0xFFC8E338\n"		// aExpdrv_c
                "BL      sub_FFC0BDB8\n"		// DebugAssert
                "B       loc_FFC91284\n"
"loc_FFC912E8:\n"
                "CMP     R1, #0x27\n"
                "BNE     loc_FFC91300\n"
"loc_FFC912F0:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "ADD     R1, SP, #0xC\n"
                "BL      sub_FFC91144\n"
                "B       loc_FFC91284\n"
"loc_FFC91300:\n"
                "CMP     R1, #0x2A\n"
                "BNE     loc_FFC91318\n"
                "BL      sub_FFC70F80\n"
                "BL      sub_FFC71D4C\n"
                "BL      sub_FFC717D0\n"
                "B       loc_FFC91284\n"
"loc_FFC91318:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "MOV     R4, #1\n"
                "LDR     R1, [R0]\n"
                "CMP     R1, #0x11\n"
                "CMPNE   R1, #0x12\n"
                "BNE     loc_FFC91388\n"
                "LDR     R1, [R0,#0x7C]\n"
                "ADD     R1, R1, R1,LSL#1\n"
                "ADD     R1, R0, R1,LSL#2\n"
                "SUB     R1, R1, #8\n"
                "LDMIA   R1, {R2-R4}\n"
                "STMIA   R6, {R2-R4}\n"
                "BL      sub_FFC8FCC4\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R3, [R0,#0x88]\n"
                "LDR     R2, [R0,#0x8C]\n"
                "ADD     R0, R0, #4\n"
                "BLX     R3\n"
                "LDR     R0, [SP,#0x1C]\n"
                "BL      sub_FFC927D0\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R3, [R0,#0x90]\n"
                "LDR     R2, [R0,#0x94]\n"
                "ADD     R0, R0, #4\n"
                "BLX     R3\n"
                "B       loc_FFC916BC\n"
"loc_FFC91388:\n"
                "CMP     R1, #0x13\n"
                "CMPNE   R1, #0x14\n"
                "CMPNE   R1, #0x15\n"
                "BNE     loc_FFC9143C\n"
                "ADD     R3, SP, #0xC\n"
                "MOV     R2, SP\n"
                "ADD     R1, SP, #0x10\n"
                "BL      sub_FFC8FF0C\n"
                "CMP     R0, #1\n"
                "MOV     R4, R0\n"
                "CMPNE   R4, #5\n"
                "BNE     loc_FFC913D8\n"
                "LDR     R0, [SP,#0x1C]\n"
                "MOV     R2, R4\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R12, [R0,#0xC]\n"
                "LDR     R3, [R0,#4]\n"
                "MOV     R0, SP\n"
                "BLX     R12\n"
                "B       loc_FFC91410\n"
"loc_FFC913D8:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "CMP     R4, #2\n"
                "LDR     R3, [R0,#0x8C]\n"
                "CMPNE   R4, #6\n"
                "BNE     loc_FFC91424\n"
                "LDR     R12, [R0,#0x88]\n"
                "MOV     R0, SP\n"
                "MOV     R2, R4\n"
                "MOV     R1, #1\n"
                "BLX     R12\n"
                "LDR     R0, [SP,#0x1C]\n"
                "MOV     R2, SP\n"
                "ADD     R1, SP, #0x10\n"
                "BL      sub_FFC90E90\n"
"loc_FFC91410:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R2, [SP,#0xC]\n"
                "MOV     R1, R4\n"
                "BL      sub_FFC910E4\n"
                "B       loc_FFC916BC\n"
"loc_FFC91424:\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R12, [R0,#0x88]\n"
                "ADD     R0, R0, #4\n"
                "MOV     R2, R4\n"
                "BLX     R12\n"
                "B       loc_FFC916BC\n"
"loc_FFC9143C:\n"
                "CMP     R1, #0x21\n"
                "CMPNE   R1, #0x22\n"
                "BNE     loc_FFC91488\n"
                "LDR     R1, [R0,#0x7C]\n"
                "ADD     R1, R1, R1,LSL#1\n"
                "ADD     R1, R0, R1,LSL#2\n"
                "SUB     R1, R1, #8\n"
                "LDMIA   R1, {R2-R4}\n"
                "STMIA   R6, {R2-R4}\n"
                "BL      sub_FFC8F250\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R3, [R0,#0x88]\n"
                "LDR     R2, [R0,#0x8C]\n"
                "ADD     R0, R0, #4\n"
                "BLX     R3\n"
                "LDR     R0, [SP,#0x1C]\n"
                "BL      sub_FFC8F540\n"
                "B       loc_FFC916BC\n"
"loc_FFC91488:\n"
                "ADD     R1, R0, #4\n"
                "LDMIA   R1, {R2,R3,R12}\n"
                "STMIA   R6, {R2,R3,R12}\n"
                "LDR     R1, [R0]\n"
                "CMP     R1, #0x24\n"
                "ADDLS   PC, PC, R1,LSL#2\n"
                "B       loc_FFC9169C\n"
"loc_FFC914A4:\n"
                "B       loc_FFC91538\n"
"loc_FFC914A8:\n"
                "B       loc_FFC91538\n"
"loc_FFC914AC:\n"
                "B       loc_FFC91540\n"
"loc_FFC914B0:\n"
                "B       loc_FFC91548\n"
"loc_FFC914B4:\n"
                "B       loc_FFC91548\n"
"loc_FFC914B8:\n"
                "B       loc_FFC91548\n"
"loc_FFC914BC:\n"
                "B       loc_FFC91538\n"
"loc_FFC914C0:\n"
                "B       loc_FFC91540\n"
"loc_FFC914C4:\n"
                "B       loc_FFC91548\n"
"loc_FFC914C8:\n"
                "B       loc_FFC91548\n"
"loc_FFC914CC:\n"
                "B       loc_FFC915A4\n"
"loc_FFC914D0:\n"
                "B       loc_FFC915A4\n"
"loc_FFC914D4:\n"
                "B       loc_FFC91690\n"
"loc_FFC914D8:\n"
                "B       loc_FFC91698\n"
"loc_FFC914DC:\n"
                "B       loc_FFC91698\n"
"loc_FFC914E0:\n"
                "B       loc_FFC91698\n"
"loc_FFC914E4:\n"
                "B       loc_FFC91698\n"
"loc_FFC914E8:\n"
                "B       loc_FFC9169C\n"
"loc_FFC914EC:\n"
                "B       loc_FFC9169C\n"
"loc_FFC914F0:\n"
                "B       loc_FFC9169C\n"
"loc_FFC914F4:\n"
                "B       loc_FFC9169C\n"
"loc_FFC914F8:\n"
                "B       loc_FFC9169C\n"
"loc_FFC914FC:\n"
                "B       loc_FFC91550\n"
"loc_FFC91500:\n"
                "B       loc_FFC91558\n"
"loc_FFC91504:\n"
                "B       loc_FFC91558\n"
"loc_FFC91508:\n"
                "B       loc_FFC915B0\n"
"loc_FFC9150C:\n"
                "B       loc_FFC915B0\n"
"loc_FFC91510:\n"
                "B       loc_FFC915B8\n"
"loc_FFC91514:\n"
                "B       loc_FFC915E8\n"
"loc_FFC91518:\n"
                "B       loc_FFC91618\n"
"loc_FFC9151C:\n"
                "B       loc_FFC91648\n"
"loc_FFC91520:\n"
                "B       loc_FFC91678\n"
"loc_FFC91524:\n"
                "B       loc_FFC91678\n"
"loc_FFC91528:\n"
                "B       loc_FFC9169C\n"
"loc_FFC9152C:\n"
                "B       loc_FFC9169C\n"
"loc_FFC91530:\n"
                "B       loc_FFC91680\n"
"loc_FFC91534:\n"
                "B       loc_FFC91688\n"
"loc_FFC91538:\n"
                "BL      sub_FFC8E120\n"
                "B       loc_FFC9169C\n"
"loc_FFC91540:\n"
                "BL      sub_FFC8E3B0\n"
                "B       loc_FFC9169C\n"
"loc_FFC91548:\n"
                "BL      sub_FFC8E5B4\n"
                "B       loc_FFC9169C\n"
"loc_FFC91550:\n"
                "BL      sub_FFC8E81C\n"
                "B       loc_FFC9169C\n"
"loc_FFC91558:\n"
                "BL      sub_FFC8EA10\n"
                "B       loc_FFC9169C\n"
//"dword_FFC91560  DCD 0xB1D \n"
//"dword_FFC91564  DCD 0xBAD \n"
//"dword_FFC91568  DCD 0xC24 \n"
//"dword_FFC9156C  DCD 0xC32 \n"
//"dword_FFC91570  DCD 0xC7B \n"
//"dword_FFC91574  DCD 0x808 \n"
//"dword_FFC91578  DCD 0xC8E \n"
//"dword_FFC9157C  DCD 0xC94 \n"
//"dword_FFC91580  DCD 0xCE8 \n"
//"dword_FFC91584  DCD 0xD0E \n"
//"dword_FFC91588  DCD 0xD11 \n"
//"off_FFC9158C    DCD 0xFFC8DC58 \n"
//"dword_FFC91590  DCD 0xD42 \n"
//"dword_FFC91594  DCD 0x3C0F0 \n"
//"dword_FFC91598  DCD 0xD1B \n"
//"off_FFC9159C    DCD 0xFFC8DC48 \n"
//"dword_FFC915A0  DCD 0xD25 \n"
"loc_FFC915A4:\n"
                "BL      sub_FFC8EC78_my\n"		//------------>
                "MOV     R4, #0\n"
                "B       loc_FFC9169C\n"
"loc_FFC915B0:\n"
                "BL      sub_FFC8EDB4\n"
                "B       loc_FFC9169C\n"
"loc_FFC915B8:\n"
                "LDRH    R1, [R0,#4]\n"
                "STRH    R1, [SP,#0x10]\n"
                "LDRH    R1, [R5,#2]\n"
                "STRH    R1, [SP,#0x12]\n"
                "LDRH    R1, [R5,#4]\n"
                "STRH    R1, [SP,#0x14]\n"
                "LDRH    R1, [R5,#6]\n"
                "STRH    R1, [SP,#0x16]\n"
                "LDRH    R1, [R0,#0xC]\n"
                "STRH    R1, [SP,#0x18]\n"
                "BL      sub_FFC9246C\n"
                "B       loc_FFC9169C\n"
"loc_FFC915E8:\n"
                "LDRH    R1, [R0,#4]\n"
                "STRH    R1, [SP,#0x10]\n"
                "LDRH    R1, [R5,#2]\n"
                "STRH    R1, [SP,#0x12]\n"
                "LDRH    R1, [R5,#4]\n"
                "STRH    R1, [SP,#0x14]\n"
                "LDRH    R1, [R5,#6]\n"
                "STRH    R1, [SP,#0x16]\n"
                "LDRH    R1, [R5,#8]\n"
                "STRH    R1, [SP,#0x18]\n"
                "BL      sub_FFC925EC\n"
                "B       loc_FFC9169C\n"
"loc_FFC91618:\n"
                "LDRH    R1, [R5]\n"
                "STRH    R1, [SP,#0x10]\n"
                "LDRH    R1, [R0,#6]\n"
                "STRH    R1, [SP,#0x12]\n"
                "LDRH    R1, [R5,#4]\n"
                "STRH    R1, [SP,#0x14]\n"
                "LDRH    R1, [R5,#6]\n"
                "STRH    R1, [SP,#0x16]\n"
                "LDRH    R1, [R5,#8]\n"
                "STRH    R1, [SP,#0x18]\n"
                "BL      sub_FFC92698\n"
                "B       loc_FFC9169C\n"
"loc_FFC91648:\n"
                "LDRH    R1, [R5]\n"
                "STRH    R1, [SP,#0x10]\n"
                "LDRH    R1, [R5,#2]\n"
                "STRH    R1, [SP,#0x12]\n"
                "LDRH    R1, [R5,#4]\n"
                "STRH    R1, [SP,#0x14]\n"
                "LDRH    R1, [R5,#6]\n"
                "STRH    R1, [SP,#0x16]\n"
                "LDRH    R1, [R0,#0xC]\n"
                "STRH    R1, [SP,#0x18]\n"
                "BL      sub_FFC92738\n"
                "B       loc_FFC9169C\n"
"loc_FFC91678:\n"
                "BL      sub_FFC8F028\n"
                "B       loc_FFC9169C\n"
"loc_FFC91680:\n"
                "BL      sub_FFC8F644\n"
                "B       loc_FFC9169C\n"
"loc_FFC91688:\n"
                "BL      sub_FFC8F87C\n"
                "B       loc_FFC9169C\n"
"loc_FFC91690:\n"
                "BL      sub_FFC8F9F4\n"
                "B       loc_FFC9169C\n"
"loc_FFC91698:\n"
                "BL      sub_FFC8FB8C\n"
"loc_FFC9169C:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R1, [R0,#0x7C]\n"
                "LDR     R3, [R0,#0x88]\n"
                "LDR     R2, [R0,#0x8C]\n"
                "ADD     R0, R0, #4\n"
                "BLX     R3\n"
                "CMP     R4, #1\n"
                "BNE     loc_FFC91704\n"
"loc_FFC916BC:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "MOV     R2, #0xC\n"
                "LDR     R1, [R0,#0x7C]\n"
                "ADD     R1, R1, R1,LSL#1\n"
                "ADD     R0, R0, R1,LSL#2\n"
                "SUB     R4, R0, #8\n"
                "LDR     R0, =0x3C0F0\n"
                "ADD     R1, SP, #0x10\n"
                "BL      sub_FFE58B0C\n"
                "LDR     R0, =0x3C0FC\n"
                "MOV     R2, #0xC\n"
                "ADD     R1, SP, #0x10\n"
                "BL      sub_FFE58B0C\n"
                "LDR     R0, =0x3C108\n"
                "MOV     R2, #0xC\n"
                "MOV     R1, R4\n"
                "BL      sub_FFE58B0C\n"
                "B       loc_FFC9177C\n"
"loc_FFC91704:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "LDR     R0, [R0]\n"
                "CMP     R0, #0xB\n"
                "BNE     loc_FFC9174C\n"
                "MOV     R3, #0\n"
                "STR     R3, [SP]\n"
                "MOV     R3, #1\n"
                "MOV     R2, #1\n"
                "MOV     R1, #1\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC8DF28\n"
                "MOV     R3, #0\n"
                "STR     R3, [SP]\n"
                "MOV     R3, #1\n"
                "MOV     R2, #1\n"
                "MOV     R1, #1\n"
                "MOV     R0, #0\n"
                "B       loc_FFC91778\n"
"loc_FFC9174C:\n"
                "MOV     R3, #1\n"
                "MOV     R2, #1\n"
                "MOV     R1, #1\n"
                "MOV     R0, #1\n"
                "STR     R3, [SP]\n"
                "BL      sub_FFC8DF28\n"
                "MOV     R3, #1\n"
                "MOV     R2, #1\n"
                "MOV     R1, #1\n"
                "MOV     R0, #1\n"
                "STR     R3, [SP]\n"
"loc_FFC91778:\n"
                "BL      sub_FFC8E068\n"
"loc_FFC9177C:\n"
                "LDR     R0, [SP,#0x1C]\n"
                "BL      sub_FFC923F8\n"
                "B       loc_FFC911B4\n"
    );
}

void __attribute__((naked,noinline)) sub_FFC8EC78_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "LDR     R7, =0x649C\n"
                "MOV     R4, R0\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R1, #0x3E\n"
                "BL      sub_FFC173FC\n"
                "LDRSH   R0, [R4,#4]\n"
                "MOV     R2, #0\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC8DCBC\n"
                "MOV     R6, R0\n"
                "LDRSH   R0, [R4,#6]\n"
                "BL      sub_FFC8DDC8\n"
                "LDRSH   R0, [R4,#8]\n"
                "BL      sub_FFC8DE20\n"
                "LDRSH   R0, [R4,#0xA]\n"
                "BL      sub_FFC8DE78\n"
                "LDRSH   R0, [R4,#0xC]\n"
                "BL      sub_FFC8DED0\n"
                "MOV     R5, R0\n"
                "LDR     R0, [R4]\n"
                "LDR     R8, =0x3C108\n"
                "CMP     R0, #0xB\n"
                "MOVEQ   R6, #0\n"
                "MOVEQ   R5, #0\n"
                "BEQ     loc_FFC8ED08\n"
                "CMP     R6, #1\n"
                "BNE     loc_FFC8ED08\n"
                "LDRSH   R0, [R4,#4]\n"
                "LDR     R1, =0xFFC8DC28\n"
                "MOV     R2, #2\n"
                "BL      sub_FFD059D4\n"
                "STRH    R0, [R4,#4]\n"
                "MOV     R0, #0\n"
                "STR     R0, [R7,#0x28]\n"
                "B       loc_FFC8ED10\n"
"loc_FFC8ED08:\n"
                "LDRH    R0, [R8]\n"
                "STRH    R0, [R4,#4]\n"
"loc_FFC8ED10:\n"
                "CMP     R5, #1\n"
                "LDRNEH  R0, [R8,#8]\n"
                "BNE     loc_FFC8ED2C\n"
                "LDRSH   R0, [R4,#0xC]\n"
                "MOV     R2, #0x20\n"
                "LDR     R1, =0xFFC8DCAC\n"		// "ADR     R1, 0xFFC8DCAC\n"
                "BL      sub_FFC92428\n"
"loc_FFC8ED2C:\n"
                "STRH    R0, [R4,#0xC]\n"
                "LDRSH   R0, [R4,#6]\n"
                "BL      sub_FFC70CCC_my\n"		//-------------->
                "LDRSH   R0, [R4,#8]\n"
                "MOV     R1, #1\n"
                "BL      sub_FFC714C8\n"
                "MOV     R1, #0\n"
                "ADD     R0, R4, #8\n"
                "BL      sub_FFC71550\n"
                "LDRSH   R0, [R4,#0xE]\n"
                "BL      sub_FFC84BF8\n"
                "LDR     R4, =0xBB8\n"
                "CMP     R6, #1\n"
                "BNE     loc_FFC8ED84\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R2, R4\n"
                "MOV     R1, #2\n"
                "BL      sub_FFC17300\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x532\n"
                "LDRNE   R0, =0xFFC8E338\n"		// aExpdrv_c
                "BLNE    sub_FFC0BDB8\n"		// DebugAssert
"loc_FFC8ED84:\n"
                "CMP     R5, #1\n"
                "LDMNEFD SP!, {R4-R8,PC}\n"
                "LDR     R0, [R7,#0x1C]\n"
                "MOV     R2, R4\n"
                "MOV     R1, #0x20\n"
                "BL      sub_FFC17300\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x537\n"
                "LDRNE   R0, =0xFFC8E338\n"		// aExpdrv_c
                "LDMNEFD SP!, {R4-R8,LR}\n"
                "BNE     sub_FFC0BDB8\n"		// DebugAssert
                "LDMFD   SP!, {R4-R8,PC}\n"
    );
}

void __attribute__((naked,noinline)) sub_FFC70CCC_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "LDR     R5, =0x5F74\n"
                "MOV     R4, R0\n"
                "LDR     R0, [R5,#4]\n"
                "CMP     R0, #1\n"
                "LDRNE   R1, =0x16D\n"
                "LDRNE   R0, =0xFFC70A64\n"		// aShutter_c, "ADRNE   R0, 0xFFC70A64\n"
                "BLNE    sub_FFC0BDB8\n"		// DebugAssert
                "CMN     R4, #0xC00\n"
                "LDREQSH R4, [R5,#2]\n"
                "CMN     R4, #0xC00\n"
                "LDREQ   R1, =0x173\n"
                "LDREQ   R0, =0xFFC70A64\n"		// aShutter_c, "ADREQ   R0, 0xFFC70A64\n"
                "STRH    R4, [R5,#2]\n"
                "BLEQ    sub_FFC0BDB8\n"		// DebugAssert
                "MOV     R0, R4\n"
//                "BL	 sub_FFD71FBC\n"		//-
                "BL      apex2us\n"		//+
                "MOV     R4, R0\n"
//                "BL	 nullsub_67\n"
                "MOV     R0, R4\n"
                "BL	 sub_FFCA4090\n"
                "TST     R0, #1\n"
                "LDMNEFD SP!, {R4-R6,LR}\n"
                "MOVNE   R1, #0x178\n"
                "LDRNE   R0, =0xFFC70A64\n"		// aShutter_c, "ADRNE   R0, 0xFFC70A64\n"
                "BNE     sub_FFC0BDB8\n"		// DebugAssert
                "LDMFD   SP!, {R4-R6,PC}\n"
    );
}
