/*
void __attribute__((naked,noinline)) sub_FFC5EA24_my() {
asm volatile(
                "LDR     R12, =0x201E\n"
                "STMFD   SP!, {R4,LR}\n"
                "CMP     R0, R12\n"
                "BEQ     loc_FFC5EAE4\n"
                "BGT     loc_FFC5EA80\n"
                "LDR     R12, =0x2004\n"
                "CMP     R0, R12\n"
                "BEQ     loc_FFC5EAEC\n"
                "BGT     loc_FFC5EA68\n"
                "SUB     R12, R0, #0x1000\n"
                "SUBS    R12, R12, #0xA9\n"
                "SUBNE   R12, R0, #0x1000\n"
                "SUBNES  R12, R12, #0xAD\n"
                "SUBNE   R12, R0, #0x1000\n"
                "SUBNES  R12, R12, #0xAF\n"
                "BNE     loc_FFC5EAFC\n"
                "B       loc_FFC5EAE4\n"
"loc_FFC5EA68:\n"
                "SUB     R12, R0, #0x2000\n"
                "SUBS    R12, R12, #5\n"
                "SUBNE   R12, R0, #0x2000\n"
                "SUBNES  R12, R12, #0x1D\n"
                "BNE     loc_FFC5EAFC\n"
                "B       loc_FFC5EAE4\n"
"loc_FFC5EA80:\n"
                "LDR     R12, =0x5004\n"
                "CMP     R0, R12\n"
                "BEQ     loc_FFC5EAE4\n"
                "BGT     loc_FFC5EAAC\n"
                "SUB     R12, R0, #0x3000\n"
                "SUBS    R12, R12, #0xA\n"
                "BEQ     loc_FFC5EAE0\n"
                "SUB     R12, R0, #0x5000\n"
                "SUBS    R12, R12, #1\n"
                "BNE     loc_FFC5EAFC\n"
                "B       loc_FFC5EAE4\n"
"loc_FFC5EAAC:\n"
                "SUB     R12, R0, #0x5000\n"
                "SUBS    R12, R12, #6\n"
                "BEQ     loc_FFC5EAE4\n"
                "SUB     R12, R0, #0x5000\n"
                "SUBS    R12, R12, #7\n"
                "BNE     loc_FFC5EAFC\n"
                "BL      sub_FFC1A5E8\n"
                "LDR     R1, =0x5738\n"
                "LDR     R0, [R1,#0x10]\n"
                "CMP     R0, #7\n"
                "LDREQ   R0, [R1,#0x18]\n"
                "BLEQ    sub_FFC5F394\n"
                "B       loc_FFC5EAF4\n"
"loc_FFC5EAE0:\n"
                "BL      sub_FFC19B98\n"
"loc_FFC5EAE4:\n"
                "LDMFD   SP!, {R4,LR}\n"
                //B	     sub_FFC5E884
                "B       sub_FFC5E884_my\n" //------------->
"loc_FFC5EAEC:\n"
                "BL      sub_FFC5D914\n"
                "BL      sub_FFC5E338\n"
"loc_FFC5EAF4:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R4,PC}\n"
"loc_FFC5EAFC:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4,PC}\n"
    );
} //#fe

void __attribute__((naked,noinline)) sub_FFC5E884_my(){  //#fs
asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "BL      sub_FFC5F500\n"
                "CMP     R0, #1\n"
                "BLEQ    sub_FFC5F5E8\n"
                "LDR     R4, =0x5738\n"
                "MOV     R5, #1\n"
                "LDR     R0, [R4,#0x24]\n"
                "CMP     R0, #0\n"
                "LDRNE   R0, [R4,#0x4C]\n"
                "CMPNE   R0, #0\n"
                "BEQ     loc_FFC5E8F0\n"
                "BL      sub_FFC5F500\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC5E8F0\n"
                "BL      sub_FFC5F5E8\n"
                "LDR     R0, [R4,#0x78]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC5E8F0\n"
                "LDR     R1, =0xFFC5EA04\n" // aAcStartupshowi ; "AC:StartupShowInfo"
                "MOV     R0, #0x20\n"
                "BL      sub_FFC5556C\n"
                "BL      sub_FFD70AF0\n"
                "BL      sub_FFD70A80\n"
                "MOV     R1, #0\n"
                "MOV     R0, #0x51\n"
                "BL      sub_FFC6695C\n"
                "STR     R5, [R4,#0x78]\n"
"loc_FFC5E8F0:\n"
                "BL      sub_FFC5F500\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC5E93C\n"
                "LDR     R0, [R4,#0x44]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC5E93C\n"
                "LDR     R0, [R4,#0x74]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC5E93C\n"
                "LDR     R1, =0xFFC5EA18\n" // aAcDispshot ; "AC:DispShot"
                "MOV     R0, #0x20\n"
                "BL      sub_FFC5556C\n"
                "MOV     R1, #0\n"
                "MOV     R0, #0x8C\n"
                "BL      sub_FFC6695C\n"
                "BL      sub_FFC64D10\n"
                "MOV     R0, #0x21\n"
                "BL      sub_FFC6699C\n"
                "STR     R5, [R4,#0x74]\n"
"loc_FFC5E93C:\n"
                "LDR     R0, [R4,#0x38]\n"
                "CMP     R0, #0\n"
                "LDRNE   R0, [R4,#0x3C]\n"
                "CMPNE   R0, #0\n"
                "LDRNE   R0, [R4,#0x44]\n"
                "CMPNE   R0, #0\n"
                "LDRNE   R0, [R4,#0x48]\n"
                "CMPNE   R0, #0\n"
                "LDRNE   R0, [R4,#0x1C]\n"
                "LDRNE   R1, [R4,#0x20]\n"
                "ORRNES  R0, R0, R1\n"
                "BEQ     loc_FFC5E978\n"
                "BL      sub_FFC5E1D8\n"
                "BL      sub_FFC5E338\n"
                "B       loc_FFC5E9A0\n"
"loc_FFC5E978:\n"
                "LDR     R0, [R4,#0x58]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC5E9A8\n"
                "BL      sub_FFC5E220\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC5E9A8\n"
                "BL      sub_FFC60B90\n"
                "BL      sub_FFC60B4C\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC5F3D0\n"
"loc_FFC5E9A0:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
"loc_FFC5E9A8:\n"
                "BL      sub_FFC5E220\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC5E9D0\n"
                "LDR     R0, [R4,#0x7C]\n"
                "CMP     R0, #0\n"
                "BLEQ    sub_FFC5F62C_my\n" //------------->
                "MOV     R0, #0\n"
                "STR     R0, [R4,#0x70]\n"
                "STR     R0, [R4,#0x74]\n"
                "STR     R0, [R4,#0x78]\n"
"loc_FFC5E9D0:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
} // #fe






void __attribute__((naked,noinline)) sub_FFC5F62C_my(){
 asm volatile(
               "STMFD   SP!, {R4,LR}\n"
               "LDR     R1, =0xFFC5F84C\n" 				// aAcEntryrecboot ; "AC:EntryRecBoot"
               "MOV     R0, #0x20\n"
               "BL      sub_FFC5556C\n"
               "BL      sub_FFC19DB4\n"
               "BL      sub_FFC5F950\n"
               "BL      sub_FFC62BE0_my\n"				// Continue here
               "MOV     R0, #1\n"
               "BL      sub_FFC5DCB4\n"
               "BL      sub_FFC5E15C\n"
               "LDMFD   SP!, {R4,LR}\n"
               "B       sub_FFC5E3CC\n"
 );
} // #fe




// Note: One sub_ missing from this firmware compared to A720
void __attribute__((naked,noinline)) sub_FFC62BE0_my(){
 asm volatile(
               "STMFD   SP!, {R4-R6,LR}\n"
               "LDR     R1, =0xFFC62DEC\n" // aStartrecmode ; "StartRecMode"
               "MOV     R0, #0x20\n"
               "BL      sub_FFC5556C\n"
               "LDR     R4, =0x59C0\n"
               "MOV     R0, #6\n"
               "MOV     R5, #1\n"
               "STR     R0, [R4,#0x5C]\n"
               "STR     R5, [R4,#0x10]\n"
               "BL      sub_FFD2D98C\n"
               "BL      sub_FFD33794\n"
               "BL      sub_FFD3206C\n"
               // One sub_ missing from this firmware compared to A720
               "BL      sub_FFC63000_my\n" //------------->
               "BL      sub_FFD3B758\n"
               "MOV     R0, #1\n"
               "STR     R5, [R4,#0x18]\n"
               "BL      sub_FFC630B0\n"
               "MOV     R0, #3\n"
               "STR     R0, [R4,#0x60]\n"
               "LDR     R1, [R4,#0x64]\n"
               "LDMFD   SP!, {R4-R6,LR}\n"
               "MOV     R0, #0\n"
               "BX      R1\n"
 );
} //#fe		







void __attribute__((naked,noinline)) sub_FFC63000_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R0, =0x855\n"
                "BL      sub_FFD2A1E8\n"
                "BL      sub_FFC19B98\n"
                "BL      sub_FFC629A8_my\n" //------------->
                "BL      sub_FFD2D294\n"
                "BL      sub_FFD1CFBC\n"
                "BL      sub_FFD35574\n"
                "BL      sub_FFD35990\n"
                "BL      sub_FFD3ADFC\n"
                "BL      sub_FFD35BAC\n"
                "BL      sub_FFD35774\n"
                "BL      sub_FFD33EC4\n"
                "BL      sub_FFD3AA5C\n"
                "BL      sub_FFC66A3C\n" // taskcreate_DSITask
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFC6686C\n" // taskcreate_FaceFrame
 
 );
} //#fe








// branches are together

void __attribute__((naked,noinline)) sub_FFC629A8_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R0, =0x5A28\n"
                //ADR     R1, sub_FFC627A8
                "LDR     R1, =sub_FFC627A8_my\n" //-------------> (branch 1)
                "BL      sub_FFC671F0\n"
                "LDR     R1, =0x59C0\n"
                //ADR     R0, sub_FFC628D0
                "LDR     R0, =sub_FFC628D0_my\n" //-------------> (branch 2)
                "STR     R0, [R1,#0x64]\n"
                "LDMFD   SP!, {R4,PC}\n"
 );
}



//branch 1

void __attribute__((naked,noinline)) sub_FFC627A8_my(){
 asm volatile(
                "STMFD   SP!, {R3-R5,LR}\n"
                "LDR     R4, =0x59C0\n"
                "LDR     R0, [R4,#0x3C]\n"
                "CMP     R0, #0\n"
                "BLEQ    sub_FFD1BD20\n"
                "LDR     R0, [R4,#0x30]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC627E8\n"
                "LDR     R1, =0xFFC628B0\n" // a__preparecaptu ; "__PrepareCaptureModeChange__"
                "MOV     R0, #0x20\n"
                "BL      sub_FFC5556C\n"
                "MOV     R0, #0\n"
                "STR     R0, [R4,#0x30]\n"
                "STR     R0, [R4,#0x2C]\n"
                "BL      sub_FFC626A0\n"
                "LDMFD   SP!, {R3-R5,PC}\n"
"loc_FFC627E8:\n"
                "BL      sub_FFC15514\n"
                "LDRH    R0, [R4,#4]\n"
                "MOV     R1, SP\n"
                "STRH    R0, [SP]\n"
                "LDR     R0, [R4,#0x5C]\n"
                "STRH    R0, [SP,#0x2]\n"
                "MOV     R0, #0x40\n"
                "BL      sub_FFC6695C\n"
                "LDR     R0, [R4,#0x1C]\n"
                "CMP     R0, #0\n"
                "LDREQH  R0, [R4,#4]\n"
                "BLEQ    sub_FFC5D030\n" // PTM_SetCurrentCaptureMode
                "LDRH    R0, [R4,#4]\n"
                "MOV     R1, #1\n"
                "BL      sub_FFC61AB0_my\n" //-------------> (branches are joining here, DecideCaptureMode)
                "LDR     R0, [R4,#0x60]\n"
                "BL      sub_FFC630B0\n"
                "MOV     R0, #3\n"
                "STR     R0, [R4,#0x60]\n"
                "LDR     R1, [R4,#0x64]\n"
                "ADD     SP, SP, #4\n"
                "LDMFD   SP!, {R4,R5,LR}\n"
                "MOV     R0, #0\n"
                "BX      R1\n"
 );
} 











//branch 2

void __attribute__((naked,noinline)) sub_FFC628D0_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "LDR     R4, =0x59C0\n"
                "LDRH    R0, [R4,#4]\n"
                "BL      sub_FFD339CC\n"
                "BL      sub_FFD3222C\n"
                "BL      sub_FFD35C3C\n"
                //"BL      nullsub_98\n"
                "BL      sub_FFD34050\n"
                "BL      sub_FFD1ECC0\n"
                "MOV     R5, #0\n"
                "MOV     R0, R5\n"
                "STR     R5, [R4,#0x24]\n"
                "BL      sub_FFC155F8\n"
                "BL      sub_FFD1E38C\n"
                "STR     R5, [R4,#0x3C]\n"
                "LDRH    R0, [R4,#4]\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC61AB0_my\n" //-------------> (branches are joining here, DecideCaptureMode)
                "BL      sub_FFC64D10\n"
                "LDR     R1, [R4,#0x5C]\n"
                "MOV     R0, #0x41\n"
                "BL      sub_FFC6695C\n"
                "BL      sub_FFD3221C\n"
                "BL      sub_FFD2DB00\n"
                "CMP     R0, #0\n"
                "BLEQ    sub_FFD32230\n"
                "BL      sub_FFD33954\n"
                "BL      sub_FFD1BB90\n"
                "BL      sub_FFC5B440\n"
                "STR     R0, [R4,#0x58]\n"
                "LDR     R0, =0x8003\n"
                "STR     R5, [R4,#0x2C]\n"
                "BL      sub_FFC5D158\n" // PTM_GetCurrentItem
                "STRH    R0, [R4]\n"
                "LDR     R0, =0x313D\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC5BEC4\n" // PostLogicalEventToUI
                "BL      sub_FFC62F9C\n"
                "LDR     R0, [R4,#0x30]\n"
                "CMP     R0, #1\n"
                "STREQ   R5, [R4,#0x30]\n"
                "LDMEQFD SP!, {R4-R6,LR}\n"
                "BEQ     sub_FFC626A0\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 
 );
} //#fe









//branches are joining here

void __attribute__((naked,noinline)) sub_FFC61AB0_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R5, R1\n"
                "MOV     R4, R0\n"
                "MOV     R0, #0x60\n"
                "LDR     R1, =0xFFC61D80\n" // a_decidecapture ; "_DecideCaptureMode"
                "BL      sub_FFC5556C\n"
                "LDR     R6, =0x59C0\n"
                "LDR     R0, [R6,#0x10]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC61BDC\n"
                "LDR     R0, [R6,#0x18]\n"
                "LDR     R2, =0x820A\n"
                "LDR     R1, =0xFFFE0000\n" // aVer_011_001
                "CMP     R0, #1\n"
                "BNE     loc_FFC61B24\n"
                "CMP     R5, #1\n"
                "LDMEQFD SP!, {R4-R6,PC}\n"
                "CMP     R5, #0\n"
                "BNE     loc_FFC61B24\n"
                "CMP     R4, R2\n"
                "BEQ     loc_FFC61B1C\n"
                "CMP     R1, R4,LSL#17\n"
                "TSTNE   R4, #0xC00\n"
                "BEQ     loc_FFC61B18\n"
                "BL      sub_FFC62E84_my\n" //-------------> (StartMovie)
                "B       loc_FFC61B1C\n"
"loc_FFC61B18:\n"
                "BL      sub_FFC62E38\n"
"loc_FFC61B1C:\n"
                "BL      sub_FFC62FFC\n"
                "B       loc_FFC61BDC\n"
"loc_FFC61B24:\n"
                "CMP     R4, R2\n"
                "BEQ     loc_FFC61BD4\n"
                "CMP     R1, R4,LSL#17\n"
                "LDRH    R0, [R6,#2]\n"
                "TSTNE   R4, #0xC00\n"
                "BEQ     loc_FFC61B84\n"
                "CMP     R0, R2\n"
                "BEQ     loc_FFC61BD4\n"
                "CMP     R1, R0,LSL#17\n"
                "TSTNE   R0, #0xC00\n"
                "BEQ     loc_FFC61B68\n"
                "LDR     R1, =0xFFC61DA0\n" // a_movietomovie ; "_MovieToMovie"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "CMP     R5, #1\n"
                "BEQ     loc_FFC61BAC\n"
                "B       loc_FFC61B7C\n"
"loc_FFC61B68:\n"
                "LDR     R1, =0xFFC61DB0\n" // a_stilltomovie ; "_StillToMovie"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "CMP     R5, #1\n"
                "BEQ     loc_FFC61BC8\n"
"loc_FFC61B7C:\n"
                "BL      sub_FFC62E84_my\n" //-------------> (StartMovie)
                "B       loc_FFC61BD4\n"
"loc_FFC61B84:\n"
                "CMP     R0, R2\n"
                "BEQ     loc_FFC61BD4\n"
                "CMP     R1, R0,LSL#17\n"
                "TSTNE   R0, #0xC00\n"
                "BEQ     loc_FFC61BB4\n"
                "LDR     R1, =0xFFC61DC0\n"				// a_movietostill ; "_MovieToStill"\n"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "CMP     R5, #1\n"
                "BNE     loc_FFC61BD0\n"
"loc_FFC61BAC:\n"
                "LDMFD   SP!, {R4-R6,LR}\n"
                "B       sub_FFC62EB0\n"
"loc_FFC61BB4:\n"
                "LDR     R1, =0xFFC61DD0\n"				// a_stilltostill ; "_StillToStill"\n"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "CMP     R5, #1\n"
                "BNE     loc_FFC61BD0\n"
"loc_FFC61BC8:\n"
                "LDMFD   SP!, {R4-R6,LR}\n"
                "B       sub_FFC62E60\n"
"loc_FFC61BD0:\n"
                "BL      sub_FFC62E38\n"
"loc_FFC61BD4:\n"
                "CMP     R5, #0\n"
                "LDMNEFD SP!, {R4-R6,PC}\n"
"loc_FFC61BDC:\n"
                "STRH    R4, [R6,#2]\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
 );
} // #fe

//StartMovie
void __attribute__((naked,noinline)) sub_FFC62E84_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R1, =0xFFC62FDC\n"		  // a_startmovie ; "_StartMovie"\n"
                "MOV     R0, #0x20\n"
                "BL      sub_FFC5556C\n"
                "LDR     R0, =0x59C0\n"
                "LDR     R0, [R0,#0x28]\n"
                "CMP     R0, #0\n"
                "BLNE    sub_FFC63860\n"
                "LDMFD   SP!, {R4,LR}\n"
                "MOV     R0, #0\n"
                "B       sub_FFC65BBC_my\n"			// Continue here
 );
}


void __attribute__((naked,noinline)) sub_FFC65BBC_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R4, =0x5B6C\n"
                "MOV     R0, #0\n"
                "STR     R0, [R4,#0x30]\n"
                "LDR     R0, [R4,#8]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC65BE8\n"
                "LDR     R0, =sub_FFC657C8_my\n"			// Continue here
                "MOV     R1, #0\n"
                "BL      sub_FFC5AEA0\n" 	// CreateController
                "STR     R0, [R4,#8]\n"
"loc_FFC65BE8:\n"
                "LDR     R0, [R4,#0xC]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC65C04\n"
                "LDR     R0, =0xFFC65468\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC62B0C\n"
                "STR     R0, [R4,#0xC]\n"
"loc_FFC65C04:\n"
                "BL      sub_FFC663CC\n"
                "BL      sub_FFC654CC\n"
                "BL      sub_FFD3B164\n"
                "BL      sub_FFD3BFAC\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFD330C8\n"
 );
}


void __attribute__((naked,noinline)) sub_FFC657C8_my(){
 asm volatile(
                "STMFD   SP!, {R3-R11,LR}\n"
                "LDR     R5, =0x5B6C\n"
                "MOV     R4, R1\n"
                "LDR     R2, [R5,#0x2C]\n"
                "ADD     R0, R5, #0\n"
                "LDR     R0, [R0,#0x14]\n"
                "LDR     R9, =0x3007\n"
                "CMP     R2, #0\n"
                "MOV     R1, #0\n"
                "MOV     R11, R3\n"
                "MVN     R8, #0\n"
                "BEQ     loc_FFC65840\n"
                "CMP     R4, R9\n"
                "BEQ     loc_FFC65A30\n"
                "CMP     R4, #0x800\n"
                "LDREQ   R2, [R5,#0x38]\n"
                "CMPEQ   R11, R2\n"
                "BNE     loc_FFC65B40\n"
                "STR     R1, [R5,#0x2C]!\n"
                "CMP     R0, #0\n"
                "STR     R8, [R5,#0xC]\n"
                "BNE     loc_FFC65BB4\n"
                "BL      sub_FFC1A540\n"
                "CMP     R0, #1\n"
                "BEQ     loc_FFC65838\n"
                "BL      sub_FFC1A548\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC65BB4\n"
"loc_FFC65838:\n"
                "BL      sub_FFC65618\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65840:\n"
                "CMP     R0, #1\n"
                "SUBEQ   R12, R4, #0x2000\n"
                "SUBEQS  R12, R12, #0x1C\n"
                "BNE     loc_FFC6585C\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC65EBC\n"
                "B       loc_FFC65BB4\n"
"loc_FFC6585C:\n"
                "BL      sub_FFC5A964\n"
                "LDR     R10, =0x9A5\n"
                "CMP     R0, #1\n"
                "SUB     R6, R10, #4\n"
                "SUB     R7, R10, #2\n"
                "BNE     loc_FFC65890\n"
                "CMP     R4, R10\n"
                "CMPNE   R4, R6\n"
                "CMPNE   R4, R7\n"
                "BNE     loc_FFC65890\n"
                "BL      sub_FFC59B08\n"
                "STR     R4, [R5,#0x3C]\n"
                "B       loc_FFC65B40\n"
"loc_FFC65890:\n"
                "BL      sub_FFD32074\n"		// GetAEIntegralServiceMode_7
                "CMP     R0, #1\n"
                "BNE     loc_FFC658B0\n"
                "MOV     R0, R4\n"
                "BL      sub_FFC5BBFC\n"
                "CMP     R0, #1\n"
                "CMPNE   R4, R10\n"
                "BEQ     loc_FFC65B40\n"
"loc_FFC658B0:\n"
                "BL      sub_FFC1A618\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC658C8\n"
                "CMP     R4, R6\n"
                "CMPNE   R4, R7\n"
                "BEQ     loc_FFC65BB4\n"
"loc_FFC658C8:\n"
                "BL      sub_FFC6279C\n"
                "LDR     R1, =0x9A2\n"
                "CMP     R0, #1\n"
                "ADD     R2, R1, #2\n"
                "BNE     loc_FFC658F0\n"
                "CMP     R4, R6\n"
                "CMPNE   R4, R1\n"
                "CMPNE   R4, R7\n"
                "CMPNE   R4, R2\n"
                "BEQ     loc_FFC65BB4\n"
"loc_FFC658F0:\n"
                "LDR     R12, =0x200A\n"
                "CMP     R4, R12\n"
                "BEQ     loc_FFC65BA4\n"
                "BGT     loc_FFC6596C\n"
                "LDR     R12, =0x907\n"
                "CMP     R4, R12\n"
                "MOVEQ   R1, #2\n"
                "MOVEQ   R0, R10\n"
                "BEQ     loc_FFC65AE0\n"
                "BGT     loc_FFC65948\n"
                "SUB     R12, R4, #0x800\n"
                "LDR     R6, =0x2003\n"
                "SUBS    R12, R12, #0x26\n"
                "BEQ     loc_FFC65A44\n"
                "SUB     R12, R4, #0x800\n"
                "SUBS    R12, R12, #0x29\n"
                "BEQ     loc_FFC65A88\n"
                "CMP     R4, #0x860\n"
                "SUBNE   R12, R4, #0x800\n"
                "SUBNES  R12, R12, #0x61\n"
                "BNE     loc_FFC65B58\n"
                "B       loc_FFC65B40\n"
"loc_FFC65948:\n"
                "CMP     R4, R6\n"
                "BEQ     loc_FFC65AD8\n"
                "CMP     R4, R1\n"
                "BEQ     loc_FFC65BA4\n"
                "CMP     R4, R7\n"
                "BEQ     loc_FFC65AD8\n"
                "CMP     R4, R2\n"
                "BEQ     loc_FFC65BA4\n"
                "B       loc_FFC65B58\n"
"loc_FFC6596C:\n"
                "LDR     R12, =0x3149\n"
                "CMP     R4, R12\n"
                "MOVEQ   R1, #0\n"
                "MOVEQ   R0, #0x84\n"
                "BEQ     loc_FFC65B50\n"
                "BGT     loc_FFC659C4\n"
                "SUB     R12, R4, #0x2000\n"
                "SUBS    R12, R12, #0x20\n"
                "MOVEQ   R1, R11\n"
                "MOVEQ   R0, #0x83\n"
                "BEQ     loc_FFC65B50\n"
                "CMP     R4, R9\n"
                "BEQ     loc_FFC65A1C\n"
                "SUB     R12, R4, #0x3100\n"
                "SUBS    R12, R12, #0x35\n"
                "BEQ     loc_FFC65A00\n"
                "SUB     R12, R4, #0x3000\n"
                "SUBS    R12, R12, #0x148\n"
                "BNE     loc_FFC65B58\n"
                "MOV     R1, #0\n"
                "MOV     R0, #0x86\n"
                "B       loc_FFC65B50\n"
"loc_FFC659C4:\n"
                "SUB     R12, R4, #0x3100\n"
                "SUBS    R12, R12, #0x4A\n"
                "BEQ     loc_FFC65B48\n"
                "SUB     R12, R4, #0x4000\n"
                "SUBS    R12, R12, #3\n"
                "BEQ     loc_FFC65B04\n"
                "SUB     R12, R4, #0x4000\n"
                "SUBS    R12, R12, #8\n"
                "BEQ     loc_FFC65AE8\n"
                "SUB     R12, R4, #0x4000\n"
                "SUBS    R12, R12, #0xF\n"
                "BNE     loc_FFC65B58\n"
                "MOV     R0, #0x82\n"
                "BL      sub_FFC6699C\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65A00:\n"
                "BL      sub_FFC66400\n" 			// GetVRAMHPixelsSize_2
                "CMP     R0, #4\n"
                "BEQ     loc_FFC65BA4\n"
                "LDR     R0, [R5,#0x1C]\n"
                "CMP     R0, #0\n"
                "BLNE    sub_FFC65560\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65A1C:\n"
                "MOV     R0, #1\n"
                "STR     R0, [R5,#0x1C]\n"
                "LDR     R0, [R5,#0x18]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC65A38\n"
"loc_FFC65A30:\n"
                "BL      sub_FFC65560\n"
                "LDMFD   SP!, {R3-R11,PC}\n"
"loc_FFC65A38:\n"
                "MOV     R0, R4\n"
                "BL      sub_FFC65738\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65A44:\n"
                "BL      sub_FFC6279C\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC65A5C\n"
                "MOV     R0, R4\n"
                "BL      sub_FFC62CD0\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65A5C:\n"
                "LDR     R0, [R5,#0x10]\n"
                "LDR     R1, [R5,#0x14]\n"
                "ORR     R0, R0, R1\n"
                "LDR     R1, [R5,#0x1C]\n"
                "ORRS    R0, R0, R1\n"
                "BNE     loc_FFC65BB4\n"
                "MOV     R1, #0\n"
                "MOV     R0, R6\n"
                "BL      sub_FFC47374\n"
                "BL      sub_FFD21708\n"			// StartRecModeMenu
                "B       loc_FFC65BB4\n"
"loc_FFC65A88:\n"
                "LDR     R0, [R5,#0x10]\n"
                "LDR     R1, [R5,#0x14]\n"
                "ORRS    R0, R0, R1\n"
                "BNE     loc_FFC65BB4\n"
                "BL      sub_FFC62CDC\n"
                "CMP     R0, #0\n"
                "LDREQ   R0, [R5,#0x1C]\n"
                "CMPEQ   R0, #0\n"
                "BNE     loc_FFC65BB4\n"
                "BL      sub_FFC6279C\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC65BB4\n"
                "BL      sub_FFD3B92C\n" 			// j_IsEvfDriveMode_16\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC65BB4\n"
                "MOV     R1, #0\n"
                "MOV     R0, R6\n"
                "BL      sub_FFC47374\n"
                "BL      sub_FFD1C988\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65AD8:\n"
                "MOV     R1, #1\n"
                "MOV     R0, R4\n"
"loc_FFC65AE0:\n"
                "BL      sub_FFC65674_my\n"		// Continue here
                "LDMFD   SP!, {R3-R11,PC}\n"
"loc_FFC65AE8:\n"
                "MOV     R0, R11\n"
                "BL      sub_FFC6145C\n"
                "CMP     R0, #0\n"
                "MOVEQ   R1, R11\n"
                "MOVEQ   R0, R4\n"
                "BLEQ    sub_FFC6606C_my\n"			// Continue here
                "B       loc_FFC65B40\n"
"loc_FFC65B04:\n"
                "LDR     R0, [R5,#0x3C]\n"
                "CMN     R0, #1\n"
                "BEQ     loc_FFC65B40\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC58BEC\n"
                "LDR     R0, [R5,#0x3C]\n"
                "CMP     R0, R6\n"
                "BNE     loc_FFC65B30\n"
                "BL      sub_FFC1A540\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC65B3C\n"
"loc_FFC65B30:\n"
                "LDR     R0, [R5,#0x3C]\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC5BE78\n"			// PostLogicalEventForNotPowerType\n"
"loc_FFC65B3C:\n"
                "STR     R8, [R5,#0x3C]\n"
"loc_FFC65B40:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R3-R11,PC}\n"
"loc_FFC65B48:\n"
                "MOV     R1, #0\n"
                "MOV     R0, #0x85\n"
"loc_FFC65B50:\n"
                "BL      sub_FFC6695C\n"
                "B       loc_FFC65BB4\n"
"loc_FFC65B58:\n"
                "LDR     R12, =0x855\n"
                "CMP     R4, R12\n"
                "BEQ     loc_FFC65B94\n"
                "BGT     loc_FFC65B80\n"
                "SUB     R12, R4, #0x800\n"
                "SUBS    R12, R12, #0x38\n"
                "SUBNE   R12, R4, #0x800\n"
                "SUBNES  R12, R12, #0x39\n"
                "BNE     loc_FFC65BA4\n"
                "B       loc_FFC65B94\n"
"loc_FFC65B80:\n"
                "SUB     R12, R4, #0x800\n"
                "SUBS    R12, R12, #0x56\n"
                "SUBNE   R12, R4, #0x800\n"
                "SUBNES  R12, R12, #0x5D\n"
                "BNE     loc_FFC65BA4\n"
"loc_FFC65B94:\n"
                "LDR     R0, [R5,#0x10]\n"
                "LDR     R1, [R5,#0x14]\n"
                "ORRS    R0, R0, R1\n"
                "BNE     loc_FFC65BB4\n"
"loc_FFC65BA4:\n"
                "MOV     R1, R11\n"
                "MOV     R0, R4\n"
                "BL      sub_FFC6606C_my\n"			// Continue here
                "LDMFD   SP!, {R3-R11,PC}\n"
"loc_FFC65BB4:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R3-R11,PC}\n"
 );
} // #fe

// sub_FFC65674_my
//sub_FFC6606C_my



void __attribute__((naked,noinline)) sub_FFC65674_my(){
 asm volatile(
                "STMFD   SP!, {R4-R6,LR}\n"
                "MOV     R4, R0\n"
                "LDR     R0, =0x5B6C\n"
                "MOV     R5, R1\n"
                "LDR     R0, [R0,#0x1C]\n"
                "CMP     R0, #0\n"
                "LDRNE   R1, =0xFFC657A4\n" 				// aMvicon_fshtdwn ; "MviCon_fShtDwn"
                "BNE     loc_FFC65720\n"
                "BL      sub_FFC6640C\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC656B0\n"
"loc_FFC656A0:\n"
                "MOV     R0, R4\n"
                "LDMFD   SP!, {R4-R6,LR}\n"
                "MOV     R1, #0\n"
                "B       sub_FFC6606C_my\n"					// Continue here
"loc_FFC656B0:\n"
                "CMP     R5, #2\n"
                "BNE     loc_FFC656C8\n"
                "BL      sub_FFC64D10\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC65710\n"
                "B       loc_FFC656DC\n"
"loc_FFC656C8:\n"
                "CMP     R5, #1\n"
                "BNE     loc_FFC65710\n"
                "BL      sub_FFC64D28\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC65710\n"
"loc_FFC656DC:\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC58BEC\n"
                "SUB     R12, R4, #0x900\n"
                "SUBS    R12, R12, #0xA1\n"
                "SUBNE   R12, R4, #0x900\n"
                "SUBNES  R12, R12, #0xA3\n"
                "SUBNE   R12, R4, #0x900\n"
                "SUBNES  R12, R12, #0xA5\n"
                "LDREQ   R0, =0xC507\n"
                "MOVEQ   R1, #0\n"
                "BLEQ    sub_FFC47374\n"
"loc_FFC65708:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R4-R6,PC}\n"
"loc_FFC65710:\n"
                "BL      sub_FFC65618\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC6572C\n"
                "LDR     R1, =0xFFC657B4\n"				// aMvicon_initchk ; "MviCon_InitChkBuf"\n"
"loc_FFC65720:\n"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "B       loc_FFC65708\n"
"loc_FFC6572C:\n"
                "MOV     R0, R5\n"
                "BL      sub_FFD31120\n"
                "B       loc_FFC656A0\n"
 );
} // #fe



void __attribute__((naked,noinline)) sub_FFC6606C_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R7, R1\n"
                "MOV     R4, R0\n"
                "BL      sub_FFC66488\n"
                "LDR     R5, =0x5BB0\n"
                "LDR     R3, =0x200A\n"
                "LDR     R12, [R5]\n"
                "LDR     R2, =0x4008\n"
                "LDR     R6, =0x9A3\n"
                "LDR     R0, =0x3007\n"
                "LDR     R1, =0x1051\n"
                "CMP     R12, #9\n"
                "ADD     LR, R3, #0x15\n"
                "ADDLS   PC, PC, R12,LSL#2\n"
                "B       loc_FFC663C4\n"
"loc_FFC660A8:\n"
                "B       loc_FFC660D0\n"
"loc_FFC660AC:\n"
                "B       loc_FFC660E0\n"
"loc_FFC660B0:\n"
                "B       loc_FFC660F0\n"
"loc_FFC660B4:\n"
                "B       loc_FFC66164\n"
"loc_FFC660B8:\n"
                "B       loc_FFC661A4\n"
"loc_FFC660BC:\n"
                "B       loc_FFC6622C\n"
"loc_FFC660C0:\n"
                "B       loc_FFC6625C\n"
"loc_FFC660C4:\n"
                "B       loc_FFC6630C\n"
"loc_FFC660C8:\n"
                "B       loc_FFC662D0\n"
"loc_FFC660CC:\n"
                "B       loc_FFC66334\n"
"loc_FFC660D0:\n"
                "MOV     R1, R7\n"
                "MOV     R0, R4\n"
                "LDMFD   SP!, {R4-R8,LR}\n"
                "B       sub_FFC65FE8\n"
"loc_FFC660E0:\n"
                "MOV     R1, R7\n"
                "MOV     R0, R4\n"
                "LDMFD   SP!, {R4-R8,LR}\n"
                "B       sub_FFC66608_my\n"					// Continue here
"loc_FFC660F0:\n"
                "CMP     R4, R1\n"
                "BEQ     loc_FFC66154\n"
                "SUB     R12, R4, #0x2000\n"
                "SUBS    R12, R12, #6\n"
                "BEQ     loc_FFC66118\n"
                "CMP     R4, R0\n"
                "BEQ     loc_FFC6615C\n"
                "SUB     R12, R4, #0x3100\n"
                "SUBS    R12, R12, #0x4B\n"
                "BNE     loc_FFC663C4\n"
"loc_FFC66118:\n"
                "BL      sub_FFC655F4\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC66470\n"
                "LDR     R0, [R5,#8]\n"
                "CMP     R0, #0\n"
                "MOVNE   R1, #0\n"
                "MOVNE   R0, R6\n"
                "BNE     loc_FFC6614C\n"
                "LDR     R0, [R5,#4]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC66374\n"
                "LDR     R0, =0x9A1\n"
                "MOV     R1, #0\n"
"loc_FFC6614C:\n"
                "BL      sub_FFC65FE8\n"
                "B       loc_FFC66374\n"
"loc_FFC66154:\n"
                "BL      sub_FFC6657C\n"
                "B       loc_FFC66374\n"
"loc_FFC6615C:\n"
                "BL      sub_FFC66594\n"
                "B       loc_FFC66374\n"
"loc_FFC66164:\n"
                "SUB     R12, R4, #0x900\n"
                "SUBS    R12, R12, #0xA2\n"
                "BEQ     loc_FFC66194\n"
                "CMP     R4, R6\n"
                "BEQ     loc_FFC6618C\n"
                "CMP     R4, R1\n"
                "BEQ     loc_FFC6619C\n"
                "CMP     R4, R0\n"
                "BLEQ    sub_FFC66594\n"
                "B       loc_FFC663C4\n"
"loc_FFC6618C:\n"
                "BL      sub_FFC65F8C_my\n"				// Continue here EntryActionOnPreMoving
                "B       loc_FFC663C4\n"
"loc_FFC66194:\n"
                "BL      sub_FFC66558\n"
                "B       loc_FFC663C4\n"
"loc_FFC6619C:\n"
                "BL      sub_FFC6657C\n"
                "B       loc_FFC663C4\n"
"loc_FFC661A4:\n"
                "CMP     R4, LR\n"
                "BEQ     loc_FFC66200\n"
                "BGT     loc_FFC661CC\n"
                "CMP     R4, R6\n"
                "BEQ     loc_FFC661E8\n"
                "CMP     R4, R1\n"
                "BEQ     loc_FFC66218\n"
"loc_FFC661C0:\n"
                "CMP     R4, R3\n"
                "BNE     loc_FFC663C4\n"
                "B       loc_FFC661DC\n"
"loc_FFC661CC:\n"
                "CMP     R4, R0\n"
                "BEQ     loc_FFC6620C\n"
"loc_FFC661D4:\n"
                "CMP     R4, R2\n"
                "BNE     loc_FFC663C4\n"
"loc_FFC661DC:\n"
                "BL      sub_FFC665E4\n"
                "BL      sub_FFC66558\n"
                "B       loc_FFC66374\n"
"loc_FFC661E8:\n"
                "BL      sub_FFC16BA4\n"
                "MOV     R0, #5\n"
                "BL      sub_FFC66470\n"
                "MOV     R0, #0\n"
                "STR     R0, [R5,#0xC]\n"
                "B       loc_FFC66374\n"
"loc_FFC66200:\n"
                "MOV     R0, #5\n"
                "BL      sub_FFC66470\n"
                "B       loc_FFC66250\n"
"loc_FFC6620C:\n"
                "BL      sub_FFC16BA4\n"
                "BL      sub_FFC665E4\n"
                "B       loc_FFC66304\n"
"loc_FFC66218:\n"
                "BL      sub_FFC16BA4\n"
                "BL      sub_FFC665E4\n"
                "B       loc_FFC66264\n"
"loc_FFC66224:\n"
                "BL      sub_FFC66470\n"
                "B       loc_FFC66374\n"
"loc_FFC6622C:\n"
                "CMP     R4, LR\n"
                "BEQ     loc_FFC66250\n"
                "BGT     loc_FFC66244\n"
                "CMP     R4, R1\n"
                "BNE     loc_FFC661C0\n"
                "B       loc_FFC66264\n"
"loc_FFC66244:\n"
                "CMP     R4, R0\n"
                "BNE     loc_FFC661D4\n"
                "B       loc_FFC66304\n"
"loc_FFC66250:\n"
                "MOV     R0, R7\n"
                "BL      sub_FFC665B0\n"
                "B       loc_FFC66374\n"
"loc_FFC6625C:\n"
                "CMP     R4, R1\n"
                "BNE     loc_FFC663C4\n"
"loc_FFC66264:\n"
                "MOV     R0, #8\n"
                "B       loc_FFC66224\n"
"loc_FFC662D0:\n"
                "CMP     R4, R0\n"
                "BEQ     loc_FFC66304\n"
                "BGT     loc_FFC662F0\n"
                "CMP     R4, R3\n"
                "BEQ     loc_FFC66154\n"
                "CMP     R4, LR\n"
                "BEQ     loc_FFC66250\n"
                "B       loc_FFC663C4\n"
"loc_FFC662F0:\n"
                "CMP     R4, R2\n"
                "SUBNE   R12, R4, #0x4000\n"
                "SUBNES  R12, R12, #0xE\n"
                "BEQ     loc_FFC66154\n"
                "B       loc_FFC663C4\n"
"loc_FFC66304:\n"
                "MOV     R0, #7\n"
                "B       loc_FFC66224\n"
"loc_FFC6630C:\n"
                "CMP     R4, R3\n"
                "BEQ     loc_FFC66324\n"
                "CMP     R4, LR\n"
                "BEQ     loc_FFC66250\n"
                "CMP     R4, R2\n"
                "BNE     loc_FFC663C4\n"
"loc_FFC66324:\n"
                "BL      sub_FFC66558\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC65738\n"
                "B       loc_FFC66374\n"
"loc_FFC66334:\n"
                "SUB     R12, R4, #0x800\n"
                "SUBS    R12, R12, #0x4A\n"
                "BEQ     loc_FFC6637C\n"
                "CMP     R4, R1\n"
                "BEQ     loc_FFC663B4\n"
                "CMP     R4, R0\n"
                "BEQ     loc_FFC663A4\n"
                "SUB     R12, R4, #0x3100\n"
                "SUBS    R12, R12, #0x2A\n"
                "BNE     loc_FFC663C4\n"
                "BL      sub_FFC66510\n"
                "LDR     R0, [R5,#0x14]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC66374\n"
                "BL      sub_FFC6652C_my\n"				// Continue here EntryActionOnMoving
                "BL      sub_FFD32080\n"
"loc_FFC66374:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC6637C:\n"
                "BL      sub_FFC66510\n"
                "LDR     R0, =0x8007\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC5D14C\n"					// j_PTM_SetCurrentItem
                "BL      sub_FFD310D4\n"
                "BL      sub_FFC66558\n"
                "BL      sub_FFD32080\n"
                "BL      sub_FFC655F4\n"
                "MOV     R0, #0\n"
                "B       loc_FFC66224\n"
"loc_FFC663A4:\n"
                "BL      sub_FFC66510\n"
                "BL      sub_FFD310D4\n"
                "BL      sub_FFD32080\n"
                "B       loc_FFC6615C\n"
"loc_FFC663B4:\n"
                "BL      sub_FFC66510\n"
                "BL      sub_FFD310D4\n"
                "BL      sub_FFD32080\n"
                "B       loc_FFC66154\n"
"loc_FFC663C4:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
                ".ltorg\n"
 );
} // #fe

// subs used in the sub above : 
//sub_FFC66608_my
//sub_FFC65F8C_my
//sub_FFC6652C_my




void __attribute__((naked,noinline)) sub_FFC66608_my(){
 asm volatile(
                "LDR     R3, =0x5BB0\n"
                "LDR     R12, =0x2006\n"
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R1, [R3,#0xC]\n"
                "LDR     R2, [R3,#0x14]\n"
                "CMP     R0, R12\n"
                "BEQ     loc_FFC6667C\n"
                "BGT     loc_FFC66648\n"
                "SUB     R12, R0, #0x900\n"
                "SUBS    R12, R12, #0xA2\n"
                "BEQ     loc_FFC666A0\n"
                "SUB     R12, R0, #0x1000\n"
                "SUBS    R12, R12, #0x51\n"
                "BNE     loc_FFC666C4\n"
                "BL      sub_FFC6657C\n"
                "B       loc_FFC666BC\n"
"loc_FFC66648:\n"
                "SUB     R12, R0, #0x3000\n"
                "SUBS    R12, R12, #7\n"
                "BEQ     loc_FFC666B8\n"
                "SUB     R12, R0, #0x3100\n"
                "SUBS    R12, R12, #0x4B\n"
                "BNE     loc_FFC666C4\n"
                "CMP     R2, #0\n"
                "BNE     loc_FFC666BC\n"
                "LDR     R0, [R3,#8]\n"
                "ORRS    R0, R0, R1\n"
                "BEQ     loc_FFC66688\n"
                "BL      sub_FFC65F8C_my\n"				// Continue here
                "B       loc_FFC666BC\n"
"loc_FFC6667C:\n"
                "CMP     R2, #0\n"
                "BLEQ    sub_FFC64D48\n"
                "B       loc_FFC666BC\n"
"loc_FFC66688:\n"
                "LDR     R0, [R3,#4]\n"
                "CMP     R0, #0\n"
                "MOVNE   R0, #3\n"
                "BNE     loc_FFC666B0\n"
                "BL      sub_FFC66558\n"
                "B       loc_FFC666BC\n"
"loc_FFC666A0:\n"
                "CMP     R1, #0\n"
                "BNE     loc_FFC666BC\n"
                "BL      sub_FFC16760\n"
                "MOV     R0, #2\n"
"loc_FFC666B0:\n"
                "BL      sub_FFC66470\n"
                "B       loc_FFC666BC\n"
"loc_FFC666B8:\n"
                "BL      sub_FFC66594\n"
"loc_FFC666BC:\n"
                "MOV     R0, #0\n"
                "LDMFD   SP!, {R4,PC}\n"
"loc_FFC666C4:\n"
                "MOV     R0, #1\n"
                "LDMFD   SP!, {R4,PC}\n"
 );
} //#fe





void __attribute__((naked,noinline)) sub_FFC65F8C_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R1, =0xFFC6626C\n" 					// a_entryactionon ; "_EntryActionOnPreMoving"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "LDR     R4, =0x5BB0\n"
                "LDR     R0, [R4,#0x10]\n"
                "CMP     R0, #0\n"
                "LDMEQFD SP!, {R4,LR}\n"
                "BEQ     sub_FFC6652C_my\n"						// Continue here
                "LDR     R1, =0xFFC66288\n" 					// a_entryaction_0 ; "_EntryActionOnSelfTimer"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "BL      sub_FFD320AC\n"
                "LDR     R0, [R4,#0x18]\n"
                "CMP     R0, #1\n"
                "MOVNE   R0, #1\n"
                "STRNE   R0, [R4,#0x18]\n"
                "BLNE    sub_FFC5C808\n" 							// LockMainPower\n"
                "MOV     R0, #9\n"
                "BL      sub_FFC66470\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFD30F90\n"
 );
} // #fe




void __attribute__((naked,noinline)) sub_FFC6652C_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "LDR     R1, =0xFFC666E4\n" 					// a_entryaction_1 ; "_EntryActionOnMoving"
                "MOV     R0, #0x60\n"
                "BL      sub_FFC5556C\n"
                "LDR     R1, =0x5BB0\n"
                "MOV     R0, #0\n"
                "STR     R0, [R1,#0xC]\n"
                "MOV     R0, #4\n"
                "BL      sub_FFC66470\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFC65C5C_my\n"			// Continue here
 
 );
} //#fe

void __attribute__((naked,noinline)) sub_FFC65C5C_my(){
 asm volatile(
                "LDR     R0, =0x5B6C\n"
                "STMFD   SP!, {R3,LR}\n"
                "LDR     R1, [R0,#0x40]\n"
                "CMP     R1, #1\n"
                "MOVNE   R1, #1\n"
                "STRNE   R1, [R0,#0x40]\n"
                "BLNE    sub_FFC5C808\n" 			// LockMainPower\n"
                "MOV     R1, #0\n"
                "MOV     R0, #0x80\n"
                "BL      sub_FFC6695C\n"
                "MOV     R2, #2\n"
                "MOV     R1, SP\n"
                "MOV     R0, #0x6B\n"
                "BL      sub_FFC5819C\n"			// PT_GetPropertyCaseString_0\n"
                "MOV     R2, #2\n"
                "MOV     R1, SP\n"
                "MOV     R0, #0xA3\n"
                "BL      sub_FFC5809C\n"			// PT_GetPropertyCaseString\n"
                "BL      sub_FFC47434\n"
                "BL      sub_FFC65000\n"
                "BL      sub_FFC16B74_my\n"		// Continue here (SSAPI:RecordMovie)
                "BL      sub_FFC655AC\n"
                "LDMFD   SP!, {R12,PC}\n"
 );
} //#fe





void __attribute__((naked,noinline)) sub_FFC16B74_my(){
 asm volatile(
                "STMFD   SP!, {R4,LR}\n"
                "MOV     R4, R0\n"
                "MOV     R0, #0x20\n"
                "LDR     R1, =0xFFC16C94\n"		 // aSsapiRecordmov ; "SSAPI::RecordMovie"
                "BL      sub_FFC5556C\n"
                "BL      sub_FFC16FC8\n"
                "CMP     R0, #0\n"
                "LDMNEFD SP!, {R4,PC}\n"
                "BL      sub_FFC48A68\n"
                "MOV     R0, R4\n"
                "LDMFD   SP!, {R4,LR}\n"
                "B       sub_FFC4AB5C_my\n"		// Continue here
 );
} // #fe



void __attribute__((naked,noinline)) sub_FFC4AB5C_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "MOV     R8, R0\n"
                "MOV     R0, #0x41\n"
                "SUB     SP, SP, #0x38\n"
                "MOV     R5, #0\n"
                "STR     R0, [SP,#0x34]\n"
                "BL      sub_FFC4AB2C\n"
                "CMP     R0, #0\n"
                "LDRNE   R1, =0x163\n"
                "BNE     loc_FFC4AD08\n"
                "LDR     R4, =0x52E4\n"
                "MOV     R1, #0x5E\n"
                "LDR     R0, [R4,#8]\n"
                "BL      sub_FFC173FC\n"
                "BL      sub_FFC5832C\n"
                "STR     R0, [R4,#4]\n"
                "MOV     R0, #0\n"
                "BL      sub_FFC52170\n"
                "STR     R0, [SP,#0x28]\n"
                "ADD     R0, SP, #0x28\n"
                "MOV     R1, SP\n"
                "BL      sub_FFC522BC\n"
                "MOV     R0, SP\n"
                "BL      sub_FFC521A4\n"
                "STR     R0, [SP,#0x2C]\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x34\n"
                "BL      sub_FFC58640\n"
                "LDR     R7, [SP,#0x2C]\n"
                "BL      sub_FFC4B04C\n"
                "MOV     R6, #0\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "STR     R6, [SP,#0x2C]\n"
                "STR     R6, [SP,#0x28]\n"
                "BL      sub_FFC1F6E8\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x2F\n"
                "BL      sub_FFC58640\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x28\n"
                "MOV     R1, #0x2D\n"
                "BL      sub_FFC58640\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "BL      sub_FFC23048\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0x30\n"
                "BL      sub_FFC58640\n"
                "ADD     R1, SP, #0x28\n"
                "ADD     R0, SP, #0x2C\n"
                "BL      sub_FFC1FEC0\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x28\n"
                "MOV     R1, #0x2E\n"
                "BL      sub_FFC58640\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #2\n"
                "ADD     R2, SP, #0x2C\n"
                "MOV     R1, #0xB8\n"
                "BL      sub_FFC586EC\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x142\n"
                "LDRNE   R0, =0xFFC4AF80\n"				// aSsmovierec_c ; "SsMovieRec.c"
                "BLNE    sub_FFC0BDB8\n"					//	DebugAssert
                "LDRH    R0, [SP,#0x2C]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x28\n"
                "CMP     R0, #0\n"
                "MOVNE   R0, #1\n"
                "STR     R0, [SP,#0x28]\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R1, #0x92\n"
                "BL      sub_FFC58640\n"
                "MOV     R2, #1\n"
                "ADD     R1, SP, #0x34\n"
                "MOV     R0, #0xFA\n"
                "BL      sub_FFC5819C\n"				// PT_GetPropertyCaseString
                "TST     R0, #1\n"
                "LDRNE   R1, =0x17A\n"
                "LDRNE   R0, =0xFFC4AF80\n"			// aSsmovierec_c ; "SsMovieRec.c"
                "BLNE    sub_FFC0BDB8\n"				// DebugAssert
                "LDRB    R0, [SP,#0x34]\n"
                "MOV     R3, R8\n"
                "MOV     R2, #0x14\n"
                "AND     R1, R0, #0xFF\n"
                "ADD     R0, SP, #0x30\n"
                "STR     R7, [SP]\n"
                "BL      sub_FFCEBB1C\n"
                "TST     R0, #1\n"
                "LDRNE   R1, =0x17E\n"
                "BNE     loc_FFC4AD08\n"
                "LDR     R0, =0x18370\n"
                "LDR     R1, [SP,#0x30]\n"
                "MOV     R2, #0x10\n"
                "BL      sub_FFCDE9C0\n"
                "TST     R0, #1\n"
                "BEQ     loc_FFC4AD18\n"
                "LDR     R1, =0x186\n"
"loc_FFC4AD08:\n"
                "LDR     R0, =0xFFC4AF80\n" //			aSsmovierec_c ; "SsMovieRec.c"
                "BL      sub_FFC0BDB8\n" 			// DebugAssert
"loc_FFC4AD10:\n"
                "ADD     SP, SP, #0x38\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC4AD18:\n"
                "LDR     R0, [R4,#4]\n"
                "MOV     R3, #4\n"
                "ADD     R2, SP, #0x30\n"
                "MOV     R1, #0x2B\n"
                "BL      sub_FFC58640\n"
                "BL      sub_FFC66B40\n"
                "LDRSB   R1, [SP,#0x34]\n"
                "CMP     R0, R1\n"
                "MOVEQ   R7, #0\n"
                "BEQ     loc_FFC4AD6C\n"
                "LDR     R5, =0x18370\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC66CBC\n"
                "MOV     R8, R0\n"
                "BL      sub_FFC95774\n"
                "CMP     R8, R0\n"
                "MOV     R7, R0\n"
                "LDRLS   R1, =0x193\n"
                "LDRLS   R0, =0xFFC4AF80\n" 			// aSsmovierec_c ; "SsMovieRec.c"
                "BLLS    sub_FFC0BDB8\n"	 				// DebugAssert
                "SUB     R7, R8, R7\n"
"loc_FFC4AD6C:\n"
                "BL      sub_FFC46780_my\n" 					// Continue here  (taskcreate_MovieRecord)
                "LDR     R0, =0x18394\n"
                "LDRH    R3, [R0,#0x46]\n"
                "LDRH    R2, [R0,#0x44]\n"
                "LDR     R1, [R0,#0x40]\n"
                "LDR     R0, [R0,#0x3C]\n"
                "BL      sub_FFC45800\n"
                "MOV     R3, #0\n"
                "LDR     R2, =0xFFC4AAF4\n"
                "MOV     R1, #0\n"
                "LDR     R0, =0xFFC4AB08\n"
                "ADD     R8, SP, #0xC\n"
                "STMIA   R8, {R0-R3}\n"
                "LDR     R2, =0xFFC4AB18\n"
                "LDR     R1, =0xFFC4AB04\n"
                "STMEA   SP, {R1-R3}\n"
                "LDR     R1, [R4,#4]\n"
                "MOV     R3, R6\n"
                "MOV     R2, R7\n"
                "MOV     R0, R5\n"
                "BL      sub_FFC45B5C\n"
                "LDR     R0, [R4,#8]\n"
                "MOV     R1, #0x20\n"
                "BL      sub_FFC173C8\n"
                "B       loc_FFC4AD10\n"
 );
} // #fe

void __attribute__((naked,noinline)) sub_FFC46780_my(){
 asm volatile(
                "STMFD   SP!, {R3-R9,LR}\n"
                "LDR     R5, =0x5178\n"
                "MOV     R6, #0\n"
                "STR     R6, [R5,#0x20]\n"
                "LDR     R0, [R5,#4]\n"
                "LDR     R8, =0x2710\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC46838\n"
                "MOV     R0, #1\n"
                "STR     R0, [R5,#4]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC0BC34\n"
                "STR     R0, [R5,#0x10]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0\n"
                "BL      sub_FFC0BC34\n"
                "STR     R0, [R5,#0x14]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0xA\n"
                "BL      sub_FFC0BBEC\n"
                "STR     R0, [R5,#0x18]\n"
                "MOV     R0, #0\n"
                "MOV     R1, #0xA\n"
                "BL      sub_FFC0BBEC\n"
                "LDR     R7, =0x17F84\n"
                "MOV     R4, #9\n"
                "ADD     R9, R4, #0x2D4\n"
                "STR     R0, [R5,#0x1C]\n"
"loc_FFC467F4:\n"
                "RSB     R0, R4, R4,LSL#3\n"
                "STR     R6, [R7,R0,LSL#2]\n"
                "ADD     R1, R7, R0,LSL#2\n"
                "STR     R9, [SP]\n"
                "LDR     R0, [R5,#0x1C]\n"
                "LDR     R3, =0xFFC45AFC\n" 				// aMovierecorder_
                "MOV     R2, R8\n"
                "BL      sub_FFC0BCF8\n"
                "SUBS    R4, R4, #1\n"
                "BPL     loc_FFC467F4\n"
                "MOV     R3, #0\n"
                "STR     R3, [SP]\n"
                "LDR     R3, =MovieRecord_Task_my\n"			// FFC46678 task_MovieRecord
                "MOV     R2, #0x1000\n"
                "MOV     R1, #0x14\n"
                "LDR     R0, =0xFFC46988\n"								// aMovierecord ; "MovieRecord"
                "BL      sub_FFC0BBB8\n" 									// KernelCreateTask
"loc_FFC46838:\n"
                "BL      sub_FFD0A4C8\n"									// taskcreate_AviWrite
                "BL      sub_FFC4689C\n"
                "MOV     R1, R0\n"
                "MOV     R0, #0xB\n"
                "ADD     R3, R0, #0x2DC\n"
                "STR     R0, [R1]\n"
                "STR     R3, [SP]\n"
                "LDR     R3, =0xFFC45AFC\n" 							// aMovierecorder_ ; "MovieRecorder.c"
                "MOV     R2, R8\n"
                "LDR     R0, [R5,#0x18]\n"
                "BL      sub_FFC0BCF8\n"
                "LDMFD   SP!, {R3-R9,PC}\n"
 );
} // #fe
*/

void __attribute__((naked,noinline)) MovieRecord_Task_my(){
 asm volatile(
                "STMFD   SP!, {R2-R8,LR}\n"
                "LDR     R8, =0x32B\n"
                "LDR     R7, =0x2710\n"
                "LDR     R4, =0x5178\n"
                "MOV     R6, #0\n"
                "MOV     R5, #1\n"
"loc_FFC46690:\n"
                "LDR     R0, [R4,#0x18]\n"
                "MOV     R2, #0\n"
                "ADD     R1, SP, #4\n"
                "BL      sub_FFC1764C\n"
                "LDR     R0, [R4,#0x20]\n"
                "CMP     R0, #0\n"
                "BNE     loc_FFC46760\n"
                "LDR     R0, [SP,#4]\n"
                "LDR     R1, [R0]\n"
                "SUB     R1, R1, #2\n"
                "CMP     R1, #9\n"
                "ADDLS   PC, PC, R1,LSL#2\n"
                "B       loc_FFC46760\n"
"loc_FFC466C4:\n"
                "B       loc_FFC46714\n"
"loc_FFC466C8:\n"
                "B       loc_FFC46734\n"
"loc_FFC466CC:\n"
                "B       loc_FFC46744\n"
"loc_FFC466D0:\n"
                "B       loc_FFC4674C\n"
"loc_FFC466D4:\n"
                "B       loc_FFC4671C\n"
"loc_FFC466D8:\n"
                "B       loc_FFC46754\n"
"loc_FFC466DC:\n"
                "B       loc_FFC46724\n"
"loc_FFC466E0:\n"
                "B       loc_FFC46760\n"
"loc_FFC466E4:\n"
                "B       loc_FFC4675C\n"
"loc_FFC466E8:\n"
                "B       loc_FFC466EC\n"
"loc_FFC466EC:\n"
                "LDR     R0, =0xFFC46374\n"
                "STR     R6, [R4,#0x34]\n"
                "STR     R0, [R4,#0xA0]\n"
                "LDR     R0, =0xFFC45DEC\n"
                "LDR     R2, =0xFFC45D08\n"
                "LDR     R1, =0x180AC\n"
                "STR     R6, [R4,#0x24]\n"
                "BL      sub_FFCA2C98\n"
                "STR     R5, [R4,#0x38]\n"
                "B       loc_FFC46760\n"
"loc_FFC46714:\n"
                "BL      unlock_optical_zoom\n"		//  +
                "BL      sub_FFC4646C\n"
                "B       loc_FFC46760\n"
"loc_FFC4671C:\n"
                "BL      sub_FFC46174_my\n"		//----------------->
                "B       loc_FFC46760\n"
"loc_FFC46724:\n"
                "LDR     R1, [R0,#0x10]\n"
                "LDR     R0, [R0,#4]\n"
                "BL      sub_FFD0B0D4\n"
                "B       loc_FFC46760\n"
"loc_FFC46734:\n"
                "LDR     R0, [R4,#0x38]\n"
                "CMP     R0, #5\n"
                "STRNE   R5, [R4,#0x28]\n"
                "B       loc_FFC46760\n"
"loc_FFC46744:\n"
                "BL      sub_FFC45F7C\n"
                "B       loc_FFC46760\n"
"loc_FFC4674C:\n"
                "BL      sub_FFC45E38\n"
                "B       loc_FFC46760\n"
"loc_FFC46754:\n"
                "BL      sub_FFC45C94\n"
                "B       loc_FFC46760\n"
"loc_FFC4675C:\n"
                "BL      sub_FFC468C8\n"
"loc_FFC46760:\n"
                "LDR     R1, [SP,#4]\n"
                "LDR     R3, =0xFFC45AFC\n"		// aMovierecorder_
                "STR     R6, [R1]\n"
                "STR     R8, [SP]\n"
                "LDR     R0, [R4,#0x1C]\n"
                "MOV     R2, R7\n"
                "BL      sub_FFC0BCF8\n"
                "B       loc_FFC46690\n"
 );
}


void __attribute__((naked,noinline)) sub_FFC46174_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "SUB     SP, SP, #0x40\n"
                "MOV     R6, #0\n"
                "LDR     R5, =0x5178\n"
                "MOV     R4, R0\n"
                "STR     R6, [SP,#0x30]\n"
                "STR     R6, [SP,#0x28]\n"
                "LDR     R0, [R5,#0x38]\n"
                "MOV     R8, #4\n"
                "CMP     R0, #3\n"
                "STREQ   R8, [R5,#0x38]\n"
                "LDR     R0, [R5,#0xA0]\n"
                "BLX     R0\n"
                //".long   0xE12FFF30\n"		// don't know how it's determined but so far same code as a720
                "LDR     R0, [R5,#0x38]\n"
                "CMP     R0, #4\n"
                "BNE     loc_FFC4624C\n"
                "ADD     R3, SP, #0x28\n"
                "ADD     R2, SP, #0x2C\n"
                "ADD     R1, SP, #0x30\n"
                "ADD     R0, SP, #0x34\n"
                "BL      sub_FFD0B268\n"
                "CMP     R0, #0\n"
                "MOV     R7, #1\n"
                "BNE     loc_FFC461F0\n"
                "LDR     R1, [R5,#0x28]\n"
                "CMP     R1, #1\n"
                "BNE     loc_FFC46254\n"
                "LDR     R1, [R5,#0x50]\n"
                "LDR     R2, [R5,#0x3C]\n"
                "CMP     R1, R2\n"
                "BCC     loc_FFC46254\n"
"loc_FFC461F0:\n"
                "CMP     R0, #0x80000001\n"
                "STREQ   R8, [R5,#0x54]\n"
                "BEQ     loc_FFC46228\n"
                "CMP     R0, #0x80000003\n"
                "STREQ   R7, [R5,#0x54]\n"
                "BEQ     loc_FFC46228\n"
                "CMP     R0, #0x80000005\n"
                "MOVEQ   R0, #2\n"
                "BEQ     loc_FFC46224\n"
                "CMP     R0, #0x80000007\n"
                "STRNE   R6, [R5,#0x54]\n"
                "BNE     loc_FFC46228\n"
                "MOV     R0, #3\n"
"loc_FFC46224:\n"
                "STR     R0, [R5,#0x54]\n"
"loc_FFC46228:\n"
                "LDR     R0, =0x180DC\n"
                "LDR     R0, [R0,#8]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC46240\n"
                "BL      sub_FFC32918\n"
                "B       loc_FFC46244\n"
"loc_FFC46240:\n"
                "BL      sub_FFC45C94\n"
"loc_FFC46244:\n"
                "MOV     R0, #5\n"
                "STR     R0, [R5,#0x38]\n"
"loc_FFC4624C:\n"
                "ADD     SP, SP, #0x40\n"
                "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFC46254:\n"
                "LDR     LR, [SP,#0x30]\n"
                "CMP     LR, #0\n"
                "BEQ     loc_FFC4631C\n"
                "STR     R7, [R5,#0x2C]\n"
                "LDR     R0, [R5,#0x6C]\n"
                "LDR     R1, [R4,#0x14]\n"
                "LDR     R2, [R4,#0x18]\n"
                "LDR     R12, [R4,#0xC]\n"
                "ADD     R3, SP, #0x38\n"
                "ADD     R8, SP, #0x14\n"
                "STMIA   R8, {R0-R3}\n"
                "LDR     R3, [R5,#0x58]\n"
                "ADD     R2, SP, #0x3C\n"
                "ADD     R8, SP, #8\n"
                "LDRD    R0, [SP,#0x28]\n"
                //".long   0xE1CD02D8\n"		// again not sure why, but so far same code as a720
                "STMIA   R8, {R0,R2,R3}\n"
                "STR     R1, [SP,#4]\n"
                "STR     LR, [SP]\n"
                "LDMIB   R4, {R0,R1}\n"
                "LDR     R3, [SP,#0x34]\n"
                "MOV     R2, R12\n"
                "BL      sub_FFCC99E4\n"
                "LDR     R0, [R5,#0x10]\n"
                "MOV     R1, #0x3E8\n"
                "BL      sub_FFC0B774\n"		// TakeSemaphore
                "CMP     R0, #9\n"
                "BNE     loc_FFC462D0\n"
                "BL      sub_FFD0B844\n"
                "MOV     R0, #0x90000\n"
                "STR     R7, [R5,#0x38]\n"
                "B       loc_FFC462E8\n"
"loc_FFC462D0:\n"
                "LDR     R0, [SP,#0x38]\n"
                "CMP     R0, #0\n"
                "BEQ     loc_FFC462F0\n"
                "BL      sub_FFD0B844\n"
                "MOV     R0, #0xA0000\n"
                "STR     R7, [R5,#0x38]\n"
"loc_FFC462E8:\n"
                "BL      sub_FFC5CAA4\n"		// HardwareDefect
                "B       loc_FFC4624C\n"
"loc_FFC462F0:\n"
                "BL      sub_FFCC9AA8\n"
                "LDR     R0, [SP,#0x34]\n"
                "LDR     R1, [SP,#0x3C]\n"
                "BL      sub_FFD0B5EC\n"
                "LDR     R0, [R5,#0x4C]\n"
                "LDR     R1, =0x51E4\n"
                "ADD     R0, R0, #1\n"
                "STR     R0, [R5,#0x4C]\n"
                "LDR     R0, [SP,#0x3C]\n"
                "MOV     R2, #0\n"
                "BL      sub_FFD0947C_my\n"		//----------------->
"loc_FFC4631C:\n"
                "LDR     R0, [R5,#0x50]\n"
                "ADD     R0, R0, #1\n"
                "STR     R0, [R5,#0x50]\n"
                "LDR     R1, [R5,#0x78]\n"
                "MUL     R0, R1, R0\n"
                "LDR     R1, [R5,#0x74]\n"
                "BL      sub_FFE5A618\n"
                "MOV     R4, R0\n"
                "BL      sub_FFD0B87C\n"
                "LDR     R1, [R5,#0x70]\n"
                "CMP     R1, R4\n"
                "BNE     loc_FFC46358\n"
                "LDR     R0, [R5,#0x30]\n"
                "CMP     R0, #1\n"
                "BNE     loc_FFC4636C\n"
"loc_FFC46358:\n"
                "LDR     R1, [R5,#0x84]\n"
                "MOV     R0, R4\n"
                "BLX     R1\n"
                //".long   0xE12FFF31\n"		// again, no clue about these but same code in a720...
                "STR     R4, [R5,#0x70]\n"
                "STR     R6, [R5,#0x30]\n"
"loc_FFC4636C:\n"
                "STR     R6, [R5,#0x2C]\n"
                "B       loc_FFC4624C\n"
 );
}


void __attribute__((naked,noinline)) sub_FFD0947C_my(){
 asm volatile(
                "STMFD   SP!, {R4-R8,LR}\n"
                "LDR     R4, =0x7F7C\n"
                "LDR     LR, [R4]\n"
                "LDR     R2, [R4,#8]\n"
                "CMP     LR, #0\n"
                "LDRNE   R3, [R4,#0xC]\n"
                "MOV     R5, R2\n"
                "CMPNE   R3, #1\n"
                "MOVEQ   R2, #0\n"
                "STREQ   R0, [R4]\n"
                "STREQ   R2, [R4,#0xC]\n"
                "BEQ     loc_FFD09548\n"
                "LDR     R3, [R4,#4]\n"
                "LDR     R7, =table\n"		// unk_FFE78188
                "ADD     R12, R3, R3,LSL#1\n"
                "LDR     R3, [R7,R12,LSL#2]\n"
                "ADD     R6, R7, #0x30\n"
                "LDR     R8, [R6,R12,LSL#2]\n"
                "SUB     R3, LR, R3\n"
                "CMP     R3, #0\n"
                "SUB     LR, LR, R8\n"
                "BLE     loc_FFD09504\n"
                "ADD     R12, R7, R12,LSL#2\n"
                "LDR     LR, [R12,#4]\n"
                "CMP     LR, R3\n"
                "ADDGE   R2, R2, #1\n"
                "BGE     loc_FFD094F8\n"
                "LDR     R12, [R12,#8]\n"
                "CMP     R12, R3\n"
                "ADDLT   R2, R2, #3\n"
                "ADDGE   R2, R2, #2\n"
"loc_FFD094F8:\n"
                //"CMP     R2, #0x17\n"		// -
                //"MOVGE   R2, #0x16\n"		// -
                "CMP     R2, #0x1A\n"		// +
                "MOVGE   R2, #0x19\n"		// +
                "B       loc_FFD09538\n"
"loc_FFD09504:\n"
                "CMP     LR, #0\n"
                "BGE     loc_FFD09538\n"
                "ADD     R3, R6, R12,LSL#2\n"
                "LDR     R12, [R3,#4]\n"
                "CMP     R12, LR\n"
                "SUBLE   R2, R2, #1\n"
                "BLE     loc_FFD09530\n"
                "LDR     R3, [R3,#8]\n"
                "CMP     R3, LR\n"
                "SUBGT   R2, R2, #3\n"
                "SUBLE   R2, R2, #2\n"
"loc_FFD09530:\n"
                "CMP     R2, #0\n"
                "MOVLT   R2, #0\n"
"loc_FFD09538:\n"
                "CMP     R2, R5\n"
                "STRNE   R2, [R4,#8]\n"
                "MOVNE   R2, #1\n"
                "STRNE   R2, [R4,#0xC]\n"
"loc_FFD09548:\n"
                "LDR     R2, =CompressionRateTable\n"			// unk_FFE7812C
                "LDR     R3, [R4,#8]\n"
                "LDR     R2, [R2,R3,LSL#2]\n"
                
                "LDR     R3, =video_mode\n"      // +
                "LDR     R3, [R3]\n"             // +
                "LDR     R3, [R3]\n"             // +
                "CMP     R3, #1\n"               // +
                "LDREQ   R3, =video_quality\n"   // +
                "LDREQ   R3, [R3]\n"             // +
                "LDREQ   R2, [R3]\n"             // +

                "STR     R2, [R1]\n"
                "STR     R0, [R4]\n"
                "BL      mute_on_zoom\n"		// +
                "LDMFD   SP!, {R4-R8,PC}\n"
 );
}

#include "conf.h"

int *video_quality = &conf.video_quality;
int *video_mode    = &conf.video_mode;

long def_table[24]={0x2000, 0x38D, 0x788, 0x5800, 0x9C5, 0x14B8, 0x10000, 0x1C6A, 0x3C45, 0x8000, 0xE35, 0x1E23,
           0x1CCD, -0x2E1, -0x579, 0x4F33, -0x7EB, -0xF0C, 0xE666, -0x170A, -0x2BC6, 0x7333, -0xB85, -0x15E3};

long table[24];

void change_video_tables(int a, int b){
 int i;
 for (i=0;i<24;i++) table[i]=(def_table[i]*a)/b;
}

long CompressionRateTable[]={0x60, 0x5D, 0x5A, 0x57, 0x54, 0x51, 0x4D, 0x48, 0x42, 0x3B, 0x32, 0x29, 0x22, 0x1D, 0x17, 0x14, 0x10, 0xE, 0xB, 9, 7, 6, 5, 4, 3, 2, 1};
