#include "stubs_asm.h"

DEF(physw_status, 0x0EBDC)
DEF(physw_run, 0x1BF0)
DEF(FlashParamsTable,0xFFE9EF08)
DEF(zoom_busy, 0x7F4C)  //0x7F38 + 0x14 //OK
DEF(focus_busy, 0x9D50) //  0x9CB8
DEF(canon_menu_active, 0x8BDC)
DEF(canon_shoot_menu_active, 0x94B9)

DEF(recreview_hold, 0xABE8) // 0xAB38+0xB0

DEF(movie_status, 0x51B0)
DEF(some_flag_for_af_scan, 0xB808)
DEF(zoom_status, 0xBA7C)
DEF(some_f_for_dng, 0x8934)
DEF(second_ext_for_dng, 0x8954)
DEF(levent_table,0xFFE7fB40)
DEF(playrec_mode,0x5320)
