#include "conf.h"

int *video_quality = &conf.video_quality;
int *video_mode    = &conf.video_mode;

long def_table1[9]={0x2000,0x38D,0x788,0x5800,0x9C5,0x14B8,0x10000,0x1C6A,0x3C45};
long def_table2[9]={0x1CCD,-0x2E1,-0x579,0x4F33,-0x7EB,-0xF0C,0xE666,-0x170A,-0x2BC6};

long table1[9], table2[9];

void change_video_tables(int a, int b){
 int i;
 for (i=0;i<9;i++) {table1[i]=(def_table1[i]*a)/b; table2[i]=(def_table2[i]*a)/b;}
}

long CompressionRateTable[]={0x60, 0x5D, 0x5A, 0x57, 0x54, 0x51, 0x4D, 0x48, 0x42, 0x3B, 0x32, 0x29, 0x22, 0x1D, 0x17, 0x14, 0x10, 0xE, 0xB, 9, 7, 6, 5, 4, 3, 2, 1};


void __attribute__((naked,noinline)) movie_record_task(){
 asm volatile(
"                 STMFD   SP!, {R4,LR}\n"
"                 SUB     SP, SP, #4\n"
"                 MOV     R4, SP\n"
"                 B       loc_FFD1D02C\n"
" loc_FFD1CF7C:\n"
"                 LDR     R3, =0x73EB8\n"
"                 LDR     R2, [R3]\n"
"                 CMP     R2, #0\n"
"                 BNE     loc_FFD1D018\n"
"                 SUB     R3, R12, #1\n"
"                 CMP     R3, #0xA\n"
"                 LDRLS   PC, [PC,R3,LSL#2]\n"
"                 B       loc_FFD1D018\n"
"                 .long loc_FFD1CFC8\n"
"                 .long loc_FFD1CFD0\n"
"                 .long loc_FFD1CFE8\n"
"                 .long loc_FFD1CFF0\n"
"                 .long loc_FFD1CFF8\n"
"                 .long loc_FFD1CFD8\n"
"                 .long loc_FFD1D000\n"
"                 .long loc_FFD1CFE0\n"
"                 .long loc_FFD1D018\n"
"                 .long loc_FFD1D010\n"
"                 .long loc_FFD1D008\n"
" loc_FFD1CFC8:\n"
"                 BL      sub_FFD1D0AC\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1CFD0:\n"
"                 BL      unlock_optical_zoom\n" // +
"                 BL      sub_FFD1D2E0_my\n" //changed some code to allow longer movies
"                 B       loc_FFD1D014\n"
" loc_FFD1CFD8:\n"
"                 BL      sub_FFD1D7A8_my\n" //
"                 B       loc_FFD1D014\n"
" loc_FFD1CFE0:\n"
"                 BL      sub_FFD1DC94\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1CFE8:\n"
"                 BL      sub_FFD1DA7C\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1CFF0:\n"
"                 BL      sub_FFD1DEA0\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1CFF8:\n"
"                 BL      sub_FFD1E064\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1D000:\n"
"                 BL      sub_FFD1DD54\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1D008:\n"
"                 BL      sub_FFD1DE34\n"
"                 B       loc_FFD1D014\n"
" loc_FFD1D010:\n"
"                 BL      sub_FFD1DACC\n"
" loc_FFD1D014:\n"
"                 LDR     R1, [SP]\n"
" loc_FFD1D018:\n"
"                 LDR     R3, =0x73DE8\n"
"                 MOV     R2, #0\n"
"                 STR     R2, [R1]\n"
"                 LDR     R0, [R3]\n"
"                 BL      sub_ffc113ac\n" // PostMessageQueue
" loc_FFD1D02C:\n"
"                 LDR     R3, =0x73DE4\n"
"                 MOV     R1, R4\n"
"                 LDR     R0, [R3]\n"
"                 MOV     R2, #0\n"
"                 BL      sub_ffc10f94\n" // ReceiveMessageQueue
"                 LDR     R0, [SP]\n"
"                 LDR     R12, [R0]\n"
"                 CMP     R12, #0xC\n"
"                 MOV     R1, R0\n"
"                 BNE     loc_FFD1CF7C\n"
"                 LDR     R3, =0x73DDC\n"
"                 LDR     R0, [R3]\n"
"                 BL      sub_ffc11d68\n" // GiveSemaphore
"                 BL      sub_ffc12724\n" // ExitTask
"                 ADD     SP, SP, #4\n"
"                 LDMFD   SP!, {R4,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFD1D7A8_my(){
 asm volatile(
"                 STMFD   SP!, {R4-R11,LR}\n"
"                 LDR     R5, =0x73ED4\n"
"                 SUB     SP, SP, #0x34\n"
"                 LDR     R3, [R5]\n"
"                 CMP     R3, #3\n"
"                 MOV     R4, R0\n"
"                 MOVEQ   R3, #4\n"
"                 STREQ   R3, [R5]\n"
"                 LDR     R3, =0x73F7C\n"
"                 MOV     LR, PC\n"
"                 LDR     PC, [R3]\n"
"                 LDR     R2, [R5]\n"
"                 CMP     R2, #4\n"
"                 BNE     loc_FFD1D9A4\n"
"                 ADD     R0, SP, #0x58-0x28\n"
"                 ADD     R1, SP, #0x58-0x2C\n"
"                 ADD     R2, SP, #0x58-0x30\n"
"                 ADD     R3, SP, #0x58-0x34\n"
"                 BL      sub_FFD1F044_my\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFD1D824\n"
"                 LDR     R3, =0x73EC0\n"
"                 LDR     R2, [R3]\n"
"                 CMP     R2, #1\n"
"                 BNE     loc_FFD1D838\n"
"                 LDR     R2, =0x73F10\n"
"                 LDR     R1, =0x73EE8\n"
"                 LDR     R12, [R2]\n"
"                 LDR     R3, [R1]\n"
"                 CMP     R12, R3\n"
"                 BCC     loc_FFD1D838\n"
" loc_FFD1D824:\n"
"                 BL      sub_FFD1D9F4\n"
"                 BL      sub_FFD1DC28\n"
"                 MOV     R3, #5\n"
"                 STR     R3, [R5]\n"
"                 B       loc_FFD1D9A4\n"
" loc_FFD1D838:\n"
"                 LDR     R12, =0x73F18\n"
"                 LDR     R11, =0x73F24\n"
"                 LDMIB   R4, {R0-R2}\n"
"                 LDR     R10, [R12]\n"
"                 LDR     R7, [R11]\n"
"                 LDR     R4, [SP,#0x58-0x2C]\n"
"                 LDR     R5, [SP,#0x58-0x30]\n"
"                 LDR     R6, [SP,#0x58-0x34]\n"
"                 LDR     R8, =0x73EC4\n"
"                 ADD     R12, SP, #0x58-0x38\n"
"                 ADD     LR, SP, #0x58-0x3C\n"
"                 MOV     R9, #1\n"
"                 LDR     R3, [SP,#0x58-0x28]\n"
"                 STMEA   SP, {R4-R6,R12}\n"
"                 STR     R10, [SP,#0x58-0x48]\n"
"                 STR     R7, [SP,#0x58-0x44]\n"
"                 STR     LR, [SP,#0x58-0x40]\n"
"                 STR     R9, [R8]\n"
"                 BL      sub_FFC82338\n"
"                 LDR     R3, =0x73DDC\n"
"                 MOV     R1, #0x3E8\n"
"                 LDR     R0, [R3]\n"
"                 BL      sub_ffc11b80\n" // TakeSemaphore
"                 CMP     R0, #9\n"
"                 BNE     loc_FFD1D8AC\n"
"                 BL      sub_FFD1F794\n"
"                 LDR     R3, =0x73ED4\n"
"                 LDR     R0, =0xffd1d790\n" //  JPEGTimeOut
"                 B       loc_FFD1D8C4\n"
" loc_FFD1D8AC:\n"
"                 LDR     R6, [SP,#0x58-0x3C]\n"
"                 CMP     R6, #0\n"
"                 BEQ     loc_FFD1D8D0\n"
"                 BL      sub_FFD1F794\n"
"                 LDR     R3, =0x73ED4\n"
"                 LDR     R0, =0xffd1d79c\n" //  JPEGICError
" loc_FFD1D8C4:\n"
"                 STR     R9, [R3]\n"
"                 BL      sub_FFD31890\n"
"                 B       loc_FFD1D9A4\n"
" loc_FFD1D8D0:\n"
"                 BL      sub_FFC824AC\n"
"                 LDR     R7, =0x73F10\n"
"                 LDR     R0, [SP,#0x58-0x28]\n"
"                 LDR     R1, [SP,#0x58-0x38]\n"
"                 BL      sub_FFD1F4B8\n"
"                 LDR     R3, [R7]\n"
"                 LDR     R8, =0x73EFC\n"
"                 ADD     R3, R3, #1\n"
"                 LDR     R1, [R8]\n" //fps
"                 MOV     R0, R3\n"
"                 STR     R3, [R7]\n"
"                 BL      sub_ffe68858\n"
"                 CMP     R0, #0\n"
"                 BNE     loc_FFD1D944\n"
"                 LDR     R4, =0x73F90\n"
"                 LDR     R3, [R4]\n"
"                 LDR     R2, =0x73ED8\n"
"                 LDR     R5, =0x73F88\n"
"                 AND     R3, R3, #1\n"
"                 LDR     R0, [R5,R3,LSL#2]\n"
"                 LDR     R1, [R2]\n"
"                 BL      sub_FFD1EF5C\n"
"                 LDR     R0, [R4]\n"
"                 AND     R0, R0, #1\n"
"                 ADD     R0, R5, R0,LSL#2\n"
"                 BL      sub_FFD1EF08\n"
"                 LDR     R3, [R4]\n"
"                 ADD     R3, R3, #1\n"
"                 STR     R3, [R4]\n"
" loc_FFD1D944:\n"
"                 LDR     R0, [SP,#0x58-0x38]\n"
"                 MOV     R1, R11\n"
"                 MOV     R2, R6\n"
"                 BL      sub_FFD1E3C8_my\n" // hope it's the right one...
"                 LDR     R4, [R7]\n"
"                 LDR     R1, [R8]\n"
"                 MOV     R0, R4\n"
"                 BL      sub_ffe68858\n"
"                 CMP     R0, #0\n"
"                 BEQ     loc_FFD1D980\n"
"                 LDR     R5, =0x73EC8\n"
"                 LDR     R3, [R5]\n"
"                 CMP     R3, #1\n"
"                 BNE     loc_FFD1D998\n"
"                 B       loc_FFD1D984\n"
" loc_FFD1D980:\n"
"                 LDR     R5, =0x73EC8\n"
" loc_FFD1D984:\n"
"                 MOV     R0, R4\n"
"                 LDR     R3, =0x73F58\n"
"                 MOV     LR, PC\n"
"                 LDR     PC, [R3]\n"
"                 STR     R6, [R5]\n"
" loc_FFD1D998:\n"
"                 LDR     R2, =0x73EC4\n"
"                 MOV     R3, #0\n"
"                 STR     R3, [R2]\n"
" loc_FFD1D9A4:\n"
"                 ADD     SP, SP, #0x34\n"
"                 LDMFD   SP!, {R4-R11,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFD1F044_my(){
 asm volatile(
"                 STMFD   SP!, {R4-R11,LR}\n"
"                 LDR     R5, =0x74234\n" //video frames counter
"                 SUB     SP, SP, #0x14\n"
"                 LDR     LR, [R5]\n"
"                 LDR     R12, =0x7424C\n" //[0x7424c] holds 3600 dec during rec. :) happens to be the framenum limit @ 20fps
"                 ADD     LR, LR, #1\n" //add 1 frame
"                 LDR     R4, [R12]\n"
"                 STR     LR, [R5]\n" //store it back
"                 LDR     R12, =0x742C8\n"
"                 STR     R0, [SP,#0x38-0x28]\n"
"                 STR     R1, [SP,#0x38-0x2C]\n"
"                 STR     R2, [SP,#0x38-0x30]\n"
"                 STR     R3, [SP,#0x38-0x34]\n"
"                 CMP     LR, R4\n" //framenum > allowed?
"                 LDR     R11, [R12]\n"
"                 MOVHI   R0, #0x80000001\n"
"                 BHI     loc_FFD1F46C\n" //if so, go to end with status 0x80000001 (but we don't want that :) unfortunately, this isn't enough
"                 LDR     R3, =0x742B0\n"
"                 MOV     R0, LR\n"
"                 LDR     R1, [R3]\n"
"                 BL      sub_ffe68858\n" // umodsi3
"                 CMP     R0, #1\n"
"                 BNE     loc_FFD1F264\n"
"                 LDR     R0, =0x742D0\n"
"                 LDR     R1, =0x74220\n"
"                 LDR     R3, [R0]\n"
"                 LDR     R2, [R1]\n"
"                 CMP     R3, R2\n"
"                 LDREQ   R3, =0x742CC\n"
"                 LDREQ   R5, [R3]\n"
"                 MOVNE   R5, R2\n"
"                 LDR     R3, =0x74234\n"
"                 LDR     R2, =0x742B0\n"
"                 LDR     R0, [R3]\n"
"                 LDR     R1, [R2]\n"
"                 BL      sub_ffe681c8\n" // udivsi3
"                 LDR     R3, =0x74228\n"
"                 ADD     R0, R0, #1\n"
"                 AND     R0, R0, #1\n"
"                 STR     R5, [R3,R0,LSL#2]\n"
"                 LDR     R3, =0x7421C\n"
"                 LDR     R2, [R3]\n"
"                 CMP     R5, R2\n"
"                 BHI     loc_FFD1F114\n"
"                 LDR     R4, =0x7426C\n"
"                 LDR     R3, [R4]\n"
"                 ADD     R3, R5, R3\n"
"                 ADD     R3, R3, #8\n"
"                 CMP     R2, R3\n"
"                 BCS     loc_FFD1F118\n"
" loc_FFD1F10C:\n"
"                 MOV     R0, #0x80000003\n"
"                 B       loc_FFD1F46C\n"
" loc_FFD1F114:\n"
"                 LDR     R4, =0x7426C\n"
" loc_FFD1F118:\n"
"                 LDR     R3, [R4]\n"
"                 LDR     R2, =0x742D0\n"
"                 ADD     R1, R5, R3\n"
"                 LDR     R3, [R2]\n"
"                 ADD     R2, R1, #8\n"
"                 CMP     R2, R3\n"
"                 BLS     loc_FFD1F164\n"
"                 LDR     R2, =0x742CC\n"
"                 LDR     R0, =0x7421C\n"
"                 RSB     R3, R3, R1\n"
"                 LDR     R1, [R2]\n"
"                 ADD     R3, R3, #8\n"
"                 LDR     R2, [R0]\n"
"                 ADD     R1, R1, R3\n"
"                 CMP     R2, R1\n"
"                 BCC     loc_FFD1F10C\n"
"                 LDR     R3, =0x74220\n"
"                 STR     R1, [R3]\n"
"                 B       loc_FFD1F16C\n"
" loc_FFD1F164:\n"
"                 LDR     R3, =0x74220\n"
"                 STR     R2, [R3]\n"
" loc_FFD1F16C:\n"
"                 LDR     R3, [R4]\n"
"                 LDR     R12, =0x74280\n"
"                 ADD     R3, R3, #0x18\n"
"                 LDR     R2, [R12,#4]\n"
"                 MOV     R0, R3\n"
"                 MOV     R1, #0\n"
"                 CMP     R1, R2\n"
"                 BHI     loc_FFD1F3B0\n"
"                 BNE     loc_FFD1F19C\n"
"                 LDR     R3, [R12]\n"
"                 CMP     R0, R3\n"
"                 BHI     loc_FFD1F3B0\n"
" loc_FFD1F19C:\n"
"                 LDR     R4, [R4]\n"
"                 LDR     LR, =0x74288\n"
"                 STR     R4, [SP,#0x38-0x38]\n"
"                 LDR     R12, =0x74280\n"
"                 LDR     R3, =0x74234\n"
"                 LDMIA   LR, {R7,R8}\n"
"                 LDMIA   R12, {R5,R6}\n"
"                 LDR     R10, [R3]\n"
"                 LDR     R2, =0x742B0\n"
"                 MOV     R3, R4\n"
"                 MOV     R4, #0\n"
"                 ADDS    R7, R7, R3\n"
"                 ADC     R8, R8, R4\n"
"                 LDR     R9, [R2]\n"
"                 SUBS    R5, R5, R3\n"
"                 SBC     R6, R6, R4\n"
"                 MVN     R2, #0x0\n"
"                 MVN     R1, #0x17\n"
"                 ADDS    R5, R5, R1\n"
"                 MOV     R4, #0\n"
"                 MOV     R3, #0x18\n"
"                 ADC     R6, R6, R2\n"
"                 ADDS    R7, R7, R3\n"
"                 ADC     R8, R8, R4\n"
"                 STMIA   R12, {R5,R6}\n"
"                 SUB     R0, R10, #1\n"
"                 MOV     R1, R9\n"
"                 STMIA   LR, {R7,R8}\n"
"                 BL      sub_ffe681c8\n"
"                 CMP     R10, #1\n"
"                 MLA     R0, R9, R0, R0\n"
"                 BEQ     loc_FFD1F264\n"
"                 SUB     R3, R0, #1\n"
"                 MOV     R3, R3,LSL#4\n"
"                 ADD     R4, R11, #0x10\n"
"                 ADD     R5, R11, #0x14\n"
"                 LDR     R1, [R5,R3]\n"
"                 LDR     R2, [R4,R3]\n"
"                 LDR     LR, =0x62773130\n"
"                 ADD     R2, R2, R1\n"
"                 MOV     R3, R0,LSL#4\n"
"                 ADD     R2, R2, #8\n"
"                 MOV     R0, #0\n"
"                 ADD     R12, R11, #0xC\n"
"                 ADD     R1, R11, #8\n"
"                 STR     LR, [R1,R3]\n"
"                 STR     R0, [R12,R3]\n"
"                 STR     R2, [R4,R3]\n"
"                 LDR     R0, [SP,#0x38-0x38]\n"
"                 STR     R0, [R5,R3]\n"
" loc_FFD1F264:\n"
"                 LDR     R2, =0x74220\n"
"                 LDR     R3, =0x742D0\n"
"                 LDR     R1, [R2]\n"
"                 LDR     R0, [R3]\n"
"                 ADD     R3, R1, #9\n"
"                 CMP     R3, R0\n"
"                 BLS     loc_FFD1F2A0\n"
"                 LDR     R2, =0x742CC\n"
"                 LDR     R3, [R2]\n"
"                 ADD     R3, R3, R1\n"
"                 RSB     R3, R0, R3\n"
"                 LDR     R0, [SP,#0x38-0x28]\n"
"                 ADD     R3, R3, #8\n"
"                 STR     R3, [R0]\n"
"                 B       loc_FFD1F2AC\n"
" loc_FFD1F2A0:\n"
"                 ADD     R3, R1, #8\n"
"                 LDR     R1, [SP,#0x38-0x28]\n"
"                 STR     R3, [R1]\n"
" loc_FFD1F2AC:\n"
"                 LDR     R2, [SP,#0x38-0x28]\n"
"                 LDR     R1, =0x7427C\n" //some other limit
"                 LDR     R3, =0x742D0\n"
"                 LDR     R12, [R2]\n"
"                 LDR     R2, [R1]\n"
"                 LDR     R0, [R3]\n"
"                 ADD     R3, R12, R2\n"
"                 CMP     R3, R0\n"
"                 BLS     loc_FFD1F300\n"
"                 LDR     R2, [SP,#0x38-0x2C]\n"
"                 RSB     R0, R12, R0\n"
"                 STR     R0, [R2]\n"
"                 LDR     R2, =0x742CC\n"
"                 LDR     R3, [R1]\n"
"                 LDR     R1, [R2]\n"
"                 RSB     R3, R0, R3\n"
"                 LDR     R0, [SP,#0x38-0x30]\n"
"                 STR     R1, [R0]\n"
"                 LDR     R1, [SP,#0x38-0x34]\n"
"                 STR     R3, [R1]\n"
"                 B       loc_FFD1F31C\n"
" loc_FFD1F300:\n"
"                 LDR     R0, [SP,#0x38-0x2C]\n"
"                 STR     R2, [R0]\n"
"                 LDR     R1, [SP,#0x38-0x34]\n"
"                 MOV     R3, #0\n"
"                 STR     R3, [R1]\n"
"                 LDR     R2, [SP,#0x38-0x30]\n"
"                 STR     R3, [R2]\n"
" loc_FFD1F31C:\n"
"                 LDR     R0, =0x74220\n"
"                 LDR     R1, =0x7421C\n"
"                 LDR     R3, [R0]\n"
"                 LDR     R2, [R1]\n"
"                 CMP     R3, R2\n"
"                 BHI     loc_FFD1F348\n"
"                 LDR     R0, [SP,#0x38-0x2C]\n"
"                 LDR     R3, [R0]\n"
"                 ADD     R3, R12, R3\n"
"                 CMP     R2, R3\n"
"                 BCC     loc_FFD1F10C\n"
" loc_FFD1F348:\n"
"                 LDR     R1, [SP,#0x38-0x30]\n"
"                 LDR     R2, [R1]\n"
"                 CMP     R2, #0\n"
"                 BEQ     loc_FFD1F37C\n"
"                 LDR     R3, =0x7421C\n"
"                 LDR     R1, [R3]\n"
"                 CMP     R2, R1\n"
"                 BHI     loc_FFD1F37C\n"
"                 LDR     R0, [SP,#0x38-0x34]\n"
"                 LDR     R3, [R0]\n"
"                 ADD     R3, R2, R3\n"
"                 CMP     R1, R3\n"
"                 BCC     loc_FFD1F10C\n"
" loc_FFD1F37C:\n"
"                 LDR     R3, =0x7427C\n" //some other limit
"                 LDR     R0, =0x74280\n"
"                 LDR     R2, [R3]\n"
"                 LDR     R3, [R0,#4]\n"
"                 ADD     R2, R2, #0x18\n"
"                 MOV     R1, R2\n"
"                 MOV     R2, #0\n"
"                 CMP     R2, R3\n"
"                 BHI     loc_FFD1F3B0\n"
"                 BNE     loc_FFD1F3B8\n"
"                 LDR     R3, [R0]\n"
"                 CMP     R1, R3\n"
"                 BLS     loc_FFD1F3B8\n"
" loc_FFD1F3B0:\n"
"                 MOV     R0, #0x80000005\n"
"                 B       loc_FFD1F46C\n"
" loc_FFD1F3B8:\n"
"                 LDR     R1, =0x74264\n"
"                 LDR     R0, =0x742B0\n"
"                 LDR     R3, [R1]\n"
"                 LDR     R2, [R0]\n"
"                 ADD     R3, R3, R2,LSL#4\n"
"                 ADD     R3, R3, R3,LSL#2\n"
"                 LDR     R12, =0x74280\n"
"                 MOV     R3, R3,LSL#1\n"
"                 ADD     R3, R3, #0xA0\n"
"                 LDR     R2, [R12,#4]\n"
"                 MOV     R0, R3\n"
"                 MOV     R1, #0\n"
"                 CMP     R1, R2\n"
"                 BHI     loc_FFD1F400\n"
"                 BNE     loc_FFD1F424\n"
"                 LDR     R3, [R12]\n"
"                 CMP     R0, R3\n"
"                 BLS     loc_FFD1F424\n"
" loc_FFD1F400:\n"
"                 LDR     R4, =0x74298\n"
"                 LDR     R1, [R4]\n"
"                 CMP     R1, #0\n"
"                 BNE     loc_FFD1F424\n"
"                 MOV     R0, #0x3140\n"
"                 ADD     R0, R0, #0x8\n"
"                 BL      sub_FFD35A08\n"
"                 MOV     R3, #1\n"
"                 STR     R3, [R4]\n"
" loc_FFD1F424:\n"
"                 LDR     R3, =0x74288\n"
"                 LDR     R12, =0x7427C\n" //some other limit
"                 LDMIA   R3, {R1,R2}\n"
"                 LDR     R0, [R12]\n"
"                 MOV     R4, #0\n"
"                 MOV     R3, #0x18\n"
"                 ADDS    R1, R1, R0\n"
"                 ADC     R2, R2, #0\n"
"                 ADDS    R1, R1, R3\n"
"                 ADC     R2, R2, R4\n"
"                 CMP     R2, #0\n"
"                 BHI     loc_FFD1F460\n"
"                 BNE     loc_FFD1F468\n"
"                 CMP     R1, #0x40000000\n"
"                 B       loc_FFD1F468\n" //  previously BLS for 1G size limit check
" loc_FFD1F460:\n"
"                 MOV     R0, #0x80000007\n"
"                 B       loc_FFD1F46C\n"
" loc_FFD1F468:\n"
"                 MOV     R0, #0\n"
" loc_FFD1F46C:\n"
"                 ADD     SP, SP, #0x14\n"
"                 LDMFD   SP!, {R4-R11,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFD1E3C8_my(){
 asm volatile(
"                 CMP     R2, #1\n"
"                 STMFD   SP!, {R4-R7,LR}\n"
"                 MOV     R7, R0\n"
"                 MOV     R6, R1\n"
"                 MOVEQ   R3, #0x79\n"
"                 STREQ   R3, [R6]\n"
"                 LDMEQFD SP!, {R4-R7,PC}\n"
"                 LDR     R12, =0x73F94\n"
"                 LDR     R0, [R12]\n"
"                 LDR     R3, =0x73F9C\n"
"                 CMP     R0, #0\n"
"                 LDR     R1, [R3]\n"
"                 BEQ     loc_FFD1E410\n"
"                 LDR     R2, =0x73FA0\n"
"                 LDR     R3, [R2]\n"
"                 CMP     R3, #1\n"
"                 BNE     loc_FFD1E424\n"
"                 B       loc_FFD1E414\n"
" loc_FFD1E410:\n"
"                 LDR     R2, =0x73FA0\n"
" loc_FFD1E414:\n"
"                 MOV     R3, #0\n"
"                 STR     R3, [R2]\n"
"                 STR     R7, [R12]\n"
"                 B       loc_FFD1E4D8\n"
" loc_FFD1E424:\n"
"                 LDR     R3, =0x73F98\n"
"                 LDR     R2, [R3]\n"
"                 LDR     R5, =table1\n" // 0xFFD1E230
"                 MOV     LR, R2,LSL#2\n"
"                 LDR     R3, [R5,LR]\n"
"                 LDR     R4, =table2\n" // 0xFFD1E26C
"                 RSB     R12, R3, R0\n"
"                 LDR     R2, [R4,LR]\n"
"                 CMP     R12, #0\n"
"                 RSB     R0, R2, R0\n"
"                 BLE     loc_FFD1E484\n"
"                 ADD     R3, R5, #0x14\n"
"                 LDR     R2, [R3,LR]\n"
"                 CMP     R2, R12\n"
"                 ADDGE   R1, R1, #1\n"
"                 BGE     loc_FFD1E478\n"
"                 ADD     R3, R5, #0x28\n"
"                 LDR     R2, [R3,LR]\n"
"                 CMP     R2, R12\n"
"                 ADDGE   R1, R1, #2\n"
"                 ADDLT   R1, R1, #3\n"
" loc_FFD1E478:\n"
"                 CMP     R1, #0x1a\n" // formerly 0xE
"                 MOVGE   R1, #0x1a\n" // formerly 0xE
"                 B       loc_FFD1E4BC\n"
" loc_FFD1E484:\n"
"                 CMP     R0, #0\n"
"                 BGE     loc_FFD1E4BC\n"
"                 ADD     R3, R4, #0x14\n"
"                 LDR     R2, [R3,LR]\n"
"                 CMP     R2, R0\n"
"                 SUBLE   R1, R1, #1\n"
"                 BLE     loc_FFD1E4B4\n"
"                 ADD     R3, R4, #0x28\n"
"                 LDR     R2, [R3,LR]\n"
"                 CMP     R2, R0\n"
"                 SUBLE   R1, R1, #2\n"
"                 SUBGT   R1, R1, #3\n"
" loc_FFD1E4B4:\n"
"                 CMP     R1, #0\n"
"                 MOVLT   R1, #0\n"
" loc_FFD1E4BC:\n"
"                 LDR     R0, =0x73F9C\n"
"                 LDR     R3, [R0]\n"
"                 CMP     R1, R3\n"
"                 LDRNE   R2, =0x73FA0\n"
"                 MOVNE   R3, #1\n"
"                 STRNE   R1, [R0]\n"
"                 STRNE   R3, [R2]\n"
" loc_FFD1E4D8:\n"
"                 LDR     R3, =0x73F9C\n"
"                 LDR     R1, =video_mode\n" // formerly 0x685C
"                 LDR     R0, [R3]\n"
"                 LDR     R2, =CompressionRateTable\n" // formerly 0xFFD1E1F4
"                 LDR     R12, [R1]\n"
"                 LDR     R12, [R12]\n" //  +
"                 LDR     LR, [R2,R0,LSL#2]\n"
"                 LDR     R3, =0x73F94\n"
"                 CMP     R12, #1\n"
"                 STR     R7, [R3]\n"
"                 STR     LR, [R6]\n"
//"                 MOVEQ   R3, #0xB\n" //  -
"                 LDREQ   R3, =video_quality\n" //  +
"                 LDREQ   R3, [R3]\n" //  +
"                 LDREQ   R3, [R3]\n" //  +
"                 STREQ   R3, [R6]\n"
"                 LDMFD   SP!, {R4-R7,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFD1D2E0_my(){
 asm volatile(
"                  STMFD   SP!, {R4-R11,LR}\n"
"                  LDR     R3, =0x73EFC\n"
"                  SUB     SP, SP, #0x30\n"
"                  LDR     R12, [R3]\n" //fps
"                  MOV     R4, #0\n"
"                  LDR     R2, =0x73EC0\n"
"                  LDR     R1, =0x73EC4\n"
"                  LDR     R0, =0x73EE8\n"
"                  MOV     R11, R4\n"
"                  STR     R11, [R2]\n"
"                  STR     R12, [R0]\n"
"                  STR     R11, [R1]\n"
"                  SUB     R3, R12, #0xA\n" //R3=fps-10
"                  CMP     R3, #0x32      \n"
"                  LDRLS   PC, [PC,R3,LSL#2]\n"
"                  B      loc_FFD1D404\n"
"                  .long loc_FFD1D3EC\n" //10fps
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D3EC\n" //15fps
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D3F4\n" //20fps
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D3F4\n" //30fps
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D404\n"
"                  .long loc_FFD1D3FC\n" //60fps
" loc_FFD1D3EC:\n"
"                  MOV     R11, #2 \n"
"                  B      loc_FFD1D414\n"
" loc_FFD1D3F4:\n"
"                  MOV     R11, #4 \n"
"                  B      loc_FFD1D414\n"
" loc_FFD1D3FC:\n"
"                  MOV     R11, #8 \n"
"                  B      loc_FFD1D414\n"
" loc_FFD1D404:\n"
"                  MOV     R1, #0x3B8     \n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #1\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D414:\n"
"                  LDR     R4, =0x73F80\n"
"                  MOV     R1, #0\n"
"                  MOV     R2, R4\n"
"                  MOV     R0, #7\n"
"                  BL            sub_FFC028B8\n" //AllocateExMem
"                  LDR     R5, =0x73EE0\n"
"                  LDR     R1, =0x73EE4\n"
"                  LDR     R3, [R5]\n"
"                  LDR     R2, [R1]\n"
"                  MUL     R12, R3, R2\n"
"                  LDR     R2, =0x73EF8\n"
"                  LDR     R2, [R2]\n" //height
"                  LDR     R1, [R4,#4]\n"
"                  LDR     LR, =0x73EFC\n"
"                  STR     R2, [SP,#0x54-0x2C]\n"
"                  LDR     R7, =0x73EF4\n"
"                  LDR     R3, =0x73ECC\n"
"                  LDR     R2, [R7]\n" //width
"                  LDR     R6, [LR]\n" //fps
"                  LDR     R5, =0x73EDC\n"
"                  LDR     LR, [R3]\n"
"                  LDR     R7, =0x73ED8\n"
"                  LDR     R3, =0x73EE0\n"
"                  LDR     R0, [R4]\n"
"                  LDR     R4, [R5]\n"
"                  LDR     R5, [R7]\n"
"                  LDRH    R7, [R3]\n"
"                  LDR     R3, =0x73EE4\n"
"                  MOV     R12, R12,LSL#13\n"
"                  LDRH    R8, [R3]\n"
"                  LDR     R10, =0xFFD1DAA0\n"
"                  LDR     R9, =0x73EEC\n"
"                  LDR     R3, [SP,#0x54-0x2C]\n"
"                  MOV     R12, R12,LSR#16\n"
"                  STR     R6, [SP,#0x54-0x54]\n"
"                  STR     R4, [SP,#0x54-0x4C]\n"
"                  STR     R5, [SP,#0x54-0x48]\n"
"                  STR     R12, [SP,#0x54-0x44]\n"
"                  STR     R7, [SP,#0x54-0x40]\n"
"                  STR     LR, [SP,#0x54-0x50]\n"
"                  STR     R8, [SP,#0x54-0x3C]\n"
"                  STR     R11, [SP,#0x54-0x38]\n"
"                  STR     R10, [SP,#0x54-0x34]\n"
"                  STR     R9, [SP,#0x54-0x30]\n"
"                  LDR     R4, =0x73F28\n"
"                  BL            sub_FFD1E6BC_my\n" //corrected function
"                  LDR     R12, =0x73F2C\n"
"                  LDR     R3, =0x73F50\n"
"                  LDR     R0, [R4]\n"
"                  LDMIA   R3, {R1,R2}\n"
"                  LDR     R3, [R12]\n"
"                  BL            sub_FFD1E9D4\n"
"                  LDR     R5, =0x73ECC\n"
"                  LDR     R4, =0x73EF4\n"
"                  LDR     R12, [R5]\n"
"                  LDR     R0, [R4]\n"
"                  LDR     R2, =0x73F24\n"
"                  MOV     R3, #0\n"
"                  LDR     R1, =0x73F18\n"
"                  STR     R12, [SP,#0x54-0x54]\n"
"                  BL            sub_FFD1E2E4\n"
"                  LDR     R2, =0x73EF0\n"
"                  LDR     R1, =0x73F30\n"
"                  LDR     R3, [R2]\n"
"                  LDR     R0, [R1]\n"
"                  LDR     R2, =0xFFD1C8AC\n"
"                  ADD     R3, R3, R3,LSL#1\n"
"                  ADD     R3, R3, R0\n"
"                  LDR     R0, [R2,R3,LSL#2]\n"
"                  MOV     R1, #1\n"
"                  BL            sub_FFC822F4\n"
"                  LDR     R0, =0xFFD1D778\n"
"                  MOV     R1, #0\n"
"                  BL            sub_FFC824E4\n"
"                  LDR     R7, =0x73EE4\n"
"                  LDR     R1, =0x73EE0\n"
"                  LDR     R2, [R7]\n"
"                  LDR     R3, [R1]\n"
"                  LDR     R0, =0xFFD1D2D0\n" //SoundDeviceIn
"                  MOV     R1, #0\n"
"                  CMP     R3, #0x10\n"
"                  MOVNE   R5, #0\n"
"                  MOVEQ   R5, #1\n"
"                  CMP     R2, #2\n"
"                  MOVNE   R4, #0\n"
"                  MOVEQ   R4, #1\n"
"                  BL            sub_FFC1DF8C\n"
"                  LDR     R6, =0x6858\n"
"                  TST     R0, #1\n"
"                  STR     R0, [R6]\n"
"                  BEQ     loc_FFD1D590\n"
"                  MOV     R1, #0x3F0\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #2\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D590:\n"
"                  LDR     R0, [R6]\n"
"                  LDR     R1, =0xFFD1DC7C\n"
"                  MOV     R2, #0\n"
"                  BL            sub_FFC1E114\n"
"                  TST     R0, #1\n"
"                  BEQ     loc_FFD1D5B8\n"
"                  MOV     R1, #0x3F4\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #1\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D5B8:\n"
"                  LDR     R3, =0x73DDC\n"
"                  MOV     R1, #0x1E\n"
"                  LDR     R0, [R3]\n"
"                  BL            sub_FFC11B80\n" //TakeSemaphore
"                  CMP     R0, #9\n"
"                  BNE     loc_FFD1D5E0\n"
"                  MOV     R1, #0x3F4\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #3\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D5E0:\n"
"                  LDR     R3, =0x73EDC\n"
"                  LDR     R7, =0x73EE0\n"
"                  LDR     R2, [R3]\n"
"                  LDR     R0, [R6]\n"
"                  LDR     R3, [R7]\n"
"                  MOV     R1, #0\n"
"                  STR     R5, [SP,#0x54-0x54]\n"
"                  STR     R4, [SP,#0x54-0x50]\n"
"                  BL            sub_FFC1E184\n"
"                  TST     R0, #1\n"
"                  BEQ     loc_FFD1D61C\n"
"                  MOV     R1, #0x400\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #8\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D61C:\n"
"                  ADD     R4, SP, #0x54-0x28\n"
"                  MOV     R0, R4\n"
"                  BL            sub_FFD1EF08\n"
"                  LDR     R10, =0xFFD1DCA8\n"
"                  LDR     R3, =0x73ED8\n"
"                  LDR     R0, [R6]\n"
"                  LDR     R2, [R3]\n"
"                  LDR     R1, [SP,#0x54-0x28]\n"
"                  MOV     R7, #0\n"
"                  MOV     R3, R10\n"
"                  STR     R7, [SP,#0x54-0x54]\n"
"                  BL            sub_FFC1E0C8\n"
"                  TST     R0, #1\n"
"                  BEQ     loc_FFD1D664\n"
"                  MOV     R1, #0x410\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  ADD     R1, R1, #6\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D664:\n"
"                  LDR     R2, [SP,#0x54-0x28]\n"
"                  LDR     R5, =0x73F90\n"
"                  LDR     R8, =0x73F88\n"
"                  MOV     R3, #1\n"
"                  MOV     R0, R4\n"
"                  STR     R2, [R8]\n"
"                  STR     R3, [R5]\n"
"                  BL            sub_FFD1EF08\n"
"                  LDR     R4, =0x73ED8\n"
"                  LDR     R0, [R6]\n"
"                  LDR     R2, [R4]\n"
"                  LDR     R1, [SP,#0x54-0x28]\n"
"                  MOV     R3, R10\n"
"                  STR     R7, [SP,#0x54-0x54]\n"
"                  BL            sub_FFC1E0C8\n"
"                  TST     R0, #1\n"
"                  BEQ     loc_FFD1D6B4\n"
"                  LDR     R0, =0xFFD1C938\n"
"                  MOV     R1, #0x420\n"
"                  BL            sub_FFC03B58\n" //DebugAssert
" loc_FFD1D6B4:\n"
"                  LDR     R3, [R5]\n"
"                  LDR     R0, [SP,#0x54-0x28]\n"
"                  LDR     R4, =0x73F7C\n"
"                  LDR     R12, =0xFFD1DBD4\n"
"                  LDR     LR, =0x73ED4\n"
"                  ADD     R2, R3, #1\n"
"                  MOV     R1, #2\n"
"                  AND     R3, R3, #1\n"
"                  STR     R0, [R8,R3,LSL#2]\n"
"                  STR     R2, [R5]\n"
"                  STR     R12, [R4]\n"
"                  STR     R1, [LR]\n"
"                  ADD     SP, SP, #0x30\n"
"                  LDMFD   SP!, {R4-R11,PC}\n"
 );
}

void __attribute__((naked,noinline)) sub_FFD1E6BC_my(){
/*
changes based on comparison of A430 and A420 firmware
current code provides 60 minutes recording time / video in 320x240 and 640x480 mode
*/
 asm volatile(
"                  STMFD   SP!, {R4-R11,LR}\n"
"                  SUB     SP, SP, #0x14\n"
"                  MOV     R9, R2\n"
"                  LDRSH   R2, [SP,#0x38+0x14]\n"
"                  STR     R2, [SP,#0x38-0x28]\n"
"                  LDRSH   R2, [SP,#0x38+0x18]\n"
"                  LDR     R8, =0x742AC\n"
"                  STR     R2, [SP,#0x38-0x2C]\n"
"                  LDRSH   R2, [SP,#0x38+0x1C]\n"
"                  LDR     R11, [SP,#0x38]\n"
"                  STR     R2, [SP,#0x38-0x30]\n"
"                  LDRSH   R10, [SP,#0x38+0x10]\n"
"                  STR     R3, [R8]\n"
"                  LDR     R3, [SP,#0x38+0x8]\n"
"                  LDR     R2, =0x742B4\n"
"                  STR     R3, [R2]\n"
"                  LDR     R2, [SP,#0x38+0xC]\n"
"                  LDR     R12, =0x742B8\n"
"                  LDR     LR, =0x742BC\n"
"                  STR     R2, [R12]\n"
"                  STRH    R10, [LR]\n"
"                  LDR     R3, [SP,#0x38-0x28]\n"
"                  LDR     R4, =0x742BE\n"
"                  STRH    R3, [R4]\n"
"                  LDR     R2, [SP,#0x38-0x2C]\n"
"                  LDR     R5, =0x742C0\n"
"                  STRH    R2, [R5]\n"
"                  LDR     R3, [SP,#0x38-0x30]\n"
"                  LDR     R6, =0x742C2\n"
"                  STRH    R3, [R6]\n"
"                  LDR     R2, [SP,#0x38+0x20]\n"
"                  LDR     R7, =0x742E4\n"
"                  LDR     R3, =0x742A8\n"
"                  STR     R2, [R7]\n"
"                  LDR     R2, =0x742B0\n"
"                  CMP     R9, #0x400\n" //1024x768 video
"                  STR     R9, [R3]\n"
"                  MOV     R4, R0\n"
"                  STR     R11, [R2]\n"
"                  MOV     R6, R1\n"
"                  BNE     loc_FFD1E798\n"
"                  ADD     R2, R11, R11,LSL#1\n" //this is dead code in this camera
"                  RSB     R2, R2, R2,LSL#4\n"
"                  LDR     R12, =0x7424C\n"
"                  LDR     R5, =0x7427C\n"
"                  MOV     R3, #0xB40\n"
"                  ADD     R3, R3, #8\n"
"                  MOV     R1, #0x80000\n"
"                  MOV     R0, R2,LSL#2\n"
"                  STR     R1, [R5]\n"
"                  STR     R0, [R12]\n"
"                  ADD     R12, R3, R2,LSL#6\n"
"                  MOV     R3, #3\n"
"                  STR     R3, [SP,#0x38-0x34]\n"
"                  B      loc_FFD1E864\n"
" loc_FFD1E798:\n" //R8 can be used here
"                  CMP     R9, #0x280\n" //640x480 video
"                  BNE     loc_FFD1E7D4\n"
//"                ADD     R2, R11, R11,LSL#1\n" //old: R2=fps+fps*2 (30)
                     "RSB R8, R11, R11, LSL#4\n" //new: R8=15*fps (150)
//"                RSB     R2, R2, R2,LSL#4\n" //old: R2=15*R2 (450)
                     "RSB R2, R8, R8, LSL#4\n" //new: R2=15*R8 (2250)
"                  LDR     R12, =0x7424C\n"
"                  LDR     R5, =0x7427C\n"
//"                MOV     R3, #0xB40\n"
                     "MOV R3, #0xE100\n"
//"                MOV     R0, R2,LSL#2\n" //old: R0=R2*4 (1800) -> 1800 frames limit (180 sec)
                     "MOV R0, R2, LSL#4\n" //new: R0=R2*16 (36000) -> 36000 frames limit (60 min)
"                  MOV     R1, #0x40000\n"
"                  ADD     R3, R3, #8\n"
"                  STR     R1, [R5]\n"
"                  STR     R0, [R12]\n"
//"                ADD     R12, R3, R2,LSL#6\n" //old: R12=R3+R2*64 (2888+450*64=31688)
                     "ADD R12, R3, R2, LSL#8\n" //new: R12=R3+R2*256 (57608+2250*256=633608)
"                  MOV     R2, #2\n"
"                  B      loc_FFD1E860\n"
" loc_FFD1E7D4:\n" //R8 can be used here
"                  CMP     R9, #0x140\n" //320x240 video
"                  BNE     loc_FFD1E830\n"
//"                ADD     R2, R11, R11,LSL#1\n"
                     "RSB R8, R11, R11, LSL#4\n"
//"                MOV     R3, #0xB40\n"
                     "MOV R3, #0xE100\n"
//"                RSB     R2, R2, R2,LSL#4\n"
                     "RSB R2, R8, R8, LSL#4\n"
"                  ADD     R3, R3, #8\n"
"                  LDR     R5, =0x7427C\n"
"                  LDR     LR, =0x7424C\n"
"                  MOV     R1, #0x20000\n"
//"                MOV     R0, R2,LSL#2\n"
                     "MOV R0, R2, LSL#4\n"
//"                ADD     R12, R3, R2,LSL#6\n"
                     "ADD R12, R3, R2, LSL#8\n"
"                  CMP     R11, #0x3C\n" //the non-existing 60fps mode
"                  MOV     R3, #1\n"
"                  STR     R1, [R5]\n"
"                  STR     R0, [LR]\n"
"                  STR     R3, [SP,#0x38-0x34]\n"
"                  BNE     loc_FFD1E864\n"
//"                RSB     R3, R11, R11,LSL#4\n"
//"                MOV     R2, R3,LSL#6\n"
//"                MOV     R3, R3,LSL#2\n"
//"                STR     R3, [LR]\n"
//"                ADD     R12, R2, #0x3C8\n"
                     "MOV  R3, R8, LSL#2\n"
                     "MOV  R2, #0xE400\n"
                     "STR  R3, [LR]\n"
                     "ADD  R12, R2, #0xC8\n"
"                  B      loc_FFD1E864\n"
" loc_FFD1E830:\n" //160x120 thumbnail video, don't feel the need to touch this
"                  ADD     R2, R11, R11,LSL#1\n"
"                  RSB     R2, R2, R2,LSL#4\n"
"                  LDR     R12, =0x7424C\n"
"                  LDR     R5, =0x7427C\n"
"                  MOV     R3, #0xB40\n"
"                  MOV     R0, R2,LSL#2\n"
"                  MOV     R1, #0x10000\n"
"                  ADD     R3, R3, #8\n"
"                  STR     R1, [R5]\n"
"                  STR     R0, [R12]\n"
"                  ADD     R12, R3, R2,LSL#6\n"
"                  MOV     R2, #0\n"
" loc_FFD1E860:\n"
"                  STR     R2, [SP,#0x38-0x34]\n"
" loc_FFD1E864:\n"
"                  LDR     R3, [SP,#0x38+0x24]\n"
"                  LDR     R2, [R5]\n"
"                  LDR     R1, =0x742B4\n"
"                  STR     R2, [R3]\n"
"                  LDR     R2, =0x742BC\n"
"                  LDR     R0, [R1]\n"
"                  LDRH    R3, [R2]\n"
"                  MUL     R11, R3, R0\n"
"                  ADD     LR, R4, #0xF\n"
"                  BIC     LR, LR, #0xF\n"
"                  ADD     LR, LR, #8\n"
"                  ADD     R5, LR, R12\n"
"                  ADD     R12, R4, R6\n"
"                  LDR     R3, [SP,#0x38+0x4]\n"
"                  MOV     R2, R11,LSL#1\n"
"                  RSB     R12, R5, R12\n"
"                  RSB     R12, R2, R12\n"
"                  SUBS    R3, R3, #0\n"
"                  MOVNE   R3, #1\n"
"                  SUB     R12, R12, #0x10\n"
"                  STR     R3, [SP,#0x38-0x38]\n"
"                  BIC     R12, R12, #0x7F00\n"
"                  LDR     R3, =0x7426C\n"
"                  LDR     R7, =0x742D8\n"
"                  BIC     R12, R12, #0xFF\n"
"                  STR     R12, [R7]\n"
"                  LDR     R10, =0x742D4\n"
"                  STR     R11, [R3]\n"
"                  LDR     R6, =0x742C8\n"
"                  LDR     R3, =0x742CC\n"
"                  LDR     R8, =0x742D0\n"
"                  ADD     R4, R5, R12\n"
"                  STR     LR, [R6]\n"
"                  MOV     R0, R4\n"
"                  STR     R4, [R8]\n"
"                  ADD     R2, R2, #0x10\n"
"                  MOV     R1, #0x80\n"
"                  STR     R5, [R3]\n"
"                  STR     R4, [R10]\n"
"                  BL            sub_FFC81194\n"
"                  LDR     R2, =0x742CC\n"
"                  LDR     R10, [R10]\n"
"                  LDR     R9, [R2]\n"
"                  LDR     LR, =0x62773130\n"
"                  LDR     R12, =0x74228\n"
"                  LDR     R0, =0x7426C\n"
"                  MOV     R1, #0\n"
" loc_FFD1E920:\n"
"                  LDR     R3, [R0]\n"
"                  ADD     R3, R3, #8\n"
"                  MUL     R2, R3, R1\n"
"                  STR     LR, [R10,R2]\n"
"                  STR     R9, [R12,R1,LSL#2]\n"
"                  LDR     R3, [R0]\n"
"                  ADD     R1, R1, #1\n"
"                  ADD     R2, R10, R2\n"
"                  CMP     R1, #1\n"
"                  STR     R3, [R2,#4]\n"
"                  BLE     loc_FFD1E920\n"
"                  LDR     R3, =0x742B0\n"
"                  LDR     R1, [SP,#0x38-0x38]\n"
"                  LDR     R2, [R3]\n"
"                  LDR     R0, [SP,#0x38-0x34]\n"
"                  BL            sub_FFCFB784\n"
"                  LDR     R3, =0x7426C\n"
"                  LDR     R2, [R3]\n"
"                  LDR     R1, =0x74264\n"
"                  ADD     R0, R0, R2\n"
"                  STR     R0, [R1]\n"
"                  ADD     SP, SP, #0x14\n"
"                  LDMFD   SP!, {R4-R11,PC}"
 );
}
