#include "stubs_asm.h"

NHSTUB(kbd_pwr_off, 0xff84b174 )
NHSTUB(MakeAFScan, 0xff946d54)   // Best match: 96%

//vid_bitmap_refresh() routines matched with ixus980_sd990
NHSTUB(ScreenLock, 0xff9dae14) 
NHSTUB(ScreenUnlock, 0xff9dae68) 
NHSTUB(RefreshPhysicalScreen, 0xff9dae68)   // same as ScreenUnlock based on SD980 code

// nullsubs - not needed anymore

NHSTUB(kbd_pwr_on, 0xFF81093C )
NHSTUB(SetZoomActuatorSpeedPercent, 0xFF81093C )

